# TODO: find a way to include variable feasts in the calendar
# basic: [day, feast, rank, commemoration, commemoration]

jan = ['Janarius',
       [1, 'In Circumcisione Domini', 'd. II cl.'],
       [2, 'In Octava S. Stephani', 's.'],
       [3, 'In Octava S. Joannis', 's.'],
       [4, 'In Octava Ss. Innocentium', 's.'],
       [5, 'Sanctissimi Nominis Jesu', 'sd.', 'St. Telesphorus Pope and Martyr'],
       [6, 'In Epiphania Domini',
        'd. I cl. with a privileged Octave of the II rank'],
       [7, 'Secunda die infra Octavam Epiphaniæ', 'sd.'],
       [8, 'Tertia die infra Octavam Epiphaniæ', 'sd.'],
       [9, 'Quarta die infra Octavam Epiphaniæ', 'sd.'],
       [10, 'Quinta die infra Octavam Epiphaniæ', 'sd.'],
       [11, 'Sexta die infra Octavam Epiphaniæ',
            'sd.', 'St. Hyginus Pope and Martyr'],
       [12, 'Septima die infra Octavam Epiphaniæ', 'sd.'],
       [13, 'In Octava Epiphaniæ', 'dm.'],
       [14, 'S. Hilarii Episcopi ECD',
            'd.', 'St. Felix Priest and Martyr'],
       [15, 'S. Pauli Primi Eremitæ C', 'd.', 'St. Maurus'],
       [16, 'S. Marcelli PM', 'sd.'],
       [17, 'S. Antonii Abb', 'd.'],
       [18, 'Cathedræ S. Petri', 'dm.',
            'St. Paul Apostle', 'St. Prisca Virgin and Martyr'],
       [19, 'Ss. Marii, Marthæ, Audifacis, et Abachum Mm',
            's.', 'St. Canute, Martyr'],
       [20, 'Ss. Fabiani et Sebastiani Mm', 'd.'],
       [21, 'S. Agnetis VM', 'd.'],
       [22, 'Ss. Vincentii et Anastasii Mm', 'sd.'],
       [23, 'S. Raymundi de Peñafort C', 'sd.',
            'St. Emerentiana Virgin and Martyr'],
       [24, 'St. Timothy Bishop and Martyr', 'd.'],
       [25, 'Conversion of St. Paul Apostle', 'dm.', 'St. Peter'],
       [26, 'St. Polycarp Bishop and Martyr', 'd.'],
       [27, 'St. John Chrysostom Bishop, Confessor, and Doctor of the Church', 'd.'],
       [28, 'St. Peter Nolasco Confessor', 'd.',
            'St. Agnes Virgin and Martyr second.'],
       [29, 'St. Francis de Sales Bishop, Confessor, and Doctor of the Church', 'd.'],
       [30, 'St. Martina Virgin and Martyr', 'sd.'],
       [31, 'St. John Bosco Confessor', 'd.'],
       ['Sunday between the Circumcision and Epiphany [or January 2, when no such Sunday occurs], The most holy Name of Jesus', 'd. II cl.'],
       ['Sunday within the Octave of the Epiphany, The Most Holy Family of Jesus, Mary, Joseph', 'dm.']
       ]

feb = ['February',
       [1, 'St. Ignatius Bishop and Martyr', 'd.'],
       [2, 'Purification of the Blessed Virgin Mary', 'd. II cl.'],
       [3, 'St. Blase Bishop and Martyr', 's.'],
       [4, 'St. Andrew Corsini Bishop and Confessor', 'd.'],
       [5, 'St. Agatha Virgin Martyr', 'd.'],
       [6, 'St. Titus Bishop and Confessor', 'd.',
        'St. Dorothy Virgin Martyr'],
       [7, 'St. Romuald Abbot', 'd.'],
       [8, 'St. John of Matha Confessor', 'd.'],
       [9, 'St. Cyril Bishop of Alexandria, Confessor, and Doctor of the Church',
        'd.', 'St. Apollonia Virgin Martyr'],
       [10, 'St. Scholastica Virgin', 'd.'],
       [11, 'Apparition of the Blessed Virgin Mary Immaculate', 'dm.'],
       [12, 'The Seven Holy Founders of the Order of Servants of the Blessed Virgin Mary Confessors', 'd.'],
       [13, 'Feria'],
       [14, 'St. Valentine Priest and Martyr', 's.'],
       [15, 'Ss. Faustinus and Jovita Martyrs', 's.'],
       [16, 'Feria'],
       [17, 'Feria'],
       [18, 'St. Simeon Bishop and Martyr', 's.'],
       [19, 'Feria'],
       [20, 'Feria'],
       [21, 'Feria'],
       [22, 'Chair of St. Peter at Antioch', 'dm.', 'St. Paul'],
       [23, 'St. Peter Damian Confessor', 'd.', 'the Vigil'],
       [24, 'St. Matthias Apostle', 'd. II cl.'],
       [25, 'Feria'],
       [26, 'Feria'],
       [27, 'St. Gabriel of Our Lady of Sorrows', 'd.'],
       [28, 'Feria'],
       ['In leap year the month of February is of 29 days, and the Feast of St. Matthias is celebrated on the 25th day and the Feast of St. Gabriel of Our Lady of Sorrows on the 28th day of February, and twice is said Sexto Kalendas, that is on the 24th day and 25th day; and the dominical letter, which was taken up in the month of January, is changed to the preceding; that, if in January, the dominical letter was A, it is changed to the preceding, which is g, etc.; and the letter f is kept twice, on the 24th and 25th.[17]']
       ]

mar = ['March',
       [1, 'Feria'],
       [2, 'Feria'],
       [3, 'Feria'],
       [4, 'St. Casimir Confessor', 'sd.', 'St. Lucius I Pope and Martyr'],
       [5, 'Feria'],
       [6, 'Ss. Perpetua and Felicity Martyrs', 'd.'],
       [7, 'St. Thomas Aquinas Confessor and Doctor of the Church', 'd.'],
       [8, 'St. John of God Confessor', 'd.'],
       [9, 'St. Frances of Rome Widow', 'd.'],
       [10, 'The Forty Holy Martyrs', 'sd.'],
       [11, 'Feria'],
       [12, 'St. Gregory I Pope, Confessor, and Doctor of the Church', 'd.'],
       [13, 'Feria'],
       [14, 'Feria'],
       [15, 'Feria'],
       [16, 'Feria'],
       [17, 'St. Patrick Bishop and Confessor', 'd.'],
       [18, 'St. Cyril Bishop of Jerusalem, Confessor, and Doctor of the Church', 'd.'],
       [19, 'St. Joseph, Spouse of the Blessed Virgin Mary, Confessor', 'd. I cl.'],
       [20, 'Feria'],
       [21, 'St. Benedict Abbot', 'dm.'],
       [22, 'Feria'],
       [23, 'Feria'],
       [24, 'St. Gabriel the Archangel', 'dm.'],
       [25, 'Annunciation of the Blessed Virgin Mary', 'd. I cl.'],
       [26, 'Feria'],
       [27, 'St. John Damascene Confessor and Doctor of the Church', 'd.'],
       [28, 'St. John Capistran Confessor', 'd.'],
       [29, 'Feria'],
       [30, 'Feria'],
       [31, 'Feria'],
       ['Friday after Passion Sunday, Seven Sorrows of the Blessed Virgin Mary', 'dm.', 'Feria']
       ]

apr = ['April',
       [1, 'Feria'],
       [2, 'St. Francis of Paula Confessor', 'd.'],
       [4, 'St. Isidore Bishop, Confessor, and Doctor of the Church', 'd.'],
       [3, 'Feria'],
       [5, 'St. Vincent Ferrer Confessor', 'd.'],
       [6, 'Feria'],
       [7, 'Feria'],
       [8, 'Feria'],
       [9, 'Feria'],
       [10, 'Feria'],
       [11, 'St. Leo I Pope, Confessor, and Doctor of the Church', 'd.'],
       [12, 'Feria'],
       [13, 'St. Hermenegild Martyr', 'sd.'],
       [14, 'St. Justin Martyr', 'd.',
        'Saints Tiburtius, Valerian and Maximus Martyrs'],
       [15, 'Feria'],
       [16, 'Feria'],
       [17, 'St. Anicetus Pope and Martyr', 's.'],
       [18, 'Feria'],
       [19, 'Feria'],
       [20, 'Feria'],
       [21, 'St. Anselm Bishop, Confessor, and Doctor of the Church', 'd.'],
       [22, 'Ss. Soter and Cajus Popes and Martyrs', 'sd.'],
       [23, 'St. George Martyr', 'sd.'],
       [24, 'St. Fidelis of Sigmaringen Martyr', 'd.'],
       [25, 'St. Mark Evangelist', 'd. II cl.'],
       [26, 'Ss. Cletus and Marcellinus Popes and Martyrs', 'sd.'],
       [27, 'St. Peter Canisius Confessor and Doctor of the Church', 'd.'],
       [28, 'St. Paul of the Cross Confessor',
        'd.', 'St. Vitalis Martyr'],
       [29, 'St. Peter of Verona Martyr', 'd.'],
       [30, 'St. Catherine of Siena Virgin', 'd.'],
       ['Wednesday within the second week after the Octave of Easter, Solemnity of St. Joseph, Spouse of the Blessed Virgin Mary, Confessor, and Patron of the Universal Church',
        'd. I cl.' 'with a common Octave(from 1871 to 1954)']
       ]

may = ['May',
       [1, 'Ss. Philip and James Apostles', 'd. II cl.'],
       [2, 'St. Athanasius, Bishop, Confessor, and Doctor of the Church', 'd.'],
       [3, 'Invention of the Holy Cross', 'd. II cl.',
        'Ss. Alexander, Pope, Eventius and Theodulus Martyrs, and Juvenal, Bishop and Confessor'],
       [4, 'St. Monica Widow', 'd.'],
       [5, 'St. Pius V Pope and Confessor', 'd.'],
       [6, 'St. John Apostle before the Latin Gate', 'dm.'],
       [7, 'St. Stanislaus Bishop and Martyr', 'd.'],
       [8, 'Apparition of St. Michael', 'dm.'],
       [9, 'St. Gregory Nazianzen Bishop, Confessor, and Doctor of the Church', 'd.'],
       [10, 'St. Antoninus Bishop and Confessor', 'd.',
            'Ss. Gordian and Epimachus Martyrs'],
       [11, 'Feria'],
       [12, 'Ss. Nereus, Achilleus, Domitilla Virgin, and Pancras Martyrs', 'sd.'],
       [13, 'St. Robert Bellarmine Bishop, Confessor, and Doctor of the Church', 'd.'],
       [14, 'St. Boniface Martyr', 's.'],
       [15, 'St. John Baptist de la Salle Confessor', 'd.'],
       [16, 'St. Ubald Bishop and Confessor', 'sd.'],
       [17, 'St. Paschal Baylon Confessor', 'd.'],
       [18, 'St. Venantius Martyr', 'd.'],
       [19, 'St. Peter Celestine Pope and Confessor',
            'd.', 'St. Pudentiana Virgin'],
       [20, 'St. Bernardine of Siena Confessor', 'sd.'],
       [21, 'Feria'],
       [22, 'Feria'],
       [23, 'Feria'],
       [24, 'Feria'],
       [25, 'St. Gregory VII Pope and Confessor', 'd.',
            'St. Urban I Pope and Martyr', 'd.'],
       [26, 'St. Philip Neri Confessor', 'd.',
        'St. Eleutherius Pope and Martyr'],
       [27, 'St. Bede the Venerable Confessor and Doctor of the Church',
            'd.', 'St. John I Pope and Martyr'],
       [28, 'St. Augustine Bishop and Confessor', 'd.'],
       [29, 'St. Mary Magdalen de Pazzi Virgin', 'sd.'],
       [30, 'St. Felix I Pope and Martyr', 's.'],
       [31, 'Blessed Virgin Mary, Queen', 'd. II cl.',
            'St. Petronilla Virgin']
       ]

jun = ['June',
       [1, 'St. Angela Merici Virgin', 'd.'],
       [2, 'Ss. Marcellinus, Peter, and Erasmus Bishop, Martyrs', 's.'],
       [3, 'Feria'],
       [4, 'St. Francis Caracciolo Confessor', 'd.'],
       [5, 'St. Boniface Bishop and Martyr', 'd.'],
       [6, 'St. Norbert Bishop and Confessor', 'd.'],
       [7, 'Feria'],
       [8, 'Feria'],
       [9, 'Ss. Primus and Felician Martyrs', 's.'],
       [10, 'St. Margaret Queen, Widow', 'sd.'],
       [11, 'St. Barnabas Apostle', 'dm.'],
       [12, 'St. John of San Facundo Confessor', 'd.',
            'Ss. Basilides, Cyrinus, Nabor and Nazarius Martyrs'],
       [13, 'St. Anthony of Padua Confessor and Doctor of the Church', 'd.'],
       [14, 'St. Basil the Great Bishop, Confessor, and Doctor of the Church', 'd.'],
       [15, 'Ss. Vitus, Modestus, and Crescentia Martyrs', 's.'],
       [16, 'Feria'],
       [17, 'Feria'],
       [18, 'St. Ephraem Syrus Deacon, Confessor, and Doctor of the Church',
            'd.', 'Ss. Mark and Marcellianus Martyrs'],
       [19, 'St. Juliana Falconieri Virgin', 'd.',
            'Ss. Gervase and Protase Martyrs'],
       [20, 'St. Silverius Pope and Martyr', 's.'],
       [21, 'St. Aloysius Gonzaga Confessor', 'd.'],
       [22, 'St. Paulinus Bishop and Confessor', 'd.'],
       [23, 'Vigil of the Nativity of St. John the Baptist'],
       [24, 'The Nativity of St. John the Baptist',
           'd. I cl. with a common Octave'],
       [25, ' St. William Abbot', 'd.', ' the Octave'],
       [26, 'Ss. John and Paul Martyrs', 'd.', 'the Octave'],
       [27, 'IV Day within the Octave of St. John the Baptist', 'sd.'],
       [28, 'St. Irenaeus Bishop and Martyr', 'd.',
        'the Octave and of the Vigil'],
       [29, 'Ss. Peter and Paul Apostles', 'd. I cl. with a common Octave'],
       [30, 'Commemoration of St. Paul Apostle', 'dm.',
            'St. Peter Apostle and of the Octave of St. John the Baptist'],
       ]

jul = ['July',
       [1, 'The Most Precious Blood of our Lord Jesus Christ',
        'd. I cl.', 'the Octave day of St. John the Baptist'],
       [2, 'Visitation of the Blessed Virgin Mary', 'd. II cl.',
        'Ss. Processus and Martinian Martyrs'],
       [3, 'St. Leo II Pope and Confessor', 'sd.',
        'the Octave of the Holy Apostles'],
       [4, 'VI day within the Octave of Ss. Peter and Paul Apostles', 'sd.'],
       [5, 'St. Anthony Mary Zaccaria Confessor', 'd.',
        'the Octave of the Holy Apostles'],
       [6, 'Octave of Ss. Peter and Paul Apostles', 'dm.'],
       [7, 'Ss. Cyril and Methodius Bishops and Confessors', 'd.'],
       [8, 'St. Elizabeth Queen, Widow', 'sd.'],
       [9, 'Feria'],
       [10, 'The Seven Holy Brothers Martyrs', 'sd.',
            'Ss. Rufina and Secunda Virgins and Martyrs'],
       [11, 'St. Pius I Pope and Martyr', 's.'],
       [12, 'St. John Gualbert Abbot', 'd.',
            'Ss. Nabor and Felix Martyrs'],
       [13, 'St. Anacletus Pope and Martyr', 'sd.'],
       [14, 'St. Bonaventure Bishop, Confessor, and Doctor of the Church', 'd.'],
       [15, 'St. Henry II Emperor, Confessor', 'sd.'],
       [16, 'Commemoration of the Blessed Virgin Mary of Mt. Carmel', 'dm.'],
       [17, 'St. Alexius Confessor', 'sd.'],
       [18, 'St. Camillus de Lellis Confessor', 'd.',
            'St. Symphorosa and her seven Sons Martyrs'],
       [19, 'St. Vincent de Paul Confessor', 'd.'],
       [20, 'St. Jerome Emiliani Confessor', 'd.',
        'St. Margaret Virgin Martyr'],
       [21, 'St. Praxedes Virgin', 's.'],
       [22, 'St. Mary Magdalene Penitent', 'd.'],
       [23, 'St. Apollinaris Martyr', 'd.',
            'St. Liborius Bishop and Confessor'],
       [24, 'Vigil', 'St. Christina Virgin and Martyr'],
       [25, 'St. James Apostle', 'd. II cl.', 'St. Christopher Martyr'],
       [26, 'St. Anne Mother of the Blessed Virgin Mary', 'd. II cl.'],
       [27, 'St. Pantaleon Martyr', 's.'],
       [28, 'Ss. Nazarius and Celsus Martyrs, Victor I Pope and Martyr, and St. Innocent I Pope and Confessor', 'sd.'],
       [29, 'St. Martha Virgin', 'sd.',
            'Ss. Felix II Pope, Simplicius, Faustinus, and Beatrice Martyrs'],
       [30, 'Ss. Abdon and Sennen Martyrs', 's.'],
       [31, 'St. Ignatius Confessor', 'dm.'],
       ]

aug = ['August',
       [1, 'St. Peter in Chains', 'dm.',
        'St. Paul and the Holy Machabees Martyrs'],
       [2, 'St. Alphonsus Mary of Liguori Bishop, Confessor, and Doctor of the Church',
        'd.', 'St. Stephen I Pope and Martyr'],
       [3, 'Invention of St. Stephen Protomartyr', 'sd.'],
       [4, 'St. Dominic Confessor', 'dm.'],
       [5, 'Dedication of Our Lady of the Snows', 'dm.'],
       [6, 'Transfiguration of our Lord Jesus Christ', 'd. II cl.',
        'Ss. Sixtus II Pope, Felicissimus and Agapitus Martyrs'],
       [7, 'St. Cajetan Confessor', 'd.', 'St. Donatus Bishop and Martyr'],
       [8, 'Ss. Cyriacus, Largus and Smaragdus Martyrs', 'sd.'],
       [9, 'St. John Vianney Confessor and Priest',
        'd.', 'Vigil', 'St. Romanus Martyr'],
       [10, 'St. Laurence Martyr', 'd. II cl. with a simple Octave'],
       [11, 'Ss. Saint Tiburtius and Saint Susanna Virgin, Martyrs', 's.'],
       [12, 'St. Clare Virgin', 'd.'],
       [13, 'Ss. Hippolytus and Cassian Martyrs', 's.'],
       [14, 'Vigil', 'St. Eusebius Confessor'],
       [15, 'Assumption of the Blessed Virgin Mary',
        'd. I cl. with a common Octave'],
       [16, 'St. Joachim Father of the Blessed Virgin Mary, Confessor', 'd. II cl.'],
       [17, 'St. Hyacinth Confessor', 'd.', 'the Octave of the Assumption',
        'the Octave Day of St. Laurence'],
       [18, 'Of the IV day within the Octave of the Assumption',
            'sd.', 'St. Agapitus Martyr'],
       [19, 'St. John Eudes Confessor', 'd.', 'the Octave of the Assumption'],
       [20, 'St. Bernard Abbot, Confessor, and Doctor of the Church',
        'd.', 'the Octave of the Assumption'],
       [21, 'St. Jane Frances de Chantal Widow',
            'd.', 'the Octave of the Assumption'],
       [22, 'Immaculate Heart of the Blessed Virgin Mary', 'd. II cl.',
        'Ss. Timothy, Hippolytus Bishop, and Symphorianus Martyrs'],
       [23, 'St. Philip Benizi Confessor', 'd.', 'Vigil of St. Bartholomew'],
       [24, 'St. Bartholomew Apostle', 'd. II cl.'],
       [25, 'St. Louis King, Confessor', 'sd.'],
       [26, 'St. Zephyrinus Pope Martyr', 's.'],
       [27, 'St. Joseph Calasanctius Confessor', 'd.'],
       [28, 'St. Augustine Bishop, Confessor, and Doctor of the Church',
        'd.', 'St. Hermes Martyr'],
       [29, 'Beheading of St. John the Baptist', 'dm.', 'St. Sabina Martyr'],
       [30, 'St. Rose of St. Mary Virgin of Lima',
            'd.', 'Ss. Felix and Adauctus Martyrs'],
       [31, 'St. Raymond Nonnatus Confessor', 'd.']
       ]

sep = ['September',
       [1, 'St. Giles Abbot', 's.', 'the Holy Twelve Brothers Martyrs'],
       [2, 'St. Stephen King, Confessor', 'sd.'],
       [3, 'St. Pius X Pope and Confessor', 'd.'],
       [4, 'Feria'],
       [5, 'St. Laurence Justinian Bishop and Confessor', 'sd.'],
       [6, 'Feria'],
       [7, 'Feria'],
       [8, 'Nativity of the Blessed Virgin Mary',
        'd. II cl. with a Simple Octave', 'St. Adrian Martyr'],
       [9, 'St. Gorgonius Martyr', 's.'],
       [10, 'St. Nicholas of Tolentino Confessor', 'd.'],
       [11, 'Ss. Protus and Hyacinth Martyrs', 's.'],
       [12, 'The Most Holy Name of Mary', 'dm.'],
       [13, 'Feria'],
       [14, 'Exaltation of the Holy Cross', 'dm.'],
       [15, 'Seven Sorrows of the Blessed Virgin Mary',
        'd. II cl.', 'St. Nicomedes Martyr'],
       [16, 'St. Cornelius Pope and St. Cyprian Bishop, Martyrs',
        'sd.', 'Ss. Euphemia Virgin, Lucy and Geminian Martyrs'],
       [17, 'Impression of the sacred Stigmata of St. Francis Confessor', 'd.'],
       [18, 'St. Joseph of Cupertino Confessor', 'd.'],
       [19, 'St. Januarius Bishop and Companions Martyrs', 'd.'],
       [20, 'St. Eustace and Companions Martyrs', 'd.', 'Vigil of St. Matthew'],
       [21, 'St. Matthew Apostle and Evangelist', 'd. II cl.'],
       [22, 'St. Thomas of Villanova Bishop and Confessor',
        'd.', 'Ss. Maurice and Companions Martyrs'],
       [23, 'St. Linus Pope and Martyr', 'sd.',
        'St. Thecla Virgin and Martyr'],
       [24, ' Our Lady of Ransom', 'dm.'],
       [25, 'Feria'],
       [26, 'Ss. Cyprian and Justina Virgin, Martyrs', 's.'],
       [27, 'Ss. Cosmas and Damian Martyrs', 'sd.'],
       [28, 'St. Wenceslaus Duke, Martyr', 'sd.'],
       [29, 'Dedication of St. Michael Archangel', 'd. I cl.'],
       [30, 'St. Jerome Priest, Confessor, and Doctor of the Church', 'd.']
       ]
okt = ['October',
       [1, 'St. Remigius Bishop and Confessor', 's.'],
       [2, 'The Holy Guardian Angels', 'dm.'],
       [3, 'St. Teresa of the Child Jesus Virgin', 'd.'],
       [4, 'St. Francis of Assisi Confessor', 'dm.'],
       [5, 'St. Placid and companions Martyrs', 's.'],
       [6, 'St. Bruno Confessor', 'd.'],
       [7, 'The most Holy Rosary of the Blessed Virgin Mary', 'd. II cl.',
           'St. Mark Pope and Confessor, and Ss. Sergius, Bacchus, Marcellus and Apuleius Martyrs'],
       [8, 'St. Bridget Widow', 'd.'],
       [9, 'St. John Leonard Confessor', 'sd.',
           'Ss. Denis Bishop, Rusticus Priest, and Eleutherius Martyrs'],
       [10, 'St. Francis Borgia Confessor', 'sd.'],
       [11, 'The Maternity of the Blessed Virgin Mary', 'd. II cl.'],
       [12, 'Feria'],
       [13, 'St. Edward King, Confessor', 'sd.'],
       [14, 'St. Callistus I Pope and Martyr', 'd.'],
       [15, 'St. Teresa Virgin', 'd.'],
       [16, 'St. Hedwig Widow', 'sd.'],
       [17, 'St. Margaret Mary Alacoque Virgin', 'd.'],
       [18, 'St. Luke Evangelist', 'd. II cl.'],
       [19, 'St. Peter of Alcantara Confessor', 'd.'],
       [20, 'St. John Cantius Confessor', 'd.'],
       [21, 'St. Hilarion Abbot', 's.',
           'St. Ursula and Companions Virgins and Martyrs'],
       [22, 'Feria'],
       [23, 'Feria'],
       [24, 'St. Raphael Archangel', 'dm.'],
       [25, 'Ss. Chrysanthus and Daria Martyrs', 's.'],
       [26, 'St. Evaristus Pope and Martyr', 's.'],
       [27, 'Vigil of Ss. Simon and Jude'],
       [28, 'Ss. Simon and Jude Apostles', 'd. II cl.'],
       [29, 'Feria'],
       [30, 'Feria'],
       [31, 'Vigil of All Saints'],
       ['Last Sunday in October, The Feast of our Lord Jesus Christ the King',
           'd. I cl.', 'the Sunday']
       ]

nov = ['November',
       [1, 'All Saints', 'd. I cl. with a common Octave'],
       [2, 'or , if 2 November is a Sunday, 3 November, Commemoration of all the Faithful Departed', 'd.'],
       [3, 'Of the III day within the Octave of All Saints', 'sd.'],
       [4, 'St. Charles Bishop and Confessor', 'd.',
        'the Octave of All Saints', 'and Ss. Vitalis and Agricola Martyrs'],
       [5, 'Of the V day within the Octave of All Saints', 'sd.'],
       [6, 'Of the VI day within the Octave of All Saints', 'sd.'],
       [7, 'Of the VII day within the Octave of All Saints', 'sd.'],
       [8, 'Octave of All Saints', 'dm.', 'the Holy Four Crowned Martyrs'],
       [9, 'Dedication of the Archbasilica of the most Holy Saviour',
        'd. II cl.', 'St. Theodore Martyr'],
       [10, 'St. Andrew Avellino Confessor', 'd.',
        'Ss. Tryphon, Respicius, and Nympha Martyrs'],
       [11, 'St. Martin Bishop and Confessor', 'd.', 'St. Mennas Martyr'],
       [12, 'St. Martin I Pope and Martyr', 'sd.'],
       [13, 'St. Didacus Confessor', 'sd.'],
       [14, 'St. Josaphat Bishop and Martyr', 'd.'],
       [15, 'St. Albert the Great Bishop, Confessor, and Doctor of the Church', 'd.'],
       [16, 'St. Gertrude Virgin', 'd.'],
       [17, 'St. Gregory Thaumaturgus Bishop and Confessor', 'sd.'],
       [18, 'Dedication of the Basilicas of Ss. Peter and Paul', 'dm.'],
       [19, 'St. Elisabeth Widow', 'd.', 'St. Pontianus Pope and Martyr'],
       [20, 'St. Felix of Valois Confessor', 'd.'],
       [21, 'Presentation of the Blessed Virgin Mary', 'dm.'],
       [22, 'St. Cecilia Virgin and Martyr', 'd.'],
       [23, 'St. Clement I Pope and Martyr', 'd.', 'St. Felicitas Martyr'],
       [24, 'St. John of the Cross Confessor and Doctor of the Church',
        'd.', 'Com. St. Chrysogonus Martyr'],
       [25, 'St. Catherine Virgin and Martyr', 'd.'],
       [26, 'St. Sylvester Abbot', 'd.', 'St. Peter of Alexandria Bishop and Martyr'],
       [27, 'Feria'],
       [28, 'Feria'],
       [29, 'Vigil of St. Andrew',  'Commemoration of St. Saturninus'],
       [30, 'St. Andrew Apostle', 'd. II cl.']
       ]

dec = ['December',
       [1, 'Feria'],
       [2, 'St. Bibiana Virgin and Martyr', 'sd.'],
       [3, 'St. Francis Xavier Confessor', 'dm.'],
       [4, 'St. Peter Chrysologus Bishop, Confessor, and Doctor of the Church',
        'd.', 'St. Barbara Virgin and Martyr'],
       [5, 'St. Sabbas Abbot'],
       [6, 'St. Nicholas Bishop and Confessor', 'd.'],
       [7, 'St. Ambrose Bishop, Confessor, and Doctor of the Church',
        'd.', 'Vigil of the Immaculate Conception'],
       [8, 'The Immaculate Conception of the Blessed Virgin Mary',
        'd. I cl. with a common Octave'],
       [9, 'Of the II day within the Octave of the Immaculate Conception', 'sd.'],
       [10, 'Of the III day within the Octave of the Immaculate Conception',
        'sd.', 'St. Melchiades Pope and Martyr'],
       [22, 'Feria'],
       [11, 'St. Damasus I Pope and Confessor', 'sd.',
        'Octave of the Immaculate Conception'],
       [12, 'Of the V day within the Octave of the Immaculate Conception', 'sd.'],
       [13, 'St. Lucy Virgin and Martyr', 'd.',
        'Octave of the Immaculate Conception'],
       [14, 'Of the VII day within the Octave of the Immaculate Conception', 'sd.'],
       [15, 'Octave of the Immaculate Conception', 'dm.'],
       [16, 'St. Eusebius Bishop and Martyr', 'sd.'],
       [17, 'Feria'],
       [18, 'Feria'],
       [19, 'Feria'],
       [20, 'Vigil of St. Thomas'],
       [21, 'St. Thomas Apostle', 'd. II cl.'],
       [23, 'Feria'],
       [24, 'Vigil'],
       [25, 'Nativity of our Lord Jesus Christ',
        'd. I cl. with a privileged Octave of the III rank'],
       [26, 'St. Stephen Protomartyr', 'd. II cl. with a simple Octave',
        'the Octave of the Nativity'],
       [27, 'St. John Apostle and Evangelist',
        'd. II cl. with a simple Octave', 'the Octave of the Nativity'],
       [28, 'The Holy Innocents', 'd. II cl. with a simple Octave',
        'the Octave of the Nativity'],
       [29, 'St. Thomas Bishop and Martyr', 'd.', 'the Octave of the Nativity'],
       [30, 'Of the VI day within the Octave of the Nativity', 'sd.'],
       [31, 'St. Sylvester I Pope and Confessor',
           'd.', 'the Octave of the Nativity']
       ]
