
[January]
[1, 'Circumcision of the Lord and Octave of the Nativity', Double of the II Class.]
[2, 'Octave of St. Stephen Protomartyr', Simple.]
[3, 'Octave of St. John Apostle and Evangelist', Simple.]
[4, 'Octave of the Holy Innocents Martyrs', Simple.]
[5, 'Vigil of the Epiphany', Semidouble, Com. of 'St. Telesphorus Pope and Martyr']
[6, 'Epiphany of the Lord', Double of the I Class with a privileged Octave of the II rank.]
[7, 'Of the II day within the Octave of the Epiphany', Semidouble.]
[8, 'Of the III day within the Octave of the Epiphany', Semidouble.]
[9, 'Of the IV day within the Octave of the Epiphany', Semidouble.]
[10, 'Of the V day within the Octave of the Epiphany', Semidouble.]
[11, 'Of the VI day within the Octave of the Epiphany', Semidouble, 'Com. of St. Hyginus Pope and Martyr']
[12, 'Of the VII day within the Octave of the Epiphany', Semidouble.]
[13, 'Octave of the Epiphany', Greater Double.]
[14, 'St. Hilary Bishop, Confessor, and Doctor of the Church', Double, 'Com. of St. Felix Priest and Martyr']
[15, 'St. Paul first hermit, Confessor', Double, 'Com. of St. Maurus']
[16, 'St. Marcellus I Pope and Martyr', Semidouble.]
[17, 'St. Anthony Abbot', Double.]
[18, 'Chair of St. Peter Apostle at Rome', Greater Double, 'Com. of St. Paul Apostle', and of 'St. Prisca Virgin and Martyr']
[19, 'Ss. Marius, Martha, Audifax, and Abachum Martyrs', Simple, 'Com. of St. Canute, Martyr']
[20, 'Ss. Fabian Pope and Sebastian Martyrs', Double.]
[21, 'St. Agnes, Roman Virgin and Martyr', Double]
[22, 'Ss. Vincent and Anastasius Martyrs', Semidouble.]
[23, 'St. Raymund of Peñafort Confessor', Semidouble, 'Com. of St. Emerentiana Virgin and Martyr']
[24, 'St. Timothy Bishop and Martyr', Double.]
[25, 'Conversion of St. Paul Apostle', Greater Double, Com. of St. Peter.]
[26, 'St. Polycarp Bishop and Martyr', Double.]
[27, 'St. John Chrysostom Bishop, Confessor, and Doctor of the Church', Double.]
[28, 'St. Peter Nolasco Confessor', Double, 'Com. of St. Agnes Virgin and Martyr second.']
[29, 'St. Francis de Sales Bishop, Confessor, and Doctor of the Church', Double.]
[30, 'St. Martina Virgin and Martyr', Semidouble.]
[31, 'St. John Bosco Confessor', Double.]
[Sunday between the Circumcision and Epiphany [or January 2, when no such Sunday occurs], The most holy Name of Jesus, Double of the II Class.]
[Sunday within the Octave of the Epiphany, The Most Holy Family of Jesus, Mary, Joseph, Greater Double.]

[February]
[1, 'St. Ignatius Bishop and Martyr', Double.]
[2, 'Purification of the Blessed Virgin Mary', Double of the II Class.]
[3, 'St. Blase Bishop and Martyr', Simple.]
[4, 'St. Andrew Corsini Bishop and Confessor', Double.]
[5, 'St. Agatha Virgin Martyr', Double.]
[6, 'St. Titus Bishop and Confessor', Double, 'Com. of St. Dorothy Virgin Martyr']
[7, St. Romuald Abbot, Double.]
[8, St. John of Matha Confessor, Double.]
[9, St. Cyril Bishop of Alexandria, Confessor, and Doctor of the Church, Double, Com. of St. Apollonia Virgin Martyr.]
[10, St. Scholastica Virgin, Double.]
[11, Apparition of the Blessed Virgin Mary Immaculate, Greater Double.]
[12, The Seven Holy Founders of the Order of Servants of the Blessed Virgin Mary Confessors, Double.]
[13, Feria]
[14, St. Valentine Priest and Martyr, Simple.]
[15, Ss. Faustinus and Jovita Martyrs, Simple.]
[16, Feria]
[17, Feria]
[18, St. Simeon Bishop and Martyr, Simple.]
[19, Feria]
[20, Feria]
[21, Feria]
[22, Chair of St. Peter at Antioch, Greater Double, Com. of St. Paul.]
[23, St. Peter Damian Confessor, Double, Com. of the Vigil.]
[24, St. Matthias Apostle, Double of the II Class.]
[25, Feria]
[26, Feria]
[27, St. Gabriel of Our Lady of Sorrows, Double]
[28, Feria]
[In leap year the month of February is of 29 days, and the Feast of St. Matthias is celebrated on the 25th day and the Feast of St. Gabriel of Our Lady of Sorrows on the 28th day of February, and twice is said Sexto Kalendas, that is on the 24th day and 25th day; and the dominical letter, which was taken up in the month of January, is changed to the preceding; that, if in January, the dominical letter was A, it is changed to the preceding, which is g, etc.; and the letter f is kept twice, on the 24th and 25th.[17]]

[March[edit]]
[1, Feria]
[2, Feria]
[3, Feria]
[4, St. Casimir Confessor, Semidouble, Com. of St. Lucius I Pope and Martyr.]
[5, Feria]
[6, Ss. Perpetua and Felicity Martyrs, Double.]
[7, St. Thomas Aquinas Confessor and Doctor of the Church, Double.]
[8, St. John of God Confessor, Double.]
[9, St. Frances of Rome Widow, Double.]
[10, The Forty Holy Martyrs, Semidouble.]
[11, Feria]
[12, St. Gregory I Pope, Confessor, and Doctor of the Church, Double.]
[13, Feria]
[14, Feria]
[15, Feria]
[16, Feria]
[17, St. Patrick Bishop and Confessor, Double.]
[18, St. Cyril Bishop of Jerusalem, Confessor, and Doctor of the Church, Double.]
[19, St. Joseph, Spouse of the Blessed Virgin Mary, Confessor, Double of the I Class.]
[20, Feria]
[21, St. Benedict Abbot, Greater Double.]
[22, Feria]
[23, Feria]
[24, St. Gabriel the Archangel, Greater Double.]
[25, Annunciation of the Blessed Virgin Mary, Double of the I Class.]
[26, Feria]
[27, St. John Damascene Confessor and Doctor of the Church, Double]
[28, St. John Capistran Confessor, Double]
[29, Feria]
[30, Feria]
[31, Feria]
[Friday after Passion Sunday, Seven Sorrows of the Blessed Virgin Mary, Greater Double, Com. of the Feria.]

[April[edit]]
[1, Feria]
[2, St. Francis of Paula Confessor, Double.]
[3, Feria]
[4, St. Isidore Bishop, Confessor, and Doctor of the Church, Double.]
[5, St. Vincent Ferrer Confessor, Double.]
[6, Feria]
[7, Feria]
[8, Feria]
[9, Feria]
[10, Feria]
[11, St. Leo I Pope, Confessor, and Doctor of the Church, Double.]
[12, Feria]
[13, St. Hermenegild Martyr, Semidouble.]
[14, St. Justin Martyr, Double, Com. of Saints Tiburtius, Valerian and Maximus, Martyrs.]
[15, Feria]
[16, Feria]
[17, St. Anicetus Pope and Martyr, Simple.]
[18, Feria]
[19, Feria]
[20, Feria]
[21, St. Anselm Bishop, Confessor, and Doctor of the Church, Double.]
[22, Ss. Soter and Cajus Popes and Martyrs, Semidouble.]
[23, St. George Martyr, Semidouble.]
[24, St. Fidelis of Sigmaringen Martyr, Double.]
[25, St. Mark Evangelist, Double of the II Class.]
[26, Ss. Cletus and Marcellinus Popes and Martyrs, Semidouble.]
[27, St. Peter Canisius Confessor and Doctor of the Church, Double.]
[28, St. Paul of the Cross Confessor, Double, Com. of St. Vitalis Martyr.]
[29, St. Peter of Verona Martyr, Double.]
[30, St. Catherine of Siena Virgin, Double.]
[Wednesday within the second week after the Octave of Easter, Solemnity of St. Joseph, Spouse of the Blessed Virgin Mary, Confessor, and Patron of the Universal Church, Double of the I Class with a common Octave (from 1871 to 1954)]

[May[edit]]
[1, Ss. Philip and James Apostles, Double of the II Class.]
[2, St. Athanasius, Bishop, Confessor, and Doctor of the Church, Double.]
[3, Invention of the Holy Cross, Double of the II Class, Com. of Ss. Alexander, Pope, Eventius and Theodulus Martyrs, and Juvenal, Bishop and Confessor.]
[4, St. Monica Widow, Double.]
[5, St. Pius V Pope and Confessor, Double.]
[6, St. John Apostle before the Latin Gate, Greater Double.]
[7, St. Stanislaus Bishop and Martyr, Double.]
[8, Apparition of St. Michael, Greater Double]
[9, St. Gregory Nazianzen Bishop, Confessor, and Doctor of the Church, Double.]
[10, St. Antoninus Bishop and Confessor, Double, Com. of Ss. Gordian and Epimachus Martyrs.]
[11, Feria]
[12, Ss. Nereus, Achilleus, Domitilla Virgin, and Pancras Martyrs, Semidouble.]
[13, St. Robert Bellarmine Bishop, Confessor, and Doctor of the Church, Double.]
[14, St. Boniface Martyr, Simple.]
[15, St. John Baptist de la Salle Confessor, Double.]
[16, St. Ubald Bishop and Confessor, Semidouble.]
[17, St. Paschal Baylon Confessor, Double.]
[18, St. Venantius Martyr, Double.]
[19, St. Peter Celestine Pope and Confessor, Double, Com. of St. Pudentiana Virgin.]
[20, St. Bernardine of Siena Confessor, Semidouble.]
[21, Feria]
[22, Feria]
[23, Feria]
[24, Feria]
[25, St. Gregory VII Pope and Confessor, Double, Com. of St. Urban I Pope and Martyr, Double.]
[26, St. Philip Neri Confessor, Double, Com. of St. Eleutherius Pope and Martyr.]
[27, St. Bede the Venerable Confessor and Doctor of the Church, Com. of St. John I Pope and Martyr, Double.]
[28, St. Augustine Bishop and Confessor, Double.]
[29, St. Mary Magdalen de Pazzi Virgin, Semidouble.]
[30, St. Felix I Pope and Martyr, Simple.]
[31, Blessed Virgin Mary, Queen Double of the II Class, Com. of St. Petronilla Virgin.]
[June[edit]]
[1, St. Angela Merici Virgin, Double.]
[2, Ss. Marcellinus, Peter, and Erasmus Bishop, Martyrs, Simple.]
[3, Feria]
[4, St. Francis Caracciolo Confessor, Double.]
[5, St. Boniface Bishop and Martyr, Double.]
[6, St. Norbert Bishop and Confessor, Double.]
[7, Feria]
[8, Feria]
[9, Ss. Primus and Felician Martyrs, Simple.]
[10, St. Margaret Queen, Widow, Semidouble.]
[11, St. Barnabas Apostle, Greater Double.]
[12, St. John of San Facundo Confessor, Double, Com. of Ss. Basilides, Cyrinus, Nabor and Nazarius Martyrs.]
[13, St. Anthony of Padua Confessor and Doctor of the Church, Double.]
[14, St. Basil the Great Bishop, Confessor, and Doctor of the Church, Double.]
[15, Ss. Vitus, Modestus, and Crescentia Martyrs, Simple.]
[16, Feria]
[17, Feria]
[18, St. Ephraem Syrus Deacon, Confessor, and Doctor of the Church, Double, Com. of Ss. Mark and Marcellianus Martyrs.]
[19, St. Juliana Falconieri Virgin, Double, Com. of Ss. Gervase and Protase Martyrs.]
[20, St. Silverius Pope and Martyr, Simple.]
[21, St. Aloysius Gonzaga Confessor, Double.]
[22, St. Paulinus Bishop and Confessor, Double]
[23, Vigil.]
[24, The Nativity of St. John the Baptist, Double of the I Class with a common Octave.]
[25, St. William Abbot, Double, Com. of the Octave.]
[26, Ss. John and Paul Martyrs, Double, Com. of the Octave.]
[27, Of the IV day within the Octave of St. John the Baptist, Semidouble.]
[28, St. Irenaeus Bishop and Martyr, Double, Com. of the Octave and of the Vigil.]
[29, Ss. Peter and Paul Apostles, Double of the I Class with a common Octave.]
[30, Commemoration of St. Paul Apostle, Greater Double, Com. of St. Peter Apostle and of the Octave of St. John the Baptist.]
[July[edit]]
[1, The Most Precious Blood of our Lord Jesus Christ, Double of the I Class, Com. of the Octave day of St. John the Baptist.]
[2, Visitation of the Blessed Virgin Mary, Double of the II Class, Com. of Ss. Processus and Martinian Martyrs.]
[3, St. Leo II Pope and Confessor, Semidouble, Com. of the Octave of the Holy Apostles.]
[4, Of the VI day within the Octave of Ss. Peter and Paul Apostles, Semidouble.]
[5, St. Anthony Mary Zaccaria Confessor, Double, Com. of the Octave of the Holy Apostles.]
[6, Octave of Ss. Peter and Paul Apostles, Greater Double.]
[7, Ss. Cyril and Methodius Bishops and Confessors, Double.]
[8, St. Elizabeth Queen, Widow, Semidouble.]
[9, Feria]
[10, The Seven Holy Brothers Martyrs, Semidouble, and Ss. Rufina and Secunda Virgins and Martyrs.]
[11, St. Pius I Pope and Martyr, Simple.]
[12, St. John Gualbert Abbot, Double, Com. of Ss. Nabor and Felix Martyrs.]
[13, St. Anacletus Pope and Martyr, Semidouble.]
[14, St. Bonaventure Bishop, Confessor, and Doctor of the Church, Double.]
[15, St. Henry II Emperor, Confessor, Semidouble.]
[16, Commemoration of the Blessed Virgin Mary of Mt. Carmel, Greater Double.]
[17, St. Alexius Confessor, Semidouble.]
[18, St. Camillus de Lellis Confessor, Double, Com. of St. Symphorosa and her seven Sons Martyrs.]
[19, St. Vincent de Paul Confessor, Double.]
[20, St. Jerome Emiliani Confessor, Double, Com. of St. Margaret Virgin Martyr.]
[21, St. Praxedes Virgin, Simple.]
[22, St. Mary Magdalene Penitent, Double.]
[23, St. Apollinaris Martyr, Double, Com. of St. Liborius Bishop and Confessor.]
[24, Vigil. Com. of St. Christina Virgin and Martyr.]
[25, St. James Apostle, Double of the II Class, Com. of St. Christopher Martyr.]
[26, St. Anne Mother of the Blessed Virgin Mary, Double of the II Class.]
[27, St. Pantaleon Martyr, Simple.]
[28, Ss. Nazarius and Celsus Martyrs, Victor I Pope and Martyr, and St. Innocent I Pope and Confessor, Semidouble.]
[29, St. Martha Virgin, Semidouble, Com. of Ss. Felix II Pope,[18] Simplicius, Faustinus, and Beatrice Martyrs.]
[30, Ss. Abdon and Sennen Martyrs, Simple.]
[31, St. Ignatius Confessor, Greater Double.]
[August[edit]]
[1, St. Peter in Chains, Greater Double, Com. of St. Paul and the Holy Machabees Martyrs.]
[2, St. Alphonsus Mary of Liguori Bishop, Confessor, and Doctor of the Church, Double, Com. of St. Stephen I Pope and Martyr.]
[3, Invention of St. Stephen Protomartyr, Semidouble.]
[4, St. Dominic Confessor, Greater Double.]
[5, Dedication of Our Lady of the Snows, Greater Double.]
[6, Transfiguration of our Lord Jesus Christ, Double of the II Class, Com. of Ss. Sixtus II Pope, Felicissimus and Agapitus Martyrs.]
[7, St. Cajetan Confessor, Double, Com. of St. Donatus Bishop and Martyr.]
[8, Ss. Cyriacus, Largus and Smaragdus Martyrs, Semidouble.]
[9, St. John Vianney Confessor and Priest, Double, Com. of the Vigil and St. Romanus Martyr.]
[10, St. Laurence Martyr, Double of the II Class with a simple Octave.]
[11, Ss. Saint Tiburtius and Saint Susanna Virgin, Martyrs, Simple.]
[12, St. Clare Virgin, Double.]
[13, Ss. Hippolytus and Cassian Martyrs, Simple.]
[14, Vigil. Com. of St. Eusebius Confessor.]
[15, Assumption of the Blessed Virgin Mary, Double of the I Class with a common Octave.]
[16, St. Joachim Father of the Blessed Virgin Mary, Confessor, Double of the II Class.]
[17, St. Hyacinth Confessor, Double, Com. of the Octave of the Assumption and the Octave Day of St. Laurence.]
[18, Of the IV day within the Octave of the Assumption, Semidouble, Com. of St. Agapitus Martyr.]
[19, St. John Eudes Confessor, Double, Com. of the Octave of the Assumption.]
[20, St. Bernard Abbot, Confessor, and Doctor of the Church, Double, Com. of the Octave of the Assumption.]
[21, St. Jane Frances de Chantal Widow, Double, Com. of the Octave of the Assumption.]
[22, Immaculate Heart of the Blessed Virgin Mary, Double of the II Class, Com. of Ss. Timothy, Hippolytus Bishop, and Symphorianus Martyrs.]
[23, St. Philip Benizi Confessor, Double, Com. of the Vigil.]
[24, St. Bartholomew Apostle, Double of the II Class.]
[25, St. Louis King, Confessor, Semidouble.]
[26, St. Zephyrinus Pope Martyr, Simple.]
[27, St. Joseph Calasanctius Confessor, Double.]
[28, St. Augustine Bishop, Confessor, and Doctor of the Church, Double, Com. of St. Hermes Martyr.]
[29, Beheading of St. John the Baptist, Greater Double, Com. of St. Sabina Martyr.]
[30, St. Rose of St. Mary Virgin of Lima, Double, Com. of Ss. Felix and Adauctus Martyrs.]
[31, St. Raymond Nonnatus Confessor, Double.]
[September[edit]]
[1, St. Giles Abbot, Simple, Com. of the Holy Twelve Brothers Martyrs.]
[2, St. Stephen King, Confessor, Semidouble.]
[3, St. Pius X Pope and Confessor, Double.]
[4, Feria]
[5, St. Laurence Justinian Bishop and Confessor, Semidouble.]
[6, Feria]
[7, Feria]
[8, Nativity of the Blessed Virgin Mary, Double of the II Class with a simple Octave, Com. of St. Adrian Martyr.]
[9, St. Gorgonius Martyr, Simple.]
[10, St. Nicholas of Tolentino Confessor, Double.]
[11, Ss. Protus and Hyacinth Martyrs, Simple.]
[12, The Most Holy Name of Mary, Greater Double.]
[13, Feria]
[14, Exaltation of the Holy Cross, Greater Double.]
[15, Seven Sorrows of the Blessed Virgin Mary, Double of the II Class, Com. of St. Nicomedes Martyr.]
[16, St. Cornelius Pope and St. Cyprian Bishop, Martyrs, Semidouble, Com. of Ss. Euphemia Virgin, Lucy and Geminian Martyrs.]
[17, Impression of the sacred Stigmata of St. Francis Confessor, Double.]
[18, St. Joseph of Cupertino Confessor, Double.]
[19, St. Januarius Bishop and Companions Martyrs, Double.]
[20, St. Eustace and Companions Martyrs, Double, Com. of the Vigil.]
[21, St. Matthew Apostle and Evangelist, Double of the II Class.]
[22, St. Thomas of Villanova Bishop and Confessor, Double, Com. of Ss. Maurice and Companions Martyrs.]
[23, St. Linus Pope and Martyr, Semidouble, Com. of St. Thecla Virgin and Martyr.]
[24, Our Lady of Ransom, Greater Double.]
[25, Feria]
[26, Ss. Cyprian and Justina Virgin, Martyrs, Simple.]
[27, Ss. Cosmas and Damian Martyrs, Semidouble.]
[28, St. Wenceslaus Duke, Martyr, Semidouble.]
[29, Dedication of St. Michael Archangel, Double of the I Class.]
[30, St. Jerome Priest, Confessor, and Doctor of the Church, Double.]
[October[edit]]
[1, St. Remigius Bishop and Confessor, Simple.]
[2, The Holy Guardian Angels, Greater Double.]
[3, St. Teresa of the Child Jesus Virgin, Double.]
[4, St. Francis of Assisi Confessor, Greater Double.]
[5, St. Placid and companions Martyrs, Simple.]
[6, St. Bruno Confessor, Double.]
[7, The most Holy Rosary of the Blessed Virgin Mary, Double of the II Class, Com. of St. Mark Pope and Confessor, and Ss. Sergius, Bacchus, Marcellus and Apuleius Martyrs.]
[8, St. Bridget Widow, Double.]
[9, St. John Leonard Confessor, Semidouble, Com. of Ss. Denis Bishop, Rusticus Priest, and Eleutherius Martyrs.]
[10, St. Francis Borgia Confessor, Semidouble.]
[11, The Maternity of the Blessed Virgin Mary, Double of the II Class.]
[12, Feria]
[13, St. Edward King, Confessor, Semidouble.]
[14, St. Callistus I Pope and Martyr, Double.]
[15, St. Teresa Virgin, Double.]
[16, St. Hedwig Widow, Semidouble.]
[17, St. Margaret Mary Alacoque Virgin, Double.]
[18, St. Luke Evangelist, Double of the II Class.]
[19, St. Peter of Alcantara Confessor, Double.]
[20, St. John Cantius Confessor, Double.]
[21, St. Hilarion Abbot, Simple, Com. of St. Ursula and Companions Virgins and Martyrs.]
[22, Feria]
[23, Feria]
[24, St. Raphael Archangel, Greater Double.]
[25, Ss. Chrysanthus and Daria Martyrs, Simple.]
[26, St. Evaristus Pope and Martyr, Simple.]
[27, Vigil.]
[28, Ss. Simon and Jude Apostles, Double of the II Class.]
[29, Feria]
[30, Feria]
[31, Vigil.]
[Last Sunday in October, The Feast of our Lord Jesus Christ the King, Double of the I Class, Com. of the Sunday.]

[November[edit]]
[1, All Saints, Double of the I Class with a common Octave.]
[2 or, if 2 November is a Sunday, 3 November, Commemoration of all the Faithful Departed, Double]
[3, Of the III day within the Octave of All Saints, Semidouble.]
[4, St. Charles Bishop and Confessor, Double, Com. of the Octave of All Saints and Ss. Vitalis and Agricola Martyrs.]
[5, Of the V day within the Octave of All Saints, Semidouble.]
[6, Of the VI day within the Octave of All Saints, Semidouble.]
[7, Of the VII day within the Octave of All Saints, Semidouble.]
[8, Octave of All Saints, Greater Double, Com. of the Holy Four Crowned Martyrs.]
[9, Dedication of the Archbasilica of the most Holy Saviour, Double of the II Class, Com. of St. Theodore Martyr.]
[10, St. Andrew Avellino Confessor, Double, Com. of Ss. Tryphon, Respicius, and Nympha Martyrs.]
[11, St. Martin Bishop and Confessor, Double, Com. of St. Mennas Martyr.]
[12, St. Martin I Pope and Martyr, Semidouble.]
[13, St. Didacus Confessor, Semidouble.]
[14, St. Josaphat Bishop and Martyr, Double.]
[15, St. Albert the Great Bishop, Confessor, and Doctor of the Church, Double.]
[16, St. Gertrude Virgin, Double.]
[17, St. Gregory Thaumaturgus Bishop and Confessor, Semidouble.]
[18, Dedication of the Basilicas of Ss. Peter and Paul, Greater Double]
[19, St. Elisabeth Widow, Double, Com. of St. Pontianus Pope and Martyr.]
[20, St. Felix of Valois Confessor, Double.]
[21, Presentation of the Blessed Virgin Mary, Greater Double]
[22, St. Cecilia Virgin and Martyr, Double.]
[23, St. Clement I Pope and Martyr, Double, Com. of St. Felicitas Martyr.]
[24, St. John of the Cross Confessor and Doctor of the Church, Double, Com. St. Chrysogonus Martyr.]
[25, St. Catherine Virgin and Martyr, Double.]
[26, St. Sylvester Abbot, Double, Com. of St. Peter of Alexandria Bishop and Martyr.]
[27, Feria]
[28, Feria]
[29, Vigil. Commemoration of St. Saturninus.]
[30, St. Andrew Apostle, Double of the II Class.]
[December[edit]]
[1, Feria]
[2, St. Bibiana Virgin and Martyr, Semidouble.]
[3, St. Francis Xavier Confessor, Greater Double.]
[4, St. Peter Chrysologus Bishop, Confessor, and Doctor of the Church, Double, Com. of St. Barbara Virgin and Martyr.]
[5, Com. of St. Sabbas Abbot.]
[6, St. Nicholas Bishop and Confessor, Double.]
[7, St. Ambrose Bishop, Confessor, and Doctor of the Church, Double, Com. of the Vigil.]
[8, The Immaculate Conception of the Blessed Virgin Mary, Double of the I Class with a common Octave.]
[9, Of the II day within the Octave of the Immaculate Conception, Semidouble.]
[10, Of the III day within the Octave of the Immaculate Conception, Semidouble, Com. of St. Melchiades Pope and Martyr.]
[11, St. Damasus I Pope and Confessor, Semidouble, Com. of the Octave of the Immaculate Conception.]
[12, Of the V day within the Octave of the Immaculate Conception, Semidouble.]
[13, St. Lucy Virgin and Martyr, Double, Com. of the Octave of the Immaculate Conception.]
[14, Of the VII day within the Octave of the Immaculate Conception, Semidouble.]
[15, Octave of the Immaculate Conception, Greater Double.]
[16, St. Eusebius Bishop and Martyr, Semidouble.]
[17, Feria]
[18, Feria]
[19, Feria]
[20, Vigil.]
[21, St. Thomas Apostle, Double of the II Class.]
[22, Feria]
[23, Feria]
[24, Vigil.]
[25, Nativity of our Lord Jesus Christ, Double of the I Class with a privileged Octave of the III rank.]
[26, St. Stephen Protomartyr, Double of the II class with a simple Octave, Com. of the Octave of the Nativity.]
[27, St. John Apostle and Evangelist, Double of the II class with a simple Octave, Com. of the Octave of the Nativity.]
[28, The Holy Innocents, Double of the II class with a simple Octave, Com. of the Octave of the Nativity.]
[29, St. Thomas Bishop and Martyr, Double, Com. of the Octave of the Nativity.]
[30, Of the VI day within the Octave of the Nativity, Semidouble.]
[31, St. Sylvester I Pope and Confessor, Double, Com. of the Octave of the Nativity.]