temporal = {
 '01/01/93': {'feast': 'Circumcisio Domini et Oct Nativitatis', 'rank': 'd2'},
 '01/02/93': {'feast': 'Octava S Stephani Protomartyris', 'rank': 'sp'},
 '01/03/93': {'feast': 'Octava S Joannis Ap & Ev', 'rank': 'sp'},
 '01/04/93': {'feast': 'Octava Ss Innocentium Mm', 'rank': 'sp'},
 '01/02/93': {'feast': 'SS Nominis Jesu', 'rank': 'd2'},
 '02/10/93': {'feast': 'Dominica in Septuagesima', 'rank': 'sd2'},
 '02/17/93': {'feast': 'Dominica in Sexagesima', 'rank': 'sd2'},
 '02/24/93': {'feast': 'Dominica in Quinquagesima', 'rank': 'sd2'},
 '01/06/93': {'feast': 'Epiphania Domini', 'rank': 'd1'},
 '01/07/93': {'feast': 'De die II infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/08/93': {'feast': 'De die III infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/09/93': {'feast': 'De die IV infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/10/93': {'feast': 'De die V infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/11/93': {'feast': 'De die VI infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/12/93': {'feast': 'De die VII infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/13/93': {'feast': 'Octava Epiphaniæ; Dominica I post Epiphaniam', 'rank': 'dm'},
 '01/12/93': {'feast': 'S Familiæ Jesu Mariæ et Joseph', 'rank': 'dm'},
 '01/20/93': {'feast': 'Dominica II post Epiphaniam', 'rank': 'sp'},
 '01/27/93': {'feast': 'Dominica III post Epiphaniam', 'rank': 'sp'},
 '02/03/93': {'feast': 'Dominica IV post Epiphaniam', 'rank': 'sp'},
 '02/27/93': {'feast': 'Dies Cinerum', 'rank': 'sp'},
 '02/27/93': {'feast': 'Feria V post Diem Cinerum', 'rank': 'sp'},
 '02/27/93': {'feast': 'Feria VI post Diem Cinerum', 'rank': 'sp'},
 '02/27/93': {'feast': 'Sabbato post Diem Cinerum', 'rank': 'sp'},
 '03/03/93': {'feast': 'Dominica I in Quadragesima', 'rank': 'sd1'},
 '03/04/93': {'feast': 'Feria II infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/05/93': {'feast': 'Feria III infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/06/93': {'feast': 'Feria IV Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/07/93': {'feast': 'Feria V infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/08/93': {'feast': 'Feria VI Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/09/93': {'feast': 'Sabbato Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/10/93': {'feast': 'Dominica II in Quadragesima', 'rank': 'sd1'},
 '03/11/93': {'feast': 'Feria II infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/12/93': {'feast': 'Feria III infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/13/93': {'feast': 'Feria IV infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/14/93': {'feast': 'Feria V infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/15/93': {'feast': 'Feria VI infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/16/93': {'feast': 'Sabbato infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/17/93': {'feast': 'Dominica III in Quadragesima', 'rank': 'sd1'},
 '03/18/93': {'feast': 'Feria II infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/19/93': {'feast': 'Feria III infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/20/93': {'feast': 'Feria IV infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/21/93': {'feast': 'Feria V infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/22/93': {'feast': 'Feria VI infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/23/93': {'feast': 'Sabbato infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/24/93': {'feast': 'Dominica IV in Quadragesima', 'rank': 'sd1'},
 '03/25/93': {'feast': 'Feria II infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/26/93': {'feast': 'Feria III infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/27/93': {'feast': 'Feria IV infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/28/93': {'feast': 'Feria V infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/29/93': {'feast': 'Feria VI infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/30/93': {'feast': 'Sabbato infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/31/93': {'feast': 'Dominica de Passione', 'rank': 'sd1'},
 '04/01/93': {'feast': 'Feria II infra Hebd de Passione', 'rank': 'sp'},
 '04/02/93': {'feast': 'Feria III infra Hebd de Passione', 'rank': 'sp'},
 '04/03/93': {'feast': 'Feria IV infra Hebd de Passione', 'rank': 'sp'},
 '04/04/93': {'feast': 'Feria V infra Hebd de Passione', 'rank': 'sp'},
 '04/05/93': {'feast': 'Septem Dolorum BMV', 'rank': 'dm'},
 '04/06/93': {'feast': 'Sabbato infra Hebd de Passione', 'rank': 'sp'},
 '04/07/93': {'feast': 'Dominica in Palmis', 'rank': 'sd1'},
 '04/08/93': {'feast': 'Feria II Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/09/93': {'feast': 'Feria III Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/10/93': {'feast': 'Feria IV Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/11/93': {'feast': 'Feria V in Cœna Domini', 'rank': 'd1'},
 '04/12/93': {'feast': 'Feria VI in Parasceve', 'rank': 'd1'},
 '04/13/93': {'feast': 'Sabbatum Sanctum', 'rank': 'd1'},
 '04/14/93': {'feast': 'Dominica Resurrectionis', 'rank': 'd1'},
 '04/15/93': {'feast': 'Feria II Paschatis', 'rank': 'd1'},
 '04/16/93': {'feast': 'Feria III Paschatis', 'rank': 'd1'},
 '04/17/93': {'feast': 'De die IV infra Oct Paschæ', 'rank': 'sd'},
 '04/18/93': {'feast': 'De die V infra Oct Paschæ', 'rank': 'sd'},
 '04/19/93': {'feast': 'De die VI infra Oct Paschæ', 'rank': 'sd'},
 '04/20/93': {'feast': 'Sabbatum in Albis', 'rank': 'sd'},
 '04/21/93': {'feast': 'Dominica in Albis', 'rank': 'sd'},
 '05/01/93': {'feast': 'Solemnitas S Joseph, Sponsi BMV C et Ecclesiæ Universalis Patroni', 'rank': 'd1'},
 '05/08/93': {'feast': 'Octava Solemnitas S Joseph', 'rank': 'dm'},
 '04/28/93': {'feast': 'Dominica II post Pascha', 'rank': 'sd'},
 '05/05/93': {'feast': 'Dominica III post Pascha', 'rank': 'sd'},
 '05/12/93': {'feast': 'Dominica IV post Pascha', 'rank': 'sd'},
 '05/20/93': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/21/93': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/22/93': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/22/93': {'feast': 'Vigilæ Ascensionis', 'rank': 'sp'},
 '05/23/93': {'feast': 'Ascensio DNJC', 'rank': 'd1'},
 '05/19/93': {'feast': 'Dominica V post Pascha', 'rank': 'sd'},
 '05/25/93': {'feast': 'De II die infra Oct Ascensionis', 'rank': 'sd'},
 '05/27/93': {'feast': 'De IV die infra Oct Ascensionis', 'rank': 'sd'},
 '05/28/93': {'feast': 'De V die infra Oct Ascensionis', 'rank': 'sd'},
 '05/29/93': {'feast': 'De VI die infra Oct Ascensionis', 'rank': 'sd'},
 '05/26/93': {'feast': 'Dominica infra Octavam Ascensionis', 'rank': 'sd'},
 '06/01/93': {'feast': 'Vigilia Pentecostes', 'rank': 'sd'},
 '06/02/93': {'feast': 'Dominica Pentecostes', 'rank': 'd1'},
 '05/25/93': {'feast': 'De II die infra Oct Pentecostes', 'rank': 'd1'},
 '05/26/93': {'feast': 'De III die infra Oct Pentecostes', 'rank': 'd1'},
 '05/27/93': {'feast': 'De IV die infra Oct Pentecostes', 'rank': 'd1'},
 '05/28/93': {'feast': 'De V die infra Oct Pentecostes', 'rank': 'd1'},
 '05/29/93': {'feast': 'De VI die infra Oct Pentecostes', 'rank': 'd1'},
 '05/30/93': {'feast': 'Sabbato die infra Oct Pentecostes', 'rank': 'd1'},
 '06/05/93': {'feast': 'Feria IV Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/07/93': {'feast': 'Feria VI Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/08/93': {'feast': 'Sabbato Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/09/93': {'feast': 'Dominica Sanctissimæ Trinitatis', 'rank': 'd1'},
 '06/14/93': {'feast': 'De II die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/15/93': {'feast': 'De III die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/17/93': {'feast': 'De V die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/18/93': {'feast': 'De VI die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/19/93': {'feast': 'De VII die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/13/93': {'feast': 'Sanctissimi Corporis Christi', 'rank': 'd1'},
 '06/20/93': {'feast': 'Octava SSmi Corporis Christi', 'rank': 'dm'},
 '06/16/93': {'feast': 'Dominica II post Pentecosten infra Octavam Corporis Christi', 'rank': 'sd'},
 '06/22/93': {'feast': 'De II die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/24/93': {'feast': 'De IV die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/25/93': {'feast': 'De V die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/26/93': {'feast': 'De VI die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/27/93': {'feast': 'De VII die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/21/93': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'd1'},
 '06/28/93': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'dm'},
 '06/23/93': {'feast': 'Dominica III post Pentecosten infra Octavam SSmi Cordis DNJC', 'rank': 'sd'},
 '06/30/93': {'feast': 'Dominica V post Pentecosten', 'rank': 'sd'},
 '07/07/93': {'feast': 'Dominica VI post Pentecosten', 'rank': 'sd'},
 '07/14/93': {'feast': 'Dominica VII post Pentecosten', 'rank': 'sd'},
 '07/21/93': {'feast': 'Dominica VIII post Pentecosten', 'rank': 'sd'},
 '07/28/93': {'feast': 'Dominica IX post Pentecosten', 'rank': 'sd'},
 '08/04/93': {'feast': 'Dominica X post Pentecosten', 'rank': 'sd'},
 '08/11/93': {'feast': 'Dominica XI post Pentecosten', 'rank': 'sd'},
 '08/18/93': {'feast': 'Dominica XII post Pentecosten', 'rank': 'sd'},
 '08/25/93': {'feast': 'Dominica XIII post Pentecosten', 'rank': 'sd'},
 '09/01/93': {'feast': 'Dominica XIV post Pentecosten', 'rank': 'sd'},
 '09/08/93': {'feast': 'Dominica XV post Pentecosten', 'rank': 'sd'},
 '09/15/93': {'feast': 'Dominica XVI post Pentecosten', 'rank': 'sd'},
 '09/18/93': {'feast': 'Feria IV Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/20/93': {'feast': 'Feria VI Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/21/93': {'feast': 'Sabbato Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/22/93': {'feast': 'Dominica XVII post Pentecosten', 'rank': 'sd'},
 '09/29/93': {'feast': 'Dominica XVIII post Pentecosten', 'rank': 'sd'},
 '10/06/93': {'feast': 'Dominica XIX post Pentecosten', 'rank': 'sd'},
 '10/13/93': {'feast': 'Dominica XX post Pentecosten', 'rank': 'sd'},
 '10/20/93': {'feast': 'Dominica XXI post Pentecosten', 'rank': 'sd'},
 '10/27/93': {'feast': 'Dominica XXII post Pentecosten', 'rank': 'sd'},
 '11/03/93': {'feast': 'Dominica XXIII post Pentecosten', 'rank': 'sd'},
 '11/10/93': {'feast': 'Dominica XXIV post Pentecosten', 'rank': 'sd'},
 '11/17/93': {'feast': 'Dominica XXV post Pentecosten', 'rank': 'sd'},
 '11/24/93': {'feast': 'Dominica XXVI post Pentecosten', 'rank': 'sd'},
 '12/01/93': {'feast': 'Dominica XXVII post Pentecosten', 'rank': 'sd'},
 '12/22/93': {'feast': 'Dominica IV Adventus', 'rank': 'sd2'},
 '12/15/93': {'feast': 'Dominica III Adventus', 'rank': 'sd2'},
 '12/18/93': {'feast': 'Feria IV Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/20/93': {'feast': 'Feria VI Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/21/93': {'feast': 'Sabbato Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/08/93': {'feast': 'Dominica II Adventus', 'rank': 'sd2'},
 '12/01/93': {'feast': 'Dominica I Adventus', 'rank': 'sd2'},
 '12/25/93': {'feast': 'Nativitas DNJC', 'rank': 'd1'},
 '12/29/93': {'feast': 'Dominica Infra Octavam Nativitatis', 'rank': 'sd'},
 '12/30/93': {'feast': 'De VI Die infra Octavam Nativitatis', 'rank': 'sd'},
 '12/26/93': {'feast': 'S Stephani Protomartyris', 'rank': 'd2'},
 '12/27/93': {'feast': 'S Joannis Ap & Ev', 'rank': 'd2'},
 '12/28/93': {'feast': 'Ss Innocentium Mm', 'rank': 'd2'},
 '12/29/93': {'feast': 'S Thomas EM', 'rank': 'd'},
 '12/31/93': {'feast': 'S Sylvestri I PC', 'rank': 'd'},
}
