temporal = {
 '01/03/21': {'feast': 'SS Nominis Jesu', 'rank': 'd2', 'weekday': 'Sun'},
 '01/31/21': {'feast': 'Dominica in Septuagesima', 'rank': 'sd2', 'weekday': 'Sun'},
 '02/07/21': {'feast': 'Dominica in Sexagesima', 'rank': 'sd2', 'weekday': 'Sun'},
 '02/14/21': {'feast': 'Dominica in Quinquagesima', 'rank': 'sd2', 'weekday': 'Sun'},
 '01/10/21': {'feast': 'S Familiæ Jesu Mariæ et Joseph; Dominica I post Epiphaniam', 'rank': 'dm', 'weekday': 'Sun'},
 '01/17/21': {'feast': 'Dominica II post Epiphaniam', 'rank': 'sp', 'weekday': 'Sun'},
 '01/24/21': {'feast': 'Dominica III post Epiphaniam', 'rank': 'sp', 'weekday': 'Sun'},
 '02/17/21': {'feast': 'Dies Cinerum', 'rank': 'sp', 'weekday': 'Wed'},
 '02/17/21': {'feast': 'Feria V post Diem Cinerum', 'rank': 'sp', 'weekday': 'Thu'},
 '02/17/21': {'feast': 'Feria VI post Diem Cinerum', 'rank': 'sp', 'weekday': 'Fri'},
 '02/17/21': {'feast': 'Sabbato post Diem Cinerum', 'rank': 'sp', 'weekday': 'Sat'},
 '02/21/21': {'feast': 'Dominica I in Quadragesima', 'rank': 'sd1', 'weekday': 'Sun'},
 '02/22/21': {'feast': 'Feria II infra Hebd I in Quadragesima', 'rank': 'sp', 'weekday': 'Mon'},
 '02/23/21': {'feast': 'Feria III infra Hebd I in Quadragesima', 'rank': 'sp', 'weekday': 'Tue'},
 '02/24/21': {'feast': 'Feria IV Quattuor Temporum Quadragesimæ', 'rank': 'sp', 'weekday': 'Wed'},
 '02/25/21': {'feast': 'Feria V infra Hebd I in Quadragesima', 'rank': 'sp', 'weekday': 'Thu'},
 '02/26/21': {'feast': 'Feria VI Quattuor Temporum Quadragesimæ', 'rank': 'sp', 'weekday': 'Fri'},
 '02/27/21': {'feast': 'Sabbato Quattuor Temporum Quadragesimæ', 'rank': 'sp', 'weekday': 'Sat'},
 '02/28/21': {'feast': 'Dominica II in Quadragesima', 'rank': 'sd1', 'weekday': 'Sun'},
 '03/01/21': {'feast': 'Feria II infra Hebd II in Quadragesima', 'rank': 'sp', 'weekday': 'Mon'},
 '03/02/21': {'feast': 'Feria III infra Hebd II in Quadragesima', 'rank': 'sp', 'weekday': 'Tue'},
 '03/03/21': {'feast': 'Feria IV infra Hebd II in Quadragesima', 'rank': 'sp', 'weekday': 'Wed'},
 '03/04/21': {'feast': 'Feria V infra Hebd II in Quadragesima', 'rank': 'sp', 'weekday': 'Thu'},
 '03/05/21': {'feast': 'Feria VI infra Hebd II in Quadragesima', 'rank': 'sp', 'weekday': 'Fri'},
 '03/06/21': {'feast': 'Sabbato infra Hebd II in Quadragesima', 'rank': 'sp', 'weekday': 'Sat'},
 '03/07/21': {'feast': 'Dominica III in Quadragesima', 'rank': 'sd1', 'weekday': 'Sun'},
 '03/08/21': {'feast': 'Feria II infra Hebd III in Quadragesima', 'rank': 'sp', 'weekday': 'Mon'},
 '03/09/21': {'feast': 'Feria III infra Hebd III in Quadragesima', 'rank': 'sp', 'weekday': 'Tue'},
 '03/10/21': {'feast': 'Feria IV infra Hebd III in Quadragesima', 'rank': 'sp', 'weekday': 'Wed'},
 '03/11/21': {'feast': 'Feria V infra Hebd III in Quadragesima', 'rank': 'sp', 'weekday': 'Thu'},
 '03/12/21': {'feast': 'Feria VI infra Hebd III in Quadragesima', 'rank': 'sp', 'weekday': 'Fri'},
 '03/13/21': {'feast': 'Sabbato infra Hebd III in Quadragesima', 'rank': 'sp', 'weekday': 'Sat'},
 '03/14/21': {'feast': 'Dominica IV in Quadragesima', 'rank': 'sd1', 'weekday': 'Sun'},
 '03/15/21': {'feast': 'Feria II infra Hebd IV in Quadragesima', 'rank': 'sp', 'weekday': 'Mon'},
 '03/16/21': {'feast': 'Feria III infra Hebd IV in Quadragesima', 'rank': 'sp', 'weekday': 'Tue'},
 '03/17/21': {'feast': 'Feria IV infra Hebd IV in Quadragesima', 'rank': 'sp', 'weekday': 'Wed'},
 '03/18/21': {'feast': 'Feria V infra Hebd IV in Quadragesima', 'rank': 'sp', 'weekday': 'Thu'},
 '03/19/21': {'feast': 'Feria VI infra Hebd IV in Quadragesima', 'rank': 'sp', 'weekday': 'Fri'},
 '03/20/21': {'feast': 'Sabbato infra Hebd IV in Quadragesima', 'rank': 'sp', 'weekday': 'Sat'},
 '03/21/21': {'feast': 'Dominica de Passione', 'rank': 'sd1', 'weekday': 'Sun'},
 '03/22/21': {'feast': 'Feria II infra Hebd de Passione', 'rank': 'sp', 'weekday': 'Mon'},
 '03/23/21': {'feast': 'Feria III infra Hebd de Passione', 'rank': 'sp', 'weekday': 'Tue'},
 '03/24/21': {'feast': 'Feria IV infra Hebd de Passione', 'rank': 'sp', 'weekday': 'Wed'},
 '03/25/21': {'feast': 'Feria V infra Hebd de Passione', 'rank': 'sp', 'weekday': 'Thu'},
 '03/26/21': {'feast': 'Septem Dolorum BMV', 'rank': 'dm', 'weekday': 'Fri'},
 '03/27/21': {'feast': 'Sabbato infra Hebd de Passione', 'rank': 'sp', 'weekday': 'Sat'},
 '03/28/21': {'feast': 'Dominica in Palmis', 'rank': 'sd1', 'weekday': 'Sun'},
 '03/29/21': {'feast': 'Feria II Majoris Hebd; Feria Priv', 'rank': 'sp', 'weekday': 'Mon'},
 '03/30/21': {'feast': 'Feria III Majoris Hebd; Feria Priv', 'rank': 'sp', 'weekday': 'Tue'},
 '03/31/21': {'feast': 'Feria IV Majoris Hebd; Feria Priv', 'rank': 'sp', 'weekday': 'Wed'},
 '04/01/21': {'feast': 'Feria V in Cœna Domini', 'rank': 'd1', 'weekday': 'Thu'},
 '04/02/21': {'feast': 'Feria VI in Parasceve', 'rank': 'd1', 'weekday': 'Fri'},
 '04/03/21': {'feast': 'Sabbatum Sanctum', 'rank': 'd1', 'weekday': 'Sat'},
 '04/04/21': {'feast': 'Dominica Resurrectionis', 'rank': 'd1', 'weekday': 'Sun'},
 '04/11/21': {'feast': 'Dominica in Albis', 'rank': 'sd', 'weekday': 'Sun'},
 '04/18/21': {'feast': 'Dominica II post Pascha', 'rank': 'sd', 'weekday': 'Sun'},
 '04/25/21': {'feast': 'Dominica III post Pascha', 'rank': 'sd', 'weekday': 'Sun'},
 '05/02/21': {'feast': 'Dominica IV post Pascha', 'rank': 'sd', 'weekday': 'Sun'},
 '05/09/21': {'feast': 'Dominica V post Pascha', 'rank': 'sd', 'weekday': 'Sun'},
 '05/16/21': {'feast': 'Dominica infra Octavam Ascensionis', 'rank': 'sd', 'weekday': 'Sun'},
 '05/23/21': {'feast': 'Dominica Pentecostes', 'rank': 'd1', 'weekday': 'Sun'},
 '05/26/21': {'feast': 'Feria IV Quattuor infra Temporum Pentecostes', 'rank': 'd1', 'weekday': 'Wed'},
 '05/28/21': {'feast': 'Feria VI Quattuor infra Temporum Pentecostes', 'rank': 'd1', 'weekday': 'Fri'},
 '05/29/21': {'feast': 'Sabbato Quattuor infra Temporum Pentecostes', 'rank': 'd1', 'weekday': 'Sat'},
 '05/30/21': {'feast': 'Dominica Sanctissimæ Trinitatis', 'rank': 'd1', 'weekday': 'Sun'},
 '06/03/21': {'feast': 'Sanctissimi Corporis Christi', 'rank': 'd1', 'weekday': 'Thu'},
 '06/06/21': {'feast': 'Dominica II post Pentecosten infra Octavam Corporis Christi', 'rank': 'sd', 'weekday': 'Sun'},
 '06/11/21': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'd1', 'weekday': 'Fri'},
 '06/13/21': {'feast': 'Dominica III post Pentecosten infra Octavam SSmi Cordis DNJC', 'rank': 'sd', 'weekday': 'Sun'},
 '06/20/21': {'feast': 'Dominica IV post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '06/27/21': {'feast': 'Dominica V post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '07/04/21': {'feast': 'Dominica VI post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '07/11/21': {'feast': 'Dominica VII post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '07/18/21': {'feast': 'Dominica VIII post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '07/25/21': {'feast': 'Dominica IX post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '08/01/21': {'feast': 'Dominica X post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '08/08/21': {'feast': 'Dominica XI post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '08/15/21': {'feast': 'Dominica XII post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '08/22/21': {'feast': 'Dominica XIII post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '08/29/21': {'feast': 'Dominica XIV post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '09/05/21': {'feast': 'Dominica XV post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '09/12/21': {'feast': 'Dominica XVI post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '09/15/21': {'feast': 'Feria IV Quattuor Temporum Septembris', 'rank': 'sd', 'weekday': 'Wed'},
 '09/17/21': {'feast': 'Feria VI Quattuor Temporum Septembris', 'rank': 'sd', 'weekday': 'Fri'},
 '09/18/21': {'feast': 'Sabbato Quattuor Temporum Septembris', 'rank': 'sd', 'weekday': 'Sat'},
 '09/19/21': {'feast': 'Dominica XVII post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '09/26/21': {'feast': 'Dominica XVIII post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '10/03/21': {'feast': 'Dominica XIX post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '10/10/21': {'feast': 'Dominica XX post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '10/17/21': {'feast': 'Dominica XXI post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '10/24/21': {'feast': 'Dominica XXII post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '10/31/21': {'feast': 'Dominica XXIII post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '11/07/21': {'feast': 'Dominica XXIV post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '11/14/21': {'feast': 'Dominica XXV post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '11/21/21': {'feast': 'Dominica XXVI post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '11/28/21': {'feast': 'Dominica XXVII post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '12/19/21': {'feast': 'Dominica IV Adventus', 'rank': 'sd2', 'weekday': 'Sun'},
 '12/12/21': {'feast': 'Dominica III Adventus', 'rank': 'sd2', 'weekday': 'Sun'},
 '12/15/21': {'feast': 'Feria IV Quattuor Temporum in Adventu', 'rank': 'sp', 'weekday': 'Wed'},
 '12/17/21': {'feast': 'Feria VI Quattuor Temporum in Adventu', 'rank': 'sp', 'weekday': 'Fri'},
 '12/18/21': {'feast': 'Sabbato Quattuor Temporum in Adventu', 'rank': 'sp', 'weekday': 'Sat'},
 '12/05/21': {'feast': 'Dominica II Adventus', 'rank': 'sd2', 'weekday': 'Sun'},
 '11/28/21': {'feast': 'Dominica I Adventus', 'rank': 'sd2', 'weekday': 'Sun'},
 '12/26/21': {'feast': 'Dominica Infra Octavam Nativitatis', 'rank': 'sd', 'weekday': 'Sun'},
}
