temporal = {
 '01/01/68': {'feast': 'Circumcisio Domini et Oct Nativitatis', 'rank': 'd2'},
 '01/02/68': {'feast': 'Octava S Stephani Protomartyris', 'rank': 'sp'},
 '01/03/68': {'feast': 'Octava S Joannis Ap & Ev', 'rank': 'sp'},
 '01/04/68': {'feast': 'Octava Ss Innocentium Mm', 'rank': 'sp'},
 '01/02/68': {'feast': 'SS Nominis Jesu', 'rank': 'd2'},
 '01/29/68': {'feast': 'Dominica in Septuagesima', 'rank': 'sd2'},
 '02/05/68': {'feast': 'Dominica in Sexagesima', 'rank': 'sd2'},
 '02/12/68': {'feast': 'Dominica in Quinquagesima', 'rank': 'sd2'},
 '01/07/68': {'feast': 'De die II infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/09/68': {'feast': 'De die IV infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/10/68': {'feast': 'De die V infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/11/68': {'feast': 'De die VI infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/12/68': {'feast': 'De die VII infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/08/68': {'feast': 'S Familiæ Jesu Mariæ et Joseph; Dominica I post Epiphaniam', 'rank': 'dm'},
 '01/15/68': {'feast': 'Dominica II post Epiphaniam', 'rank': 'sp'},
 '01/22/68': {'feast': 'Dominica III post Epiphaniam', 'rank': 'sp'},
 '02/15/68': {'feast': 'Dies Cinerum', 'rank': 'sp'},
 '02/15/68': {'feast': 'Feria V post Diem Cinerum', 'rank': 'sp'},
 '02/15/68': {'feast': 'Feria VI post Diem Cinerum', 'rank': 'sp'},
 '02/15/68': {'feast': 'Sabbato post Diem Cinerum', 'rank': 'sp'},
 '02/19/68': {'feast': 'Dominica I in Quadragesima', 'rank': 'sd1'},
 '02/20/68': {'feast': 'Feria II infra Hebd I in Quadragesima', 'rank': 'sp'},
 '02/21/68': {'feast': 'Feria III infra Hebd I in Quadragesima', 'rank': 'sp'},
 '02/22/68': {'feast': 'Feria IV Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '02/23/68': {'feast': 'Feria V infra Hebd I in Quadragesima', 'rank': 'sp'},
 '02/24/68': {'feast': 'Feria VI Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '02/25/68': {'feast': 'Sabbato Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '02/26/68': {'feast': 'Dominica II in Quadragesima', 'rank': 'sd1'},
 '02/27/68': {'feast': 'Feria II infra Hebd II in Quadragesima', 'rank': 'sp'},
 '02/28/68': {'feast': 'Feria III infra Hebd II in Quadragesima', 'rank': 'sp'},
 '02/29/68': {'feast': 'Feria IV infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/01/68': {'feast': 'Feria V infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/02/68': {'feast': 'Feria VI infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/03/68': {'feast': 'Sabbato infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/04/68': {'feast': 'Dominica III in Quadragesima', 'rank': 'sd1'},
 '03/05/68': {'feast': 'Feria II infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/06/68': {'feast': 'Feria III infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/07/68': {'feast': 'Feria IV infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/08/68': {'feast': 'Feria V infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/09/68': {'feast': 'Feria VI infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/10/68': {'feast': 'Sabbato infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/11/68': {'feast': 'Dominica IV in Quadragesima', 'rank': 'sd1'},
 '03/12/68': {'feast': 'Feria II infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/13/68': {'feast': 'Feria III infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/14/68': {'feast': 'Feria IV infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/15/68': {'feast': 'Feria V infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/16/68': {'feast': 'Feria VI infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/17/68': {'feast': 'Sabbato infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/18/68': {'feast': 'Dominica de Passione', 'rank': 'sd1'},
 '03/19/68': {'feast': 'Feria II infra Hebd de Passione', 'rank': 'sp'},
 '03/20/68': {'feast': 'Feria III infra Hebd de Passione', 'rank': 'sp'},
 '03/21/68': {'feast': 'Feria IV infra Hebd de Passione', 'rank': 'sp'},
 '03/22/68': {'feast': 'Feria V infra Hebd de Passione', 'rank': 'sp'},
 '03/23/68': {'feast': 'Septem Dolorum BMV', 'rank': 'dm'},
 '03/24/68': {'feast': 'Sabbato infra Hebd de Passione', 'rank': 'sp'},
 '03/25/68': {'feast': 'Dominica in Palmis', 'rank': 'sd1'},
 '03/26/68': {'feast': 'Feria II Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '03/27/68': {'feast': 'Feria III Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '03/28/68': {'feast': 'Feria IV Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '03/29/68': {'feast': 'Feria V in Cœna Domini', 'rank': 'd1'},
 '03/30/68': {'feast': 'Feria VI in Parasceve', 'rank': 'd1'},
 '03/31/68': {'feast': 'Sabbatum Sanctum', 'rank': 'd1'},
 '04/01/68': {'feast': 'Dominica Resurrectionis', 'rank': 'd1'},
 '04/02/68': {'feast': 'Feria II Paschatis', 'rank': 'd1'},
 '04/03/68': {'feast': 'Feria III Paschatis', 'rank': 'd1'},
 '04/04/68': {'feast': 'De die IV infra Oct Paschæ', 'rank': 'sd'},
 '04/05/68': {'feast': 'De die V infra Oct Paschæ', 'rank': 'sd'},
 '04/06/68': {'feast': 'De die VI infra Oct Paschæ', 'rank': 'sd'},
 '04/07/68': {'feast': 'Sabbatum in Albis', 'rank': 'sd'},
 '04/08/68': {'feast': 'Dominica in Albis', 'rank': 'sd'},
 '04/18/68': {'feast': 'Solemnitas S Joseph, Sponsi BMV C et Ecclesiæ Universalis Patroni', 'rank': 'd1'},
 '04/25/68': {'feast': 'Octava Solemnitas S Joseph', 'rank': 'dm'},
 '04/15/68': {'feast': 'Dominica II post Pascha', 'rank': 'sd'},
 '04/22/68': {'feast': 'Dominica III post Pascha', 'rank': 'sd'},
 '04/29/68': {'feast': 'Dominica IV post Pascha', 'rank': 'sd'},
 '05/07/68': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/08/68': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/09/68': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/09/68': {'feast': 'Vigilæ Ascensionis', 'rank': 'sp'},
 '05/10/68': {'feast': 'Ascensio DNJC', 'rank': 'd1'},
 '05/06/68': {'feast': 'Dominica V post Pascha', 'rank': 'sd'},
 '05/12/68': {'feast': 'De II die infra Oct Ascensionis', 'rank': 'sd'},
 '05/14/68': {'feast': 'De IV die infra Oct Ascensionis', 'rank': 'sd'},
 '05/15/68': {'feast': 'De V die infra Oct Ascensionis', 'rank': 'sd'},
 '05/16/68': {'feast': 'De VI die infra Oct Ascensionis', 'rank': 'sd'},
 '05/13/68': {'feast': 'Dominica infra Octavam Ascensionis', 'rank': 'sd'},
 '05/19/68': {'feast': 'Vigilia Pentecostes', 'rank': 'sd'},
 '05/20/68': {'feast': 'Dominica Pentecostes', 'rank': 'd1'},
 '05/12/68': {'feast': 'De II die infra Oct Pentecostes', 'rank': 'd1'},
 '05/13/68': {'feast': 'De III die infra Oct Pentecostes', 'rank': 'd1'},
 '05/14/68': {'feast': 'De IV die infra Oct Pentecostes', 'rank': 'd1'},
 '05/15/68': {'feast': 'De V die infra Oct Pentecostes', 'rank': 'd1'},
 '05/16/68': {'feast': 'De VI die infra Oct Pentecostes', 'rank': 'd1'},
 '05/17/68': {'feast': 'Sabbato die infra Oct Pentecostes', 'rank': 'd1'},
 '05/23/68': {'feast': 'Feria IV Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '05/25/68': {'feast': 'Feria VI Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '05/26/68': {'feast': 'Sabbato Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '05/27/68': {'feast': 'Dominica Sanctissimæ Trinitatis', 'rank': 'd1'},
 '06/01/68': {'feast': 'De II die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/02/68': {'feast': 'De III die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/04/68': {'feast': 'De V die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/05/68': {'feast': 'De VI die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/06/68': {'feast': 'De VII die infra Oct Corporis Christi', 'rank': 'sd'},
 '05/31/68': {'feast': 'Sanctissimi Corporis Christi', 'rank': 'd1'},
 '06/07/68': {'feast': 'Octava SSmi Corporis Christi', 'rank': 'dm'},
 '06/03/68': {'feast': 'Dominica II post Pentecosten infra Octavam Corporis Christi', 'rank': 'sd'},
 '06/09/68': {'feast': 'De II die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/11/68': {'feast': 'De IV die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/12/68': {'feast': 'De V die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/13/68': {'feast': 'De VI die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/14/68': {'feast': 'De VII die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/08/68': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'd1'},
 '06/15/68': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'dm'},
 '06/10/68': {'feast': 'Dominica III post Pentecosten infra Octavam SSmi Cordis DNJC', 'rank': 'sd'},
 '06/17/68': {'feast': 'Dominica V post Pentecosten', 'rank': 'sd'},
 '06/24/68': {'feast': 'Dominica VI post Pentecosten', 'rank': 'sd'},
 '07/01/68': {'feast': 'Dominica VII post Pentecosten', 'rank': 'sd'},
 '07/08/68': {'feast': 'Dominica VIII post Pentecosten', 'rank': 'sd'},
 '07/15/68': {'feast': 'Dominica IX post Pentecosten', 'rank': 'sd'},
 '07/22/68': {'feast': 'Dominica X post Pentecosten', 'rank': 'sd'},
 '07/29/68': {'feast': 'Dominica XI post Pentecosten', 'rank': 'sd'},
 '08/05/68': {'feast': 'Dominica XII post Pentecosten', 'rank': 'sd'},
 '08/12/68': {'feast': 'Dominica XIII post Pentecosten', 'rank': 'sd'},
 '08/19/68': {'feast': 'Dominica XIV post Pentecosten', 'rank': 'sd'},
 '08/26/68': {'feast': 'Dominica XV post Pentecosten', 'rank': 'sd'},
 '09/02/68': {'feast': 'Dominica XVI post Pentecosten', 'rank': 'sd'},
 '09/09/68': {'feast': 'Dominica XVII post Pentecosten', 'rank': 'sd'},
 '09/16/68': {'feast': 'Dominica XVIII post Pentecosten', 'rank': 'sd'},
 '09/19/68': {'feast': 'Feria IV Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/21/68': {'feast': 'Feria VI Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/22/68': {'feast': 'Sabbato Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/23/68': {'feast': 'Dominica XIX post Pentecosten', 'rank': 'sd'},
 '09/30/68': {'feast': 'Dominica XX post Pentecosten', 'rank': 'sd'},
 '10/07/68': {'feast': 'Dominica XXI post Pentecosten', 'rank': 'sd'},
 '10/14/68': {'feast': 'Dominica XXII post Pentecosten', 'rank': 'sd'},
 '10/21/68': {'feast': 'Dominica XXIII post Pentecosten', 'rank': 'sd'},
 '10/28/68': {'feast': 'Dominica XXIV post Pentecosten', 'rank': 'sd'},
 '11/04/68': {'feast': 'Dominica XXV post Pentecosten', 'rank': 'sd'},
 '11/11/68': {'feast': 'Dominica XXVI post Pentecosten', 'rank': 'sd'},
 '11/18/68': {'feast': 'Dominica XXVII post Pentecosten', 'rank': 'sd'},
 '12/23/68': {'feast': 'Dominica IV Adventus', 'rank': 'sd2'},
 '12/16/68': {'feast': 'Dominica III Adventus', 'rank': 'sd2'},
 '12/19/68': {'feast': 'Feria IV Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/21/68': {'feast': 'Feria VI Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/22/68': {'feast': 'Sabbato Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/09/68': {'feast': 'Dominica II Adventus', 'rank': 'sd2'},
 '12/02/68': {'feast': 'Dominica I Adventus', 'rank': 'sd2'},
 '12/25/68': {'feast': 'Nativitas DNJC', 'rank': 'd1'},
 '12/30/68': {'feast': 'Dominica Infra Octavam Nativitatis', 'rank': 'sd'},
 '12/30/68': {'feast': 'De VI Die infra Octavam Nativitatis', 'rank': 'sd'},
 '12/26/68': {'feast': 'S Stephani Protomartyris', 'rank': 'd2'},
 '12/27/68': {'feast': 'S Joannis Ap & Ev', 'rank': 'd2'},
 '12/28/68': {'feast': 'Ss Innocentium Mm', 'rank': 'd2'},
 '12/29/68': {'feast': 'S Thomas EM', 'rank': 'd'},
 '12/31/68': {'feast': 'S Sylvestri I PC', 'rank': 'd'},
}
