temporal = {
 '01/01/83': {'feast': 'Circumcisio Domini et Oct Nativitatis', 'rank': 'd2'},
 '01/02/83': {'feast': 'Octava S Stephani Protomartyris', 'rank': 'sp'},
 '01/03/83': {'feast': 'Octava S Joannis Ap & Ev', 'rank': 'sp'},
 '01/04/83': {'feast': 'Octava Ss Innocentium Mm', 'rank': 'sp'},
 '01/03/83': {'feast': 'SS Nominis Jesu', 'rank': 'd2'},
 '02/14/83': {'feast': 'Dominica in Septuagesima', 'rank': 'sd2'},
 '02/21/83': {'feast': 'Dominica in Sexagesima', 'rank': 'sd2'},
 '02/28/83': {'feast': 'Dominica in Quinquagesima', 'rank': 'sd2'},
 '01/07/83': {'feast': 'De die II infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/08/83': {'feast': 'De die III infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/09/83': {'feast': 'De die IV infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/11/83': {'feast': 'De die VI infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/12/83': {'feast': 'De die VII infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/10/83': {'feast': 'S Familiæ Jesu Mariæ et Joseph; Dominica I post Epiphaniam', 'rank': 'dm'},
 '01/17/83': {'feast': 'Dominica II post Epiphaniam', 'rank': 'sp'},
 '01/24/83': {'feast': 'Dominica III post Epiphaniam', 'rank': 'sp'},
 '01/31/83': {'feast': 'Dominica IV post Epiphaniam', 'rank': 'sp'},
 '02/07/83': {'feast': 'Dominica V post Epiphaniam', 'rank': 'sp'},
 '03/03/83': {'feast': 'Dies Cinerum', 'rank': 'sp'},
 '03/03/83': {'feast': 'Feria V post Diem Cinerum', 'rank': 'sp'},
 '03/03/83': {'feast': 'Feria VI post Diem Cinerum', 'rank': 'sp'},
 '03/03/83': {'feast': 'Sabbato post Diem Cinerum', 'rank': 'sp'},
 '03/07/83': {'feast': 'Dominica I in Quadragesima', 'rank': 'sd1'},
 '03/08/83': {'feast': 'Feria II infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/09/83': {'feast': 'Feria III infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/10/83': {'feast': 'Feria IV Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/11/83': {'feast': 'Feria V infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/12/83': {'feast': 'Feria VI Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/13/83': {'feast': 'Sabbato Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/14/83': {'feast': 'Dominica II in Quadragesima', 'rank': 'sd1'},
 '03/15/83': {'feast': 'Feria II infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/16/83': {'feast': 'Feria III infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/17/83': {'feast': 'Feria IV infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/18/83': {'feast': 'Feria V infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/19/83': {'feast': 'Feria VI infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/20/83': {'feast': 'Sabbato infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/21/83': {'feast': 'Dominica III in Quadragesima', 'rank': 'sd1'},
 '03/22/83': {'feast': 'Feria II infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/23/83': {'feast': 'Feria III infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/24/83': {'feast': 'Feria IV infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/25/83': {'feast': 'Feria V infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/26/83': {'feast': 'Feria VI infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/27/83': {'feast': 'Sabbato infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/28/83': {'feast': 'Dominica IV in Quadragesima', 'rank': 'sd1'},
 '03/29/83': {'feast': 'Feria II infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/30/83': {'feast': 'Feria III infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/31/83': {'feast': 'Feria IV infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/01/83': {'feast': 'Feria V infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/02/83': {'feast': 'Feria VI infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/03/83': {'feast': 'Sabbato infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/04/83': {'feast': 'Dominica de Passione', 'rank': 'sd1'},
 '04/05/83': {'feast': 'Feria II infra Hebd de Passione', 'rank': 'sp'},
 '04/06/83': {'feast': 'Feria III infra Hebd de Passione', 'rank': 'sp'},
 '04/07/83': {'feast': 'Feria IV infra Hebd de Passione', 'rank': 'sp'},
 '04/08/83': {'feast': 'Feria V infra Hebd de Passione', 'rank': 'sp'},
 '04/09/83': {'feast': 'Septem Dolorum BMV', 'rank': 'dm'},
 '04/10/83': {'feast': 'Sabbato infra Hebd de Passione', 'rank': 'sp'},
 '04/11/83': {'feast': 'Dominica in Palmis', 'rank': 'sd1'},
 '04/12/83': {'feast': 'Feria II Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/13/83': {'feast': 'Feria III Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/14/83': {'feast': 'Feria IV Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/15/83': {'feast': 'Feria V in Cœna Domini', 'rank': 'd1'},
 '04/16/83': {'feast': 'Feria VI in Parasceve', 'rank': 'd1'},
 '04/17/83': {'feast': 'Sabbatum Sanctum', 'rank': 'd1'},
 '04/18/83': {'feast': 'Dominica Resurrectionis', 'rank': 'd1'},
 '04/19/83': {'feast': 'Feria II Paschatis', 'rank': 'd1'},
 '04/20/83': {'feast': 'Feria III Paschatis', 'rank': 'd1'},
 '04/21/83': {'feast': 'De die IV infra Oct Paschæ', 'rank': 'sd'},
 '04/22/83': {'feast': 'De die V infra Oct Paschæ', 'rank': 'sd'},
 '04/23/83': {'feast': 'De die VI infra Oct Paschæ', 'rank': 'sd'},
 '04/24/83': {'feast': 'Sabbatum in Albis', 'rank': 'sd'},
 '04/25/83': {'feast': 'Dominica in Albis', 'rank': 'sd'},
 '05/05/83': {'feast': 'Solemnitas S Joseph, Sponsi BMV C et Ecclesiæ Universalis Patroni', 'rank': 'd1'},
 '05/12/83': {'feast': 'Octava Solemnitas S Joseph', 'rank': 'dm'},
 '05/02/83': {'feast': 'Dominica II post Pascha', 'rank': 'sd'},
 '05/09/83': {'feast': 'Dominica III post Pascha', 'rank': 'sd'},
 '05/16/83': {'feast': 'Dominica IV post Pascha', 'rank': 'sd'},
 '05/24/83': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/25/83': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/26/83': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/26/83': {'feast': 'Vigilæ Ascensionis', 'rank': 'sp'},
 '05/27/83': {'feast': 'Ascensio DNJC', 'rank': 'd1'},
 '05/23/83': {'feast': 'Dominica V post Pascha', 'rank': 'sd'},
 '05/29/83': {'feast': 'De II die infra Oct Ascensionis', 'rank': 'sd'},
 '05/31/83': {'feast': 'De IV die infra Oct Ascensionis', 'rank': 'sd'},
 '06/01/83': {'feast': 'De V die infra Oct Ascensionis', 'rank': 'sd'},
 '06/02/83': {'feast': 'De VI die infra Oct Ascensionis', 'rank': 'sd'},
 '05/30/83': {'feast': 'Dominica infra Octavam Ascensionis', 'rank': 'sd'},
 '06/05/83': {'feast': 'Vigilia Pentecostes', 'rank': 'sd'},
 '06/06/83': {'feast': 'Dominica Pentecostes', 'rank': 'd1'},
 '05/29/83': {'feast': 'De II die infra Oct Pentecostes', 'rank': 'd1'},
 '05/30/83': {'feast': 'De III die infra Oct Pentecostes', 'rank': 'd1'},
 '05/31/83': {'feast': 'De IV die infra Oct Pentecostes', 'rank': 'd1'},
 '06/01/83': {'feast': 'De V die infra Oct Pentecostes', 'rank': 'd1'},
 '06/02/83': {'feast': 'De VI die infra Oct Pentecostes', 'rank': 'd1'},
 '06/03/83': {'feast': 'Sabbato die infra Oct Pentecostes', 'rank': 'd1'},
 '06/09/83': {'feast': 'Feria IV Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/11/83': {'feast': 'Feria VI Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/12/83': {'feast': 'Sabbato Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/13/83': {'feast': 'Dominica Sanctissimæ Trinitatis', 'rank': 'd1'},
 '06/18/83': {'feast': 'De II die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/19/83': {'feast': 'De III die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/21/83': {'feast': 'De V die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/22/83': {'feast': 'De VI die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/23/83': {'feast': 'De VII die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/17/83': {'feast': 'Sanctissimi Corporis Christi', 'rank': 'd1'},
 '06/24/83': {'feast': 'Octava SSmi Corporis Christi', 'rank': 'dm'},
 '06/20/83': {'feast': 'Dominica II post Pentecosten infra Octavam Corporis Christi', 'rank': 'sd'},
 '06/26/83': {'feast': 'De II die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/28/83': {'feast': 'De IV die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/29/83': {'feast': 'De V die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/30/83': {'feast': 'De VI die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '07/01/83': {'feast': 'De VII die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/25/83': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'd1'},
 '07/02/83': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'dm'},
 '06/27/83': {'feast': 'Dominica III post Pentecosten infra Octavam SSmi Cordis DNJC', 'rank': 'sd'},
 '07/04/83': {'feast': 'Dominica V post Pentecosten', 'rank': 'sd'},
 '07/11/83': {'feast': 'Dominica VI post Pentecosten', 'rank': 'sd'},
 '07/18/83': {'feast': 'Dominica VII post Pentecosten', 'rank': 'sd'},
 '07/25/83': {'feast': 'Dominica VIII post Pentecosten', 'rank': 'sd'},
 '08/01/83': {'feast': 'Dominica IX post Pentecosten', 'rank': 'sd'},
 '08/08/83': {'feast': 'Dominica X post Pentecosten', 'rank': 'sd'},
 '08/15/83': {'feast': 'Dominica XI post Pentecosten', 'rank': 'sd'},
 '08/22/83': {'feast': 'Dominica XII post Pentecosten', 'rank': 'sd'},
 '08/29/83': {'feast': 'Dominica XIII post Pentecosten', 'rank': 'sd'},
 '09/05/83': {'feast': 'Dominica XIV post Pentecosten', 'rank': 'sd'},
 '09/12/83': {'feast': 'Dominica XV post Pentecosten', 'rank': 'sd'},
 '09/15/83': {'feast': 'Feria IV Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/17/83': {'feast': 'Feria VI Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/18/83': {'feast': 'Sabbato Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/19/83': {'feast': 'Dominica XVI post Pentecosten', 'rank': 'sd'},
 '09/26/83': {'feast': 'Dominica XVII post Pentecosten', 'rank': 'sd'},
 '10/03/83': {'feast': 'Dominica XVIII post Pentecosten', 'rank': 'sd'},
 '10/10/83': {'feast': 'Dominica XIX post Pentecosten', 'rank': 'sd'},
 '10/17/83': {'feast': 'Dominica XX post Pentecosten', 'rank': 'sd'},
 '10/24/83': {'feast': 'Dominica XXI post Pentecosten', 'rank': 'sd'},
 '10/31/83': {'feast': 'Dominica XXII post Pentecosten', 'rank': 'sd'},
 '11/07/83': {'feast': 'Dominica XXIII post Pentecosten', 'rank': 'sd'},
 '11/14/83': {'feast': 'Dominica XXIV post Pentecosten', 'rank': 'sd'},
 '11/21/83': {'feast': 'Dominica XXV post Pentecosten', 'rank': 'sd'},
 '11/28/83': {'feast': 'Dominica XXVI post Pentecosten', 'rank': 'sd'},
 '12/19/83': {'feast': 'Dominica IV Adventus', 'rank': 'sd2'},
 '12/12/83': {'feast': 'Dominica III Adventus', 'rank': 'sd2'},
 '12/15/83': {'feast': 'Feria IV Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/17/83': {'feast': 'Feria VI Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/18/83': {'feast': 'Sabbato Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/05/83': {'feast': 'Dominica II Adventus', 'rank': 'sd2'},
 '11/28/83': {'feast': 'Dominica I Adventus', 'rank': 'sd2'},
 '12/25/83': {'feast': 'Nativitas DNJC', 'rank': 'd1'},
 '12/30/83': {'feast': 'Dominica Infra Octavam Nativitatis reposit', 'rank': 'sd'},
 '12/26/83': {'feast': 'S Stephani Protomartyris', 'rank': 'd2'},
 '12/27/83': {'feast': 'S Joannis Ap & Ev', 'rank': 'd2'},
 '12/28/83': {'feast': 'Ss Innocentium Mm', 'rank': 'd2'},
 '12/29/83': {'feast': 'S Thomas EM', 'rank': 'd'},
 '12/31/83': {'feast': 'S Sylvestri I PC', 'rank': 'd'},
}
