temporal = {
 '01/01/25': {'feast': 'Circumcisio Domini et Oct Nativitatis', 'rank': 'd2'},
 '01/02/25': {'feast': 'Octava S Stephani Protomartyris', 'rank': 'sp'},
 '01/03/25': {'feast': 'Octava S Joannis Ap & Ev', 'rank': 'sp'},
 '01/04/25': {'feast': 'Octava Ss Innocentium Mm', 'rank': 'sp'},
 '01/02/25': {'feast': 'SS Nominis Jesu', 'rank': 'd2'},
 '02/18/25': {'feast': 'Dominica in Septuagesima', 'rank': 'sd2'},
 '02/25/25': {'feast': 'Dominica in Sexagesima', 'rank': 'sd2'},
 '03/04/25': {'feast': 'Dominica in Quinquagesima', 'rank': 'sd2'},
 '01/08/25': {'feast': 'De die III infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/09/25': {'feast': 'De die IV infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/10/25': {'feast': 'De die V infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/11/25': {'feast': 'De die VI infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/12/25': {'feast': 'De die VII infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/07/25': {'feast': 'S Familiæ Jesu Mariæ et Joseph; Dominica I post Epiphaniam', 'rank': 'dm'},
 '01/14/25': {'feast': 'Dominica II post Epiphaniam', 'rank': 'sp'},
 '01/21/25': {'feast': 'Dominica III post Epiphaniam', 'rank': 'sp'},
 '01/28/25': {'feast': 'Dominica IV post Epiphaniam', 'rank': 'sp'},
 '02/04/25': {'feast': 'Dominica V post Epiphaniam', 'rank': 'sp'},
 '02/11/25': {'feast': 'Dominica VI post Epiphaniam', 'rank': 'sp'},
 '03/07/25': {'feast': 'Dies Cinerum', 'rank': 'sp'},
 '03/07/25': {'feast': 'Feria V post Diem Cinerum', 'rank': 'sp'},
 '03/07/25': {'feast': 'Feria VI post Diem Cinerum', 'rank': 'sp'},
 '03/07/25': {'feast': 'Sabbato post Diem Cinerum', 'rank': 'sp'},
 '03/11/25': {'feast': 'Dominica I in Quadragesima', 'rank': 'sd1'},
 '03/12/25': {'feast': 'Feria II infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/13/25': {'feast': 'Feria III infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/14/25': {'feast': 'Feria IV Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/15/25': {'feast': 'Feria V infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/16/25': {'feast': 'Feria VI Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/17/25': {'feast': 'Sabbato Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/18/25': {'feast': 'Dominica II in Quadragesima', 'rank': 'sd1'},
 '03/19/25': {'feast': 'Feria II infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/20/25': {'feast': 'Feria III infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/21/25': {'feast': 'Feria IV infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/22/25': {'feast': 'Feria V infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/23/25': {'feast': 'Feria VI infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/24/25': {'feast': 'Sabbato infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/25/25': {'feast': 'Dominica III in Quadragesima', 'rank': 'sd1'},
 '03/26/25': {'feast': 'Feria II infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/27/25': {'feast': 'Feria III infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/28/25': {'feast': 'Feria IV infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/29/25': {'feast': 'Feria V infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/30/25': {'feast': 'Feria VI infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/31/25': {'feast': 'Sabbato infra Hebd III in Quadragesima', 'rank': 'sp'},
 '04/01/25': {'feast': 'Dominica IV in Quadragesima', 'rank': 'sd1'},
 '04/02/25': {'feast': 'Feria II infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/03/25': {'feast': 'Feria III infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/04/25': {'feast': 'Feria IV infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/05/25': {'feast': 'Feria V infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/06/25': {'feast': 'Feria VI infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/07/25': {'feast': 'Sabbato infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/08/25': {'feast': 'Dominica de Passione', 'rank': 'sd1'},
 '04/09/25': {'feast': 'Feria II infra Hebd de Passione', 'rank': 'sp'},
 '04/10/25': {'feast': 'Feria III infra Hebd de Passione', 'rank': 'sp'},
 '04/11/25': {'feast': 'Feria IV infra Hebd de Passione', 'rank': 'sp'},
 '04/12/25': {'feast': 'Feria V infra Hebd de Passione', 'rank': 'sp'},
 '04/13/25': {'feast': 'Septem Dolorum BMV', 'rank': 'dm'},
 '04/14/25': {'feast': 'Sabbato infra Hebd de Passione', 'rank': 'sp'},
 '04/15/25': {'feast': 'Dominica in Palmis', 'rank': 'sd1'},
 '04/16/25': {'feast': 'Feria II Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/17/25': {'feast': 'Feria III Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/18/25': {'feast': 'Feria IV Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/19/25': {'feast': 'Feria V in Cœna Domini', 'rank': 'd1'},
 '04/20/25': {'feast': 'Feria VI in Parasceve', 'rank': 'd1'},
 '04/21/25': {'feast': 'Sabbatum Sanctum', 'rank': 'd1'},
 '04/22/25': {'feast': 'Dominica Resurrectionis', 'rank': 'd1'},
 '04/23/25': {'feast': 'Feria II Paschatis', 'rank': 'd1'},
 '04/24/25': {'feast': 'Feria III Paschatis', 'rank': 'd1'},
 '04/25/25': {'feast': 'De die IV infra Oct Paschæ', 'rank': 'sd'},
 '04/26/25': {'feast': 'De die V infra Oct Paschæ', 'rank': 'sd'},
 '04/27/25': {'feast': 'De die VI infra Oct Paschæ', 'rank': 'sd'},
 '04/28/25': {'feast': 'Sabbatum in Albis', 'rank': 'sd'},
 '04/29/25': {'feast': 'Dominica in Albis', 'rank': 'sd'},
 '05/09/25': {'feast': 'Solemnitas S Joseph, Sponsi BMV C et Ecclesiæ Universalis Patroni', 'rank': 'd1'},
 '05/16/25': {'feast': 'Octava Solemnitas S Joseph', 'rank': 'dm'},
 '05/06/25': {'feast': 'Dominica II post Pascha', 'rank': 'sd'},
 '05/13/25': {'feast': 'Dominica III post Pascha', 'rank': 'sd'},
 '05/20/25': {'feast': 'Dominica IV post Pascha', 'rank': 'sd'},
 '05/28/25': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/29/25': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/30/25': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/30/25': {'feast': 'Vigilæ Ascensionis', 'rank': 'sp'},
 '05/31/25': {'feast': 'Ascensio DNJC', 'rank': 'd1'},
 '05/27/25': {'feast': 'Dominica V post Pascha', 'rank': 'sd'},
 '06/02/25': {'feast': 'De II die infra Oct Ascensionis', 'rank': 'sd'},
 '06/04/25': {'feast': 'De IV die infra Oct Ascensionis', 'rank': 'sd'},
 '06/05/25': {'feast': 'De V die infra Oct Ascensionis', 'rank': 'sd'},
 '06/06/25': {'feast': 'De VI die infra Oct Ascensionis', 'rank': 'sd'},
 '06/03/25': {'feast': 'Dominica infra Octavam Ascensionis', 'rank': 'sd'},
 '06/09/25': {'feast': 'Vigilia Pentecostes', 'rank': 'sd'},
 '06/10/25': {'feast': 'Dominica Pentecostes', 'rank': 'd1'},
 '06/02/25': {'feast': 'De II die infra Oct Pentecostes', 'rank': 'd1'},
 '06/03/25': {'feast': 'De III die infra Oct Pentecostes', 'rank': 'd1'},
 '06/04/25': {'feast': 'De IV die infra Oct Pentecostes', 'rank': 'd1'},
 '06/05/25': {'feast': 'De V die infra Oct Pentecostes', 'rank': 'd1'},
 '06/06/25': {'feast': 'De VI die infra Oct Pentecostes', 'rank': 'd1'},
 '06/07/25': {'feast': 'Sabbato die infra Oct Pentecostes', 'rank': 'd1'},
 '06/13/25': {'feast': 'Feria IV Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/15/25': {'feast': 'Feria VI Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/16/25': {'feast': 'Sabbato Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/17/25': {'feast': 'Dominica Sanctissimæ Trinitatis', 'rank': 'd1'},
 '06/22/25': {'feast': 'De II die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/23/25': {'feast': 'De III die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/25/25': {'feast': 'De V die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/26/25': {'feast': 'De VI die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/27/25': {'feast': 'De VII die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/21/25': {'feast': 'Sanctissimi Corporis Christi', 'rank': 'd1'},
 '06/28/25': {'feast': 'Octava SSmi Corporis Christi', 'rank': 'dm'},
 '06/24/25': {'feast': 'Dominica II post Pentecosten infra Octavam Corporis Christi', 'rank': 'sd'},
 '06/30/25': {'feast': 'De II die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '07/02/25': {'feast': 'De IV die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '07/03/25': {'feast': 'De V die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '07/04/25': {'feast': 'De VI die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '07/05/25': {'feast': 'De VII die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/29/25': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'd1'},
 '07/06/25': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'dm'},
 '07/01/25': {'feast': 'Dominica III post Pentecosten infra Octavam SSmi Cordis DNJC', 'rank': 'sd'},
 '07/08/25': {'feast': 'Dominica V post Pentecosten', 'rank': 'sd'},
 '07/15/25': {'feast': 'Dominica VI post Pentecosten', 'rank': 'sd'},
 '07/22/25': {'feast': 'Dominica VII post Pentecosten', 'rank': 'sd'},
 '07/29/25': {'feast': 'Dominica VIII post Pentecosten', 'rank': 'sd'},
 '08/05/25': {'feast': 'Dominica IX post Pentecosten', 'rank': 'sd'},
 '08/12/25': {'feast': 'Dominica X post Pentecosten', 'rank': 'sd'},
 '08/19/25': {'feast': 'Dominica XI post Pentecosten', 'rank': 'sd'},
 '08/26/25': {'feast': 'Dominica XII post Pentecosten', 'rank': 'sd'},
 '09/02/25': {'feast': 'Dominica XIII post Pentecosten', 'rank': 'sd'},
 '09/09/25': {'feast': 'Dominica XIV post Pentecosten', 'rank': 'sd'},
 '09/16/25': {'feast': 'Dominica XV post Pentecosten', 'rank': 'sd'},
 '09/19/25': {'feast': 'Feria IV Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/21/25': {'feast': 'Feria VI Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/22/25': {'feast': 'Sabbato Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/23/25': {'feast': 'Dominica XVI post Pentecosten', 'rank': 'sd'},
 '09/30/25': {'feast': 'Dominica XVII post Pentecosten', 'rank': 'sd'},
 '10/07/25': {'feast': 'Dominica XVIII post Pentecosten', 'rank': 'sd'},
 '10/14/25': {'feast': 'Dominica XIX post Pentecosten', 'rank': 'sd'},
 '10/21/25': {'feast': 'Dominica XX post Pentecosten', 'rank': 'sd'},
 '10/28/25': {'feast': 'Dominica XXI post Pentecosten', 'rank': 'sd'},
 '11/04/25': {'feast': 'Dominica XXII post Pentecosten', 'rank': 'sd'},
 '11/11/25': {'feast': 'Dominica XXIII post Pentecosten', 'rank': 'sd'},
 '11/18/25': {'feast': 'Dominica XXIV post Pentecosten', 'rank': 'sd'},
 '11/25/25': {'feast': 'Dominica XXV post Pentecosten', 'rank': 'sd'},
 '12/02/25': {'feast': 'Dominica XXVI post Pentecosten', 'rank': 'sd'},
 '12/23/25': {'feast': 'Dominica IV Adventus', 'rank': 'sd2'},
 '12/16/25': {'feast': 'Dominica III Adventus', 'rank': 'sd2'},
 '12/19/25': {'feast': 'Feria IV Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/21/25': {'feast': 'Feria VI Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/22/25': {'feast': 'Sabbato Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/09/25': {'feast': 'Dominica II Adventus', 'rank': 'sd2'},
 '12/02/25': {'feast': 'Dominica I Adventus', 'rank': 'sd2'},
 '12/25/25': {'feast': 'Nativitas DNJC', 'rank': 'd1'},
 '12/30/25': {'feast': 'Dominica Infra Octavam Nativitatis', 'rank': 'sd'},
 '12/30/25': {'feast': 'De VI Die infra Octavam Nativitatis', 'rank': 'sd'},
 '12/26/25': {'feast': 'S Stephani Protomartyris', 'rank': 'd2'},
 '12/27/25': {'feast': 'S Joannis Ap & Ev', 'rank': 'd2'},
 '12/28/25': {'feast': 'Ss Innocentium Mm', 'rank': 'd2'},
 '12/29/25': {'feast': 'S Thomas EM', 'rank': 'd'},
 '12/31/25': {'feast': 'S Sylvestri I PC', 'rank': 'd'},
}
