temporal = {
 '01/01/22': {'feast': 'Circumcisio Domini et Oct Nativitatis', 'rank': 'd2'},
 '01/02/22': {'feast': 'Octava S Stephani Protomartyris', 'rank': 'sp'},
 '01/03/22': {'feast': 'Octava S Joannis Ap & Ev', 'rank': 'sp'},
 '01/04/22': {'feast': 'Octava Ss Innocentium Mm', 'rank': 'sp'},
 '01/02/22': {'feast': 'SS Nominis Jesu', 'rank': 'd2'},
 '02/13/22': {'feast': 'Dominica in Septuagesima', 'rank': 'sd2'},
 '02/20/22': {'feast': 'Dominica in Sexagesima', 'rank': 'sd2'},
 '02/27/22': {'feast': 'Dominica in Quinquagesima', 'rank': 'sd2'},
 '01/07/22': {'feast': 'De die II infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/08/22': {'feast': 'De die III infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/10/22': {'feast': 'De die V infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/11/22': {'feast': 'De die VI infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/12/22': {'feast': 'De die VII infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/09/22': {'feast': 'S Familiæ Jesu Mariæ et Joseph; Dominica I post Epiphaniam', 'rank': 'dm'},
 '01/16/22': {'feast': 'Dominica II post Epiphaniam', 'rank': 'sp'},
 '01/23/22': {'feast': 'Dominica III post Epiphaniam', 'rank': 'sp'},
 '01/30/22': {'feast': 'Dominica IV post Epiphaniam', 'rank': 'sp'},
 '02/06/22': {'feast': 'Dominica V post Epiphaniam', 'rank': 'sp'},
 '03/02/22': {'feast': 'Dies Cinerum', 'rank': 'sp'},
 '03/02/22': {'feast': 'Feria V post Diem Cinerum', 'rank': 'sp'},
 '03/02/22': {'feast': 'Feria VI post Diem Cinerum', 'rank': 'sp'},
 '03/02/22': {'feast': 'Sabbato post Diem Cinerum', 'rank': 'sp'},
 '03/06/22': {'feast': 'Dominica I in Quadragesima', 'rank': 'sd1'},
 '03/07/22': {'feast': 'Feria II infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/08/22': {'feast': 'Feria III infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/09/22': {'feast': 'Feria IV Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/10/22': {'feast': 'Feria V infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/11/22': {'feast': 'Feria VI Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/12/22': {'feast': 'Sabbato Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/13/22': {'feast': 'Dominica II in Quadragesima', 'rank': 'sd1'},
 '03/14/22': {'feast': 'Feria II infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/15/22': {'feast': 'Feria III infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/16/22': {'feast': 'Feria IV infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/17/22': {'feast': 'Feria V infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/18/22': {'feast': 'Feria VI infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/19/22': {'feast': 'Sabbato infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/20/22': {'feast': 'Dominica III in Quadragesima', 'rank': 'sd1'},
 '03/21/22': {'feast': 'Feria II infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/22/22': {'feast': 'Feria III infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/23/22': {'feast': 'Feria IV infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/24/22': {'feast': 'Feria V infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/25/22': {'feast': 'Feria VI infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/26/22': {'feast': 'Sabbato infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/27/22': {'feast': 'Dominica IV in Quadragesima', 'rank': 'sd1'},
 '03/28/22': {'feast': 'Feria II infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/29/22': {'feast': 'Feria III infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/30/22': {'feast': 'Feria IV infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/31/22': {'feast': 'Feria V infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/01/22': {'feast': 'Feria VI infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/02/22': {'feast': 'Sabbato infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/03/22': {'feast': 'Dominica de Passione', 'rank': 'sd1'},
 '04/04/22': {'feast': 'Feria II infra Hebd de Passione', 'rank': 'sp'},
 '04/05/22': {'feast': 'Feria III infra Hebd de Passione', 'rank': 'sp'},
 '04/06/22': {'feast': 'Feria IV infra Hebd de Passione', 'rank': 'sp'},
 '04/07/22': {'feast': 'Feria V infra Hebd de Passione', 'rank': 'sp'},
 '04/08/22': {'feast': 'Septem Dolorum BMV', 'rank': 'dm'},
 '04/09/22': {'feast': 'Sabbato infra Hebd de Passione', 'rank': 'sp'},
 '04/10/22': {'feast': 'Dominica in Palmis', 'rank': 'sd1'},
 '04/11/22': {'feast': 'Feria II Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/12/22': {'feast': 'Feria III Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/13/22': {'feast': 'Feria IV Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/14/22': {'feast': 'Feria V in Cœna Domini', 'rank': 'd1'},
 '04/15/22': {'feast': 'Feria VI in Parasceve', 'rank': 'd1'},
 '04/16/22': {'feast': 'Sabbatum Sanctum', 'rank': 'd1'},
 '04/17/22': {'feast': 'Dominica Resurrectionis', 'rank': 'd1'},
 '04/18/22': {'feast': 'Feria II Paschatis', 'rank': 'd1'},
 '04/19/22': {'feast': 'Feria III Paschatis', 'rank': 'd1'},
 '04/20/22': {'feast': 'De die IV infra Oct Paschæ', 'rank': 'sd'},
 '04/21/22': {'feast': 'De die V infra Oct Paschæ', 'rank': 'sd'},
 '04/22/22': {'feast': 'De die VI infra Oct Paschæ', 'rank': 'sd'},
 '04/23/22': {'feast': 'Sabbatum in Albis', 'rank': 'sd'},
 '04/24/22': {'feast': 'Dominica in Albis', 'rank': 'sd'},
 '05/04/22': {'feast': 'Solemnitas S Joseph, Sponsi BMV C et Ecclesiæ Universalis Patroni', 'rank': 'd1'},
 '05/11/22': {'feast': 'Octava Solemnitas S Joseph', 'rank': 'dm'},
 '05/01/22': {'feast': 'Dominica II post Pascha', 'rank': 'sd'},
 '05/08/22': {'feast': 'Dominica III post Pascha', 'rank': 'sd'},
 '05/15/22': {'feast': 'Dominica IV post Pascha', 'rank': 'sd'},
 '05/23/22': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/24/22': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/25/22': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/25/22': {'feast': 'Vigilæ Ascensionis', 'rank': 'sp'},
 '05/26/22': {'feast': 'Ascensio DNJC', 'rank': 'd1'},
 '05/22/22': {'feast': 'Dominica V post Pascha', 'rank': 'sd'},
 '05/28/22': {'feast': 'De II die infra Oct Ascensionis', 'rank': 'sd'},
 '05/30/22': {'feast': 'De IV die infra Oct Ascensionis', 'rank': 'sd'},
 '05/31/22': {'feast': 'De V die infra Oct Ascensionis', 'rank': 'sd'},
 '06/01/22': {'feast': 'De VI die infra Oct Ascensionis', 'rank': 'sd'},
 '05/29/22': {'feast': 'Dominica infra Octavam Ascensionis', 'rank': 'sd'},
 '06/04/22': {'feast': 'Vigilia Pentecostes', 'rank': 'sd'},
 '06/05/22': {'feast': 'Dominica Pentecostes', 'rank': 'd1'},
 '05/28/22': {'feast': 'De II die infra Oct Pentecostes', 'rank': 'd1'},
 '05/29/22': {'feast': 'De III die infra Oct Pentecostes', 'rank': 'd1'},
 '05/30/22': {'feast': 'De IV die infra Oct Pentecostes', 'rank': 'd1'},
 '05/31/22': {'feast': 'De V die infra Oct Pentecostes', 'rank': 'd1'},
 '06/01/22': {'feast': 'De VI die infra Oct Pentecostes', 'rank': 'd1'},
 '06/02/22': {'feast': 'Sabbato die infra Oct Pentecostes', 'rank': 'd1'},
 '06/08/22': {'feast': 'Feria IV Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/10/22': {'feast': 'Feria VI Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/11/22': {'feast': 'Sabbato Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/12/22': {'feast': 'Dominica Sanctissimæ Trinitatis', 'rank': 'd1'},
 '06/17/22': {'feast': 'De II die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/18/22': {'feast': 'De III die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/20/22': {'feast': 'De V die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/21/22': {'feast': 'De VI die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/22/22': {'feast': 'De VII die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/16/22': {'feast': 'Sanctissimi Corporis Christi', 'rank': 'd1'},
 '06/23/22': {'feast': 'Octava SSmi Corporis Christi', 'rank': 'dm'},
 '06/19/22': {'feast': 'Dominica II post Pentecosten infra Octavam Corporis Christi', 'rank': 'sd'},
 '06/25/22': {'feast': 'De II die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/27/22': {'feast': 'De IV die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/28/22': {'feast': 'De V die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/29/22': {'feast': 'De VI die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/30/22': {'feast': 'De VII die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/24/22': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'd1'},
 '07/01/22': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'dm'},
 '06/26/22': {'feast': 'Dominica III post Pentecosten infra Octavam SSmi Cordis DNJC', 'rank': 'sd'},
 '07/03/22': {'feast': 'Dominica V post Pentecosten', 'rank': 'sd'},
 '07/10/22': {'feast': 'Dominica VI post Pentecosten', 'rank': 'sd'},
 '07/17/22': {'feast': 'Dominica VII post Pentecosten', 'rank': 'sd'},
 '07/24/22': {'feast': 'Dominica VIII post Pentecosten', 'rank': 'sd'},
 '07/31/22': {'feast': 'Dominica IX post Pentecosten', 'rank': 'sd'},
 '08/07/22': {'feast': 'Dominica X post Pentecosten', 'rank': 'sd'},
 '08/14/22': {'feast': 'Dominica XI post Pentecosten', 'rank': 'sd'},
 '08/21/22': {'feast': 'Dominica XII post Pentecosten', 'rank': 'sd'},
 '08/28/22': {'feast': 'Dominica XIII post Pentecosten', 'rank': 'sd'},
 '09/04/22': {'feast': 'Dominica XIV post Pentecosten', 'rank': 'sd'},
 '09/11/22': {'feast': 'Dominica XV post Pentecosten', 'rank': 'sd'},
 '09/14/22': {'feast': 'Feria IV Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/16/22': {'feast': 'Feria VI Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/17/22': {'feast': 'Sabbato Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/18/22': {'feast': 'Dominica XVI post Pentecosten', 'rank': 'sd'},
 '09/25/22': {'feast': 'Dominica XVII post Pentecosten', 'rank': 'sd'},
 '10/02/22': {'feast': 'Dominica XVIII post Pentecosten', 'rank': 'sd'},
 '10/09/22': {'feast': 'Dominica XIX post Pentecosten', 'rank': 'sd'},
 '10/16/22': {'feast': 'Dominica XX post Pentecosten', 'rank': 'sd'},
 '10/23/22': {'feast': 'Dominica XXI post Pentecosten', 'rank': 'sd'},
 '10/30/22': {'feast': 'Dominica XXII post Pentecosten', 'rank': 'sd'},
 '11/06/22': {'feast': 'Dominica XXIII post Pentecosten', 'rank': 'sd'},
 '11/13/22': {'feast': 'Dominica XXIV post Pentecosten', 'rank': 'sd'},
 '11/20/22': {'feast': 'Dominica XXV post Pentecosten', 'rank': 'sd'},
 '11/27/22': {'feast': 'Dominica XXVI post Pentecosten', 'rank': 'sd'},
 '12/25/22': {'feast': 'Dominica IV Adventus', 'rank': 'sd2'},
 '12/18/22': {'feast': 'Dominica III Adventus', 'rank': 'sd2'},
 '12/21/22': {'feast': 'Feria IV Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/23/22': {'feast': 'Feria VI Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/24/22': {'feast': 'Sabbato Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/11/22': {'feast': 'Dominica II Adventus', 'rank': 'sd2'},
 '12/04/22': {'feast': 'Dominica I Adventus', 'rank': 'sd2'},
 '12/25/22': {'feast': 'Nativitas DNJC', 'rank': 'd1'},
 '12/30/22': {'feast': 'Dominica Infra Octavam Nativitatis reposit', 'rank': 'sd'},
 '12/26/22': {'feast': 'S Stephani Protomartyris', 'rank': 'd2'},
 '12/27/22': {'feast': 'S Joannis Ap & Ev', 'rank': 'd2'},
 '12/28/22': {'feast': 'Ss Innocentium Mm', 'rank': 'd2'},
 '12/29/22': {'feast': 'S Thomas EM', 'rank': 'd'},
 '12/31/22': {'feast': 'S Sylvestri I PC', 'rank': 'd'},
}
