temporal = {
 '01/01/86': {'feast': 'Circumcisio Domini et Oct Nativitatis', 'rank': 'd2'},
 '01/02/86': {'feast': 'Octava S Stephani Protomartyris', 'rank': 'sp'},
 '01/03/86': {'feast': 'Octava S Joannis Ap & Ev', 'rank': 'sp'},
 '01/04/86': {'feast': 'Octava Ss Innocentium Mm', 'rank': 'sp'},
 '01/05/86': {'feast': 'SS Nominis Jesu', 'rank': 'd2'},
 '02/16/86': {'feast': 'Dominica in Septuagesima', 'rank': 'sd2'},
 '02/23/86': {'feast': 'Dominica in Sexagesima', 'rank': 'sd2'},
 '03/02/86': {'feast': 'Dominica in Quinquagesima', 'rank': 'sd2'},
 '01/07/86': {'feast': 'De die II infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/08/86': {'feast': 'De die III infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/09/86': {'feast': 'De die IV infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/10/86': {'feast': 'De die V infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/11/86': {'feast': 'De die VI infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/12/86': {'feast': 'S Familiæ Jesu Mariæ et Joseph; Dominica I post Epiphaniam', 'rank': 'dm'},
 '01/19/86': {'feast': 'Dominica II post Epiphaniam', 'rank': 'sp'},
 '01/26/86': {'feast': 'Dominica III post Epiphaniam', 'rank': 'sp'},
 '02/02/86': {'feast': 'Dominica IV post Epiphaniam', 'rank': 'sp'},
 '02/09/86': {'feast': 'Dominica V post Epiphaniam', 'rank': 'sp'},
 '03/05/86': {'feast': 'Dies Cinerum', 'rank': 'sp'},
 '03/05/86': {'feast': 'Feria V post Diem Cinerum', 'rank': 'sp'},
 '03/05/86': {'feast': 'Feria VI post Diem Cinerum', 'rank': 'sp'},
 '03/05/86': {'feast': 'Sabbato post Diem Cinerum', 'rank': 'sp'},
 '03/09/86': {'feast': 'Dominica I in Quadragesima', 'rank': 'sd1'},
 '03/10/86': {'feast': 'Feria II infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/11/86': {'feast': 'Feria III infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/12/86': {'feast': 'Feria IV Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/13/86': {'feast': 'Feria V infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/14/86': {'feast': 'Feria VI Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/15/86': {'feast': 'Sabbato Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/16/86': {'feast': 'Dominica II in Quadragesima', 'rank': 'sd1'},
 '03/17/86': {'feast': 'Feria II infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/18/86': {'feast': 'Feria III infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/19/86': {'feast': 'Feria IV infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/20/86': {'feast': 'Feria V infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/21/86': {'feast': 'Feria VI infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/22/86': {'feast': 'Sabbato infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/23/86': {'feast': 'Dominica III in Quadragesima', 'rank': 'sd1'},
 '03/24/86': {'feast': 'Feria II infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/25/86': {'feast': 'Feria III infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/26/86': {'feast': 'Feria IV infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/27/86': {'feast': 'Feria V infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/28/86': {'feast': 'Feria VI infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/29/86': {'feast': 'Sabbato infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/30/86': {'feast': 'Dominica IV in Quadragesima', 'rank': 'sd1'},
 '03/31/86': {'feast': 'Feria II infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/01/86': {'feast': 'Feria III infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/02/86': {'feast': 'Feria IV infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/03/86': {'feast': 'Feria V infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/04/86': {'feast': 'Feria VI infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/05/86': {'feast': 'Sabbato infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/06/86': {'feast': 'Dominica de Passione', 'rank': 'sd1'},
 '04/07/86': {'feast': 'Feria II infra Hebd de Passione', 'rank': 'sp'},
 '04/08/86': {'feast': 'Feria III infra Hebd de Passione', 'rank': 'sp'},
 '04/09/86': {'feast': 'Feria IV infra Hebd de Passione', 'rank': 'sp'},
 '04/10/86': {'feast': 'Feria V infra Hebd de Passione', 'rank': 'sp'},
 '04/11/86': {'feast': 'Septem Dolorum BMV', 'rank': 'dm'},
 '04/12/86': {'feast': 'Sabbato infra Hebd de Passione', 'rank': 'sp'},
 '04/13/86': {'feast': 'Dominica in Palmis', 'rank': 'sd1'},
 '04/14/86': {'feast': 'Feria II Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/15/86': {'feast': 'Feria III Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/16/86': {'feast': 'Feria IV Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/17/86': {'feast': 'Feria V in Cœna Domini', 'rank': 'd1'},
 '04/18/86': {'feast': 'Feria VI in Parasceve', 'rank': 'd1'},
 '04/19/86': {'feast': 'Sabbatum Sanctum', 'rank': 'd1'},
 '04/20/86': {'feast': 'Dominica Resurrectionis', 'rank': 'd1'},
 '04/21/86': {'feast': 'Feria II Paschatis', 'rank': 'd1'},
 '04/22/86': {'feast': 'Feria III Paschatis', 'rank': 'd1'},
 '04/23/86': {'feast': 'De die IV infra Oct Paschæ', 'rank': 'sd'},
 '04/24/86': {'feast': 'De die V infra Oct Paschæ', 'rank': 'sd'},
 '04/25/86': {'feast': 'De die VI infra Oct Paschæ', 'rank': 'sd'},
 '04/26/86': {'feast': 'Sabbatum in Albis', 'rank': 'sd'},
 '04/27/86': {'feast': 'Dominica in Albis', 'rank': 'sd'},
 '05/07/86': {'feast': 'Solemnitas S Joseph, Sponsi BMV C et Ecclesiæ Universalis Patroni', 'rank': 'd1'},
 '05/14/86': {'feast': 'Octava Solemnitas S Joseph', 'rank': 'dm'},
 '05/04/86': {'feast': 'Dominica II post Pascha', 'rank': 'sd'},
 '05/11/86': {'feast': 'Dominica III post Pascha', 'rank': 'sd'},
 '05/18/86': {'feast': 'Dominica IV post Pascha', 'rank': 'sd'},
 '05/26/86': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/27/86': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/28/86': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/28/86': {'feast': 'Vigilæ Ascensionis', 'rank': 'sp'},
 '05/29/86': {'feast': 'Ascensio DNJC', 'rank': 'd1'},
 '05/25/86': {'feast': 'Dominica V post Pascha', 'rank': 'sd'},
 '05/31/86': {'feast': 'De II die infra Oct Ascensionis', 'rank': 'sd'},
 '06/02/86': {'feast': 'De IV die infra Oct Ascensionis', 'rank': 'sd'},
 '06/03/86': {'feast': 'De V die infra Oct Ascensionis', 'rank': 'sd'},
 '06/04/86': {'feast': 'De VI die infra Oct Ascensionis', 'rank': 'sd'},
 '06/01/86': {'feast': 'Dominica infra Octavam Ascensionis', 'rank': 'sd'},
 '06/07/86': {'feast': 'Vigilia Pentecostes', 'rank': 'sd'},
 '06/08/86': {'feast': 'Dominica Pentecostes', 'rank': 'd1'},
 '05/31/86': {'feast': 'De II die infra Oct Pentecostes', 'rank': 'd1'},
 '06/01/86': {'feast': 'De III die infra Oct Pentecostes', 'rank': 'd1'},
 '06/02/86': {'feast': 'De IV die infra Oct Pentecostes', 'rank': 'd1'},
 '06/03/86': {'feast': 'De V die infra Oct Pentecostes', 'rank': 'd1'},
 '06/04/86': {'feast': 'De VI die infra Oct Pentecostes', 'rank': 'd1'},
 '06/05/86': {'feast': 'Sabbato die infra Oct Pentecostes', 'rank': 'd1'},
 '06/11/86': {'feast': 'Feria IV Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/13/86': {'feast': 'Feria VI Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/14/86': {'feast': 'Sabbato Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/15/86': {'feast': 'Dominica Sanctissimæ Trinitatis', 'rank': 'd1'},
 '06/20/86': {'feast': 'De II die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/21/86': {'feast': 'De III die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/23/86': {'feast': 'De V die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/24/86': {'feast': 'De VI die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/25/86': {'feast': 'De VII die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/19/86': {'feast': 'Sanctissimi Corporis Christi', 'rank': 'd1'},
 '06/26/86': {'feast': 'Octava SSmi Corporis Christi', 'rank': 'dm'},
 '06/22/86': {'feast': 'Dominica II post Pentecosten infra Octavam Corporis Christi', 'rank': 'sd'},
 '06/28/86': {'feast': 'De II die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/30/86': {'feast': 'De IV die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '07/01/86': {'feast': 'De V die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '07/02/86': {'feast': 'De VI die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '07/03/86': {'feast': 'De VII die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/27/86': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'd1'},
 '07/04/86': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'dm'},
 '06/29/86': {'feast': 'Dominica III post Pentecosten infra Octavam SSmi Cordis DNJC', 'rank': 'sd'},
 '07/06/86': {'feast': 'Dominica V post Pentecosten', 'rank': 'sd'},
 '07/13/86': {'feast': 'Dominica VI post Pentecosten', 'rank': 'sd'},
 '07/20/86': {'feast': 'Dominica VII post Pentecosten', 'rank': 'sd'},
 '07/27/86': {'feast': 'Dominica VIII post Pentecosten', 'rank': 'sd'},
 '08/03/86': {'feast': 'Dominica IX post Pentecosten', 'rank': 'sd'},
 '08/10/86': {'feast': 'Dominica X post Pentecosten', 'rank': 'sd'},
 '08/17/86': {'feast': 'Dominica XI post Pentecosten', 'rank': 'sd'},
 '08/24/86': {'feast': 'Dominica XII post Pentecosten', 'rank': 'sd'},
 '08/31/86': {'feast': 'Dominica XIII post Pentecosten', 'rank': 'sd'},
 '09/07/86': {'feast': 'Dominica XIV post Pentecosten', 'rank': 'sd'},
 '09/14/86': {'feast': 'Dominica XV post Pentecosten', 'rank': 'sd'},
 '09/17/86': {'feast': 'Feria IV Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/19/86': {'feast': 'Feria VI Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/20/86': {'feast': 'Sabbato Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/21/86': {'feast': 'Dominica XVI post Pentecosten', 'rank': 'sd'},
 '09/28/86': {'feast': 'Dominica XVII post Pentecosten', 'rank': 'sd'},
 '10/05/86': {'feast': 'Dominica XVIII post Pentecosten', 'rank': 'sd'},
 '10/12/86': {'feast': 'Dominica XIX post Pentecosten', 'rank': 'sd'},
 '10/19/86': {'feast': 'Dominica XX post Pentecosten', 'rank': 'sd'},
 '10/26/86': {'feast': 'Dominica XXI post Pentecosten', 'rank': 'sd'},
 '11/02/86': {'feast': 'Dominica XXII post Pentecosten', 'rank': 'sd'},
 '11/09/86': {'feast': 'Dominica XXIII post Pentecosten', 'rank': 'sd'},
 '11/16/86': {'feast': 'Dominica XXIV post Pentecosten', 'rank': 'sd'},
 '11/23/86': {'feast': 'Dominica XXV post Pentecosten', 'rank': 'sd'},
 '11/30/86': {'feast': 'Dominica XXVI post Pentecosten', 'rank': 'sd'},
 '12/21/86': {'feast': 'Dominica IV Adventus', 'rank': 'sd2'},
 '12/14/86': {'feast': 'Dominica III Adventus', 'rank': 'sd2'},
 '12/17/86': {'feast': 'Feria IV Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/19/86': {'feast': 'Feria VI Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/20/86': {'feast': 'Sabbato Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/07/86': {'feast': 'Dominica II Adventus', 'rank': 'sd2'},
 '11/30/86': {'feast': 'Dominica I Adventus', 'rank': 'sd2'},
 '12/25/86': {'feast': 'Nativitas DNJC', 'rank': 'd1'},
 '12/28/86': {'feast': 'Dominica Infra Octavam Nativitatis', 'rank': 'sd'},
 '12/26/86': {'feast': 'S Stephani Protomartyris', 'rank': 'd2'},
 '12/27/86': {'feast': 'S Joannis Ap & Ev', 'rank': 'd2'},
 '12/28/86': {'feast': 'Ss Innocentium Mm', 'rank': 'd2'},
 '12/29/86': {'feast': 'S Thomas EM', 'rank': 'd'},
 '12/31/86': {'feast': 'S Sylvestri I PC', 'rank': 'd'},
}
