temporal = {
 '01/01/65': {'feast': 'Circumcisio Domini et Oct Nativitatis', 'rank': 'd2'},
 '01/02/65': {'feast': 'Octava S Stephani Protomartyris', 'rank': 'sp'},
 '01/03/65': {'feast': 'Octava S Joannis Ap & Ev', 'rank': 'sp'},
 '01/04/65': {'feast': 'Octava Ss Innocentium Mm', 'rank': 'sp'},
 '01/02/65': {'feast': 'SS Nominis Jesu', 'rank': 'd2'},
 '02/05/65': {'feast': 'Dominica in Septuagesima', 'rank': 'sd2'},
 '02/12/65': {'feast': 'Dominica in Sexagesima', 'rank': 'sd2'},
 '02/19/65': {'feast': 'Dominica in Quinquagesima', 'rank': 'sd2'},
 '01/07/65': {'feast': 'De die II infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/09/65': {'feast': 'De die IV infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/10/65': {'feast': 'De die V infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/11/65': {'feast': 'De die VI infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/12/65': {'feast': 'De die VII infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/08/65': {'feast': 'S Familiæ Jesu Mariæ et Joseph; Dominica I post Epiphaniam', 'rank': 'dm'},
 '01/15/65': {'feast': 'Dominica II post Epiphaniam', 'rank': 'sp'},
 '01/22/65': {'feast': 'Dominica III post Epiphaniam', 'rank': 'sp'},
 '01/29/65': {'feast': 'Dominica IV post Epiphaniam', 'rank': 'sp'},
 '02/22/65': {'feast': 'Dies Cinerum', 'rank': 'sp'},
 '02/22/65': {'feast': 'Feria V post Diem Cinerum', 'rank': 'sp'},
 '02/22/65': {'feast': 'Feria VI post Diem Cinerum', 'rank': 'sp'},
 '02/22/65': {'feast': 'Sabbato post Diem Cinerum', 'rank': 'sp'},
 '02/26/65': {'feast': 'Dominica I in Quadragesima', 'rank': 'sd1'},
 '02/27/65': {'feast': 'Feria II infra Hebd I in Quadragesima', 'rank': 'sp'},
 '02/28/65': {'feast': 'Feria III infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/01/65': {'feast': 'Feria IV Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/02/65': {'feast': 'Feria V infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/03/65': {'feast': 'Feria VI Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/04/65': {'feast': 'Sabbato Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/05/65': {'feast': 'Dominica II in Quadragesima', 'rank': 'sd1'},
 '03/06/65': {'feast': 'Feria II infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/07/65': {'feast': 'Feria III infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/08/65': {'feast': 'Feria IV infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/09/65': {'feast': 'Feria V infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/10/65': {'feast': 'Feria VI infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/11/65': {'feast': 'Sabbato infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/12/65': {'feast': 'Dominica III in Quadragesima', 'rank': 'sd1'},
 '03/13/65': {'feast': 'Feria II infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/14/65': {'feast': 'Feria III infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/15/65': {'feast': 'Feria IV infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/16/65': {'feast': 'Feria V infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/17/65': {'feast': 'Feria VI infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/18/65': {'feast': 'Sabbato infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/19/65': {'feast': 'Dominica IV in Quadragesima', 'rank': 'sd1'},
 '03/20/65': {'feast': 'Feria II infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/21/65': {'feast': 'Feria III infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/22/65': {'feast': 'Feria IV infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/23/65': {'feast': 'Feria V infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/24/65': {'feast': 'Feria VI infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/25/65': {'feast': 'Sabbato infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/26/65': {'feast': 'Dominica de Passione', 'rank': 'sd1'},
 '03/27/65': {'feast': 'Feria II infra Hebd de Passione', 'rank': 'sp'},
 '03/28/65': {'feast': 'Feria III infra Hebd de Passione', 'rank': 'sp'},
 '03/29/65': {'feast': 'Feria IV infra Hebd de Passione', 'rank': 'sp'},
 '03/30/65': {'feast': 'Feria V infra Hebd de Passione', 'rank': 'sp'},
 '03/31/65': {'feast': 'Septem Dolorum BMV', 'rank': 'dm'},
 '04/01/65': {'feast': 'Sabbato infra Hebd de Passione', 'rank': 'sp'},
 '04/02/65': {'feast': 'Dominica in Palmis', 'rank': 'sd1'},
 '04/03/65': {'feast': 'Feria II Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/04/65': {'feast': 'Feria III Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/05/65': {'feast': 'Feria IV Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/06/65': {'feast': 'Feria V in Cœna Domini', 'rank': 'd1'},
 '04/07/65': {'feast': 'Feria VI in Parasceve', 'rank': 'd1'},
 '04/08/65': {'feast': 'Sabbatum Sanctum', 'rank': 'd1'},
 '04/09/65': {'feast': 'Dominica Resurrectionis', 'rank': 'd1'},
 '04/10/65': {'feast': 'Feria II Paschatis', 'rank': 'd1'},
 '04/11/65': {'feast': 'Feria III Paschatis', 'rank': 'd1'},
 '04/12/65': {'feast': 'De die IV infra Oct Paschæ', 'rank': 'sd'},
 '04/13/65': {'feast': 'De die V infra Oct Paschæ', 'rank': 'sd'},
 '04/14/65': {'feast': 'De die VI infra Oct Paschæ', 'rank': 'sd'},
 '04/15/65': {'feast': 'Sabbatum in Albis', 'rank': 'sd'},
 '04/16/65': {'feast': 'Dominica in Albis', 'rank': 'sd'},
 '04/26/65': {'feast': 'Solemnitas S Joseph, Sponsi BMV C et Ecclesiæ Universalis Patroni', 'rank': 'd1'},
 '05/03/65': {'feast': 'Octava Solemnitas S Joseph', 'rank': 'dm'},
 '04/23/65': {'feast': 'Dominica II post Pascha', 'rank': 'sd'},
 '04/30/65': {'feast': 'Dominica III post Pascha', 'rank': 'sd'},
 '05/07/65': {'feast': 'Dominica IV post Pascha', 'rank': 'sd'},
 '05/15/65': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/16/65': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/17/65': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/17/65': {'feast': 'Vigilæ Ascensionis', 'rank': 'sp'},
 '05/18/65': {'feast': 'Ascensio DNJC', 'rank': 'd1'},
 '05/14/65': {'feast': 'Dominica V post Pascha', 'rank': 'sd'},
 '05/20/65': {'feast': 'De II die infra Oct Ascensionis', 'rank': 'sd'},
 '05/22/65': {'feast': 'De IV die infra Oct Ascensionis', 'rank': 'sd'},
 '05/23/65': {'feast': 'De V die infra Oct Ascensionis', 'rank': 'sd'},
 '05/24/65': {'feast': 'De VI die infra Oct Ascensionis', 'rank': 'sd'},
 '05/21/65': {'feast': 'Dominica infra Octavam Ascensionis', 'rank': 'sd'},
 '05/27/65': {'feast': 'Vigilia Pentecostes', 'rank': 'sd'},
 '05/28/65': {'feast': 'Dominica Pentecostes', 'rank': 'd1'},
 '05/20/65': {'feast': 'De II die infra Oct Pentecostes', 'rank': 'd1'},
 '05/21/65': {'feast': 'De III die infra Oct Pentecostes', 'rank': 'd1'},
 '05/22/65': {'feast': 'De IV die infra Oct Pentecostes', 'rank': 'd1'},
 '05/23/65': {'feast': 'De V die infra Oct Pentecostes', 'rank': 'd1'},
 '05/24/65': {'feast': 'De VI die infra Oct Pentecostes', 'rank': 'd1'},
 '05/25/65': {'feast': 'Sabbato die infra Oct Pentecostes', 'rank': 'd1'},
 '05/31/65': {'feast': 'Feria IV Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/02/65': {'feast': 'Feria VI Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/03/65': {'feast': 'Sabbato Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/04/65': {'feast': 'Dominica Sanctissimæ Trinitatis', 'rank': 'd1'},
 '06/09/65': {'feast': 'De II die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/10/65': {'feast': 'De III die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/12/65': {'feast': 'De V die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/13/65': {'feast': 'De VI die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/14/65': {'feast': 'De VII die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/08/65': {'feast': 'Sanctissimi Corporis Christi', 'rank': 'd1'},
 '06/15/65': {'feast': 'Octava SSmi Corporis Christi', 'rank': 'dm'},
 '06/11/65': {'feast': 'Dominica II post Pentecosten infra Octavam Corporis Christi', 'rank': 'sd'},
 '06/17/65': {'feast': 'De II die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/19/65': {'feast': 'De IV die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/20/65': {'feast': 'De V die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/21/65': {'feast': 'De VI die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/22/65': {'feast': 'De VII die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/16/65': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'd1'},
 '06/23/65': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'dm'},
 '06/18/65': {'feast': 'Dominica III post Pentecosten infra Octavam SSmi Cordis DNJC', 'rank': 'sd'},
 '06/25/65': {'feast': 'Dominica V post Pentecosten', 'rank': 'sd'},
 '07/02/65': {'feast': 'Dominica VI post Pentecosten', 'rank': 'sd'},
 '07/09/65': {'feast': 'Dominica VII post Pentecosten', 'rank': 'sd'},
 '07/16/65': {'feast': 'Dominica VIII post Pentecosten', 'rank': 'sd'},
 '07/23/65': {'feast': 'Dominica IX post Pentecosten', 'rank': 'sd'},
 '07/30/65': {'feast': 'Dominica X post Pentecosten', 'rank': 'sd'},
 '08/06/65': {'feast': 'Dominica XI post Pentecosten', 'rank': 'sd'},
 '08/13/65': {'feast': 'Dominica XII post Pentecosten', 'rank': 'sd'},
 '08/20/65': {'feast': 'Dominica XIII post Pentecosten', 'rank': 'sd'},
 '08/27/65': {'feast': 'Dominica XIV post Pentecosten', 'rank': 'sd'},
 '09/03/65': {'feast': 'Dominica XV post Pentecosten', 'rank': 'sd'},
 '09/10/65': {'feast': 'Dominica XVI post Pentecosten', 'rank': 'sd'},
 '09/17/65': {'feast': 'Dominica XVII post Pentecosten', 'rank': 'sd'},
 '09/20/65': {'feast': 'Feria IV Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/22/65': {'feast': 'Feria VI Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/23/65': {'feast': 'Sabbato Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/24/65': {'feast': 'Dominica XVIII post Pentecosten', 'rank': 'sd'},
 '10/01/65': {'feast': 'Dominica XIX post Pentecosten', 'rank': 'sd'},
 '10/08/65': {'feast': 'Dominica XX post Pentecosten', 'rank': 'sd'},
 '10/15/65': {'feast': 'Dominica XXI post Pentecosten', 'rank': 'sd'},
 '10/22/65': {'feast': 'Dominica XXII post Pentecosten', 'rank': 'sd'},
 '10/29/65': {'feast': 'Dominica XXIII post Pentecosten', 'rank': 'sd'},
 '11/05/65': {'feast': 'Dominica XXIV post Pentecosten', 'rank': 'sd'},
 '11/12/65': {'feast': 'Dominica XXV post Pentecosten', 'rank': 'sd'},
 '11/19/65': {'feast': 'Dominica XXVI post Pentecosten', 'rank': 'sd'},
 '11/26/65': {'feast': 'Dominica XXVII post Pentecosten', 'rank': 'sd'},
 '12/24/65': {'feast': 'Dominica IV Adventus', 'rank': 'sd2'},
 '12/17/65': {'feast': 'Dominica III Adventus', 'rank': 'sd2'},
 '12/20/65': {'feast': 'Feria IV Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/22/65': {'feast': 'Feria VI Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/23/65': {'feast': 'Sabbato Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/10/65': {'feast': 'Dominica II Adventus', 'rank': 'sd2'},
 '12/03/65': {'feast': 'Dominica I Adventus', 'rank': 'sd2'},
 '12/25/65': {'feast': 'Nativitas DNJC', 'rank': 'd1'},
 '12/31/65': {'feast': 'Dominica Infra Octavam Nativitatis', 'rank': 'sd'},
 '12/26/65': {'feast': 'S Stephani Protomartyris', 'rank': 'd2'},
 '12/27/65': {'feast': 'S Joannis Ap & Ev', 'rank': 'd2'},
 '12/28/65': {'feast': 'Ss Innocentium Mm', 'rank': 'd2'},
 '12/29/65': {'feast': 'S Thomas EM', 'rank': 'd'},
 '12/31/65': {'feast': 'S Sylvestri I PC', 'rank': 'd'},
}
