temporal = {
 '01/01/20': {'feast': 'Circumcisio Domini et Oct Nativitatis', 'rank': 'd2', 'weekday': 'Wed'},
 '01/02/20': {'feast': 'Octava S Stephani Protomartyris', 'rank': 'sp', 'weekday': 'Thu'},
 '01/03/20': {'feast': 'Octava S Joannis Ap & Ev', 'rank': 'sp', 'weekday': 'Fri'},
 '01/04/20': {'feast': 'Octava Ss Innocentium Mm', 'rank': 'sp', 'weekday': 'Sat'},
 '01/05/20': {'feast': 'SS Nominis Jesu', 'rank': 'd2', 'weekday': 'Sun'},
 '02/09/20': {'feast': 'Dominica in Septuagesima', 'rank': 'sd2', 'weekday': 'Sun'},
 '02/16/20': {'feast': 'Dominica in Sexagesima', 'rank': 'sd2', 'weekday': 'Sun'},
 '02/23/20': {'feast': 'Dominica in Quinquagesima', 'rank': 'sd2', 'weekday': 'Sun'},
 '01/07/20': {'feast': 'De die II infra Oct Epiphaniæ', 'rank': 'sd', 'weekday': 'Tue'},
 '01/08/20': {'feast': 'De die III infra Oct Epiphaniæ', 'rank': 'sd', 'weekday': 'Wed'},
 '01/09/20': {'feast': 'De die IV infra Oct Epiphaniæ', 'rank': 'sd', 'weekday': 'Thu'},
 '01/10/20': {'feast': 'De die V infra Oct Epiphaniæ', 'rank': 'sd', 'weekday': 'Fri'},
 '01/11/20': {'feast': 'De die VI infra Oct Epiphaniæ', 'rank': 'sd', 'weekday': 'Sat'},
 '01/12/20': {'feast': 'S Familiæ Jesu Mariæ et Joseph; Dominica I post Epiphaniam', 'rank': 'dm', 'weekday': 'Sun'},
 '01/19/20': {'feast': 'Dominica II post Epiphaniam', 'rank': 'sp', 'weekday': 'Sun'},
 '01/26/20': {'feast': 'Dominica III post Epiphaniam', 'rank': 'sp', 'weekday': 'Sun'},
 '02/02/20': {'feast': 'Dominica IV post Epiphaniam', 'rank': 'sp', 'weekday': 'Sun'},
 '02/26/20': {'feast': 'Dies Cinerum', 'rank': 'sp', 'weekday': 'Wed'},
 '02/26/20': {'feast': 'Feria V post Diem Cinerum', 'rank': 'sp', 'weekday': 'Thu'},
 '02/26/20': {'feast': 'Feria VI post Diem Cinerum', 'rank': 'sp', 'weekday': 'Fri'},
 '02/26/20': {'feast': 'Sabbato post Diem Cinerum', 'rank': 'sp', 'weekday': 'Sat'},
 '03/01/20': {'feast': 'Dominica I in Quadragesima', 'rank': 'sd1', 'weekday': 'Sun'},
 '03/02/20': {'feast': 'Feria II infra Hebd I in Quadragesima', 'rank': 'sp', 'weekday': 'Mon'},
 '03/03/20': {'feast': 'Feria III infra Hebd I in Quadragesima', 'rank': 'sp', 'weekday': 'Tue'},
 '03/04/20': {'feast': 'Feria IV Quattuor Temporum Quadragesimæ', 'rank': 'sp', 'weekday': 'Wed'},
 '03/05/20': {'feast': 'Feria V infra Hebd I in Quadragesima', 'rank': 'sp', 'weekday': 'Thu'},
 '03/06/20': {'feast': 'Feria VI Quattuor Temporum Quadragesimæ', 'rank': 'sp', 'weekday': 'Fri'},
 '03/07/20': {'feast': 'Sabbato Quattuor Temporum Quadragesimæ', 'rank': 'sp', 'weekday': 'Sat'},
 '03/08/20': {'feast': 'Dominica II in Quadragesima', 'rank': 'sd1', 'weekday': 'Sun'},
 '03/09/20': {'feast': 'Feria II infra Hebd II in Quadragesima', 'rank': 'sp', 'weekday': 'Mon'},
 '03/10/20': {'feast': 'Feria III infra Hebd II in Quadragesima', 'rank': 'sp', 'weekday': 'Tue'},
 '03/11/20': {'feast': 'Feria IV infra Hebd II in Quadragesima', 'rank': 'sp', 'weekday': 'Wed'},
 '03/12/20': {'feast': 'Feria V infra Hebd II in Quadragesima', 'rank': 'sp', 'weekday': 'Thu'},
 '03/13/20': {'feast': 'Feria VI infra Hebd II in Quadragesima', 'rank': 'sp', 'weekday': 'Fri'},
 '03/14/20': {'feast': 'Sabbato infra Hebd II in Quadragesima', 'rank': 'sp', 'weekday': 'Sat'},
 '03/15/20': {'feast': 'Dominica III in Quadragesima', 'rank': 'sd1', 'weekday': 'Sun'},
 '03/16/20': {'feast': 'Feria II infra Hebd III in Quadragesima', 'rank': 'sp', 'weekday': 'Mon'},
 '03/17/20': {'feast': 'Feria III infra Hebd III in Quadragesima', 'rank': 'sp', 'weekday': 'Tue'},
 '03/18/20': {'feast': 'Feria IV infra Hebd III in Quadragesima', 'rank': 'sp', 'weekday': 'Wed'},
 '03/19/20': {'feast': 'Feria V infra Hebd III in Quadragesima', 'rank': 'sp', 'weekday': 'Thu'},
 '03/20/20': {'feast': 'Feria VI infra Hebd III in Quadragesima', 'rank': 'sp', 'weekday': 'Fri'},
 '03/21/20': {'feast': 'Sabbato infra Hebd III in Quadragesima', 'rank': 'sp', 'weekday': 'Sat'},
 '03/22/20': {'feast': 'Dominica IV in Quadragesima', 'rank': 'sd1', 'weekday': 'Sun'},
 '03/23/20': {'feast': 'Feria II infra Hebd IV in Quadragesima', 'rank': 'sp', 'weekday': 'Mon'},
 '03/24/20': {'feast': 'Feria III infra Hebd IV in Quadragesima', 'rank': 'sp', 'weekday': 'Tue'},
 '03/25/20': {'feast': 'Feria IV infra Hebd IV in Quadragesima', 'rank': 'sp', 'weekday': 'Wed'},
 '03/26/20': {'feast': 'Feria V infra Hebd IV in Quadragesima', 'rank': 'sp', 'weekday': 'Thu'},
 '03/27/20': {'feast': 'Feria VI infra Hebd IV in Quadragesima', 'rank': 'sp', 'weekday': 'Fri'},
 '03/28/20': {'feast': 'Sabbato infra Hebd IV in Quadragesima', 'rank': 'sp', 'weekday': 'Sat'},
 '03/29/20': {'feast': 'Dominica de Passione', 'rank': 'sd1', 'weekday': 'Sun'},
 '03/30/20': {'feast': 'Feria II infra Hebd de Passione', 'rank': 'sp', 'weekday': 'Mon'},
 '03/31/20': {'feast': 'Feria III infra Hebd de Passione', 'rank': 'sp', 'weekday': 'Tue'},
 '04/01/20': {'feast': 'Feria IV infra Hebd de Passione', 'rank': 'sp', 'weekday': 'Wed'},
 '04/02/20': {'feast': 'Feria V infra Hebd de Passione', 'rank': 'sp', 'weekday': 'Thu'},
 '04/03/20': {'feast': 'Septem Dolorum BMV', 'rank': 'dm', 'weekday': 'Fri'},
 '04/04/20': {'feast': 'Sabbato infra Hebd de Passione', 'rank': 'sp', 'weekday': 'Sat'},
 '04/05/20': {'feast': 'Dominica in Palmis', 'rank': 'sd1', 'weekday': 'Sun'},
 '04/06/20': {'feast': 'Feria II Majoris Hebd; Feria Priv', 'rank': 'sp', 'weekday': 'Mon'},
 '04/07/20': {'feast': 'Feria III Majoris Hebd; Feria Priv', 'rank': 'sp', 'weekday': 'Tue'},
 '04/08/20': {'feast': 'Feria IV Majoris Hebd; Feria Priv', 'rank': 'sp', 'weekday': 'Wed'},
 '04/09/20': {'feast': 'Feria V in Cœna Domini', 'rank': 'd1', 'weekday': 'Thu'},
 '04/10/20': {'feast': 'Feria VI in Parasceve', 'rank': 'd1', 'weekday': 'Fri'},
 '04/11/20': {'feast': 'Sabbatum Sanctum', 'rank': 'd1', 'weekday': 'Sat'},
 '04/12/20': {'feast': 'Dominica Resurrectionis', 'rank': 'd1', 'weekday': 'Sun'},
 '04/19/20': {'feast': 'Dominica in Albis', 'rank': 'sd', 'weekday': 'Sun'},
 '04/26/20': {'feast': 'Dominica II post Pascha', 'rank': 'sd', 'weekday': 'Sun'},
 '05/03/20': {'feast': 'Dominica III post Pascha', 'rank': 'sd', 'weekday': 'Sun'},
 '05/10/20': {'feast': 'Dominica IV post Pascha', 'rank': 'sd', 'weekday': 'Sun'},
 '05/17/20': {'feast': 'Dominica V post Pascha', 'rank': 'sd', 'weekday': 'Sun'},
 '05/24/20': {'feast': 'Dominica infra Octavam Ascensionis', 'rank': 'sd', 'weekday': 'Sun'},
 '05/31/20': {'feast': 'Dominica Pentecostes', 'rank': 'd1', 'weekday': 'Sun'},
 '06/03/20': {'feast': 'Feria IV Quattuor infra Temporum Pentecostes', 'rank': 'd1', 'weekday': 'Wed'},
 '06/05/20': {'feast': 'Feria VI Quattuor infra Temporum Pentecostes', 'rank': 'd1', 'weekday': 'Fri'},
 '06/06/20': {'feast': 'Sabbato Quattuor infra Temporum Pentecostes', 'rank': 'd1', 'weekday': 'Sat'},
 '06/07/20': {'feast': 'Dominica Sanctissimæ Trinitatis', 'rank': 'd1', 'weekday': 'Sun'},
 '06/11/20': {'feast': 'Sanctissimi Corporis Christi', 'rank': 'd1', 'weekday': 'Thu'},
 '06/14/20': {'feast': 'Dominica II post Pentecosten infra Octavam Corporis Christi', 'rank': 'sd', 'weekday': 'Sun'},
 '06/19/20': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'd1', 'weekday': 'Fri'},
 '06/21/20': {'feast': 'Dominica III post Pentecosten infra Octavam SSmi Cordis DNJC', 'rank': 'sd', 'weekday': 'Sun'},
 '06/28/20': {'feast': 'Dominica IV post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '07/05/20': {'feast': 'Dominica V post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '07/12/20': {'feast': 'Dominica VI post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '07/19/20': {'feast': 'Dominica VII post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '07/26/20': {'feast': 'Dominica VIII post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '08/02/20': {'feast': 'Dominica IX post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '08/09/20': {'feast': 'Dominica X post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '08/16/20': {'feast': 'Dominica XI post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '08/23/20': {'feast': 'Dominica XII post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '08/30/20': {'feast': 'Dominica XIII post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '09/06/20': {'feast': 'Dominica XIV post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '09/13/20': {'feast': 'Dominica XV post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '09/16/20': {'feast': 'Feria IV Quattuor Temporum Septembris', 'rank': 'sd', 'weekday': 'Wed'},
 '09/18/20': {'feast': 'Feria VI Quattuor Temporum Septembris', 'rank': 'sd', 'weekday': 'Fri'},
 '09/19/20': {'feast': 'Sabbato Quattuor Temporum Septembris', 'rank': 'sd', 'weekday': 'Sat'},
 '09/20/20': {'feast': 'Dominica XVI post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '09/27/20': {'feast': 'Dominica XVII post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '10/04/20': {'feast': 'Dominica XVIII post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '10/11/20': {'feast': 'Dominica XIX post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '10/18/20': {'feast': 'Dominica XX post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '10/25/20': {'feast': 'Dominica XXI post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '11/01/20': {'feast': 'Dominica XXII post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '11/08/20': {'feast': 'Dominica XXIII post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '11/15/20': {'feast': 'Dominica XXIV post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '11/22/20': {'feast': 'Dominica XXV post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '11/29/20': {'feast': 'Dominica XXVI post Pentecosten', 'rank': 'sd', 'weekday': 'Sun'},
 '12/20/20': {'feast': 'Dominica IV Adventus', 'rank': 'sd2', 'weekday': 'Sun'},
 '12/13/20': {'feast': 'Dominica III Adventus', 'rank': 'sd2', 'weekday': 'Sun'},
 '12/16/20': {'feast': 'Feria IV Quattuor Temporum in Adventu', 'rank': 'sp', 'weekday': 'Wed'},
 '12/18/20': {'feast': 'Feria VI Quattuor Temporum in Adventu', 'rank': 'sp', 'weekday': 'Fri'},
 '12/19/20': {'feast': 'Sabbato Quattuor Temporum in Adventu', 'rank': 'sp', 'weekday': 'Sat'},
 '12/06/20': {'feast': 'Dominica II Adventus', 'rank': 'sd2', 'weekday': 'Sun'},
 '11/29/20': {'feast': 'Dominica I Adventus', 'rank': 'sd2', 'weekday': 'Sun'},
 '12/25/20': {'feast': 'Nativitas DNJC', 'rank': 'd1', 'weekday': 'Fri'},
 '12/30/20': {'feast': 'Dominica Infra Octavam Nativitatis reposit', 'rank': 'sd', 'weekday': 'Wed'},
 '12/26/20': {'feast': 'S Stephani Protomartyris', 'rank': 'd2', 'weekday': 'Sat'},
 '12/27/20': {'feast': 'S Joannis Ap & Ev', 'rank': 'd2', 'weekday': 'Sun'},
 '12/28/20': {'feast': 'Ss Innocentium Mm', 'rank': 'd2', 'weekday': 'Mon'},
 '12/29/20': {'feast': 'S Thomas EM', 'rank': 'd', 'weekday': 'Tue'},
 '12/31/20': {'feast': 'S Sylvestri I PC', 'rank': 'd', 'weekday': 'Thu'},
}
