temporal = {
 '01/01/26': {'feast': 'Circumcisio Domini et Oct Nativitatis', 'rank': 'd2'},
 '01/02/26': {'feast': 'Octava S Stephani Protomartyris', 'rank': 'sp'},
 '01/03/26': {'feast': 'Octava S Joannis Ap & Ev', 'rank': 'sp'},
 '01/04/26': {'feast': 'Octava Ss Innocentium Mm', 'rank': 'sp'},
 '01/03/26': {'feast': 'SS Nominis Jesu', 'rank': 'd2'},
 '01/31/26': {'feast': 'Dominica in Septuagesima', 'rank': 'sd2'},
 '02/07/26': {'feast': 'Dominica in Sexagesima', 'rank': 'sd2'},
 '02/14/26': {'feast': 'Dominica in Quinquagesima', 'rank': 'sd2'},
 '01/07/26': {'feast': 'De die II infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/08/26': {'feast': 'De die III infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/09/26': {'feast': 'De die IV infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/11/26': {'feast': 'De die VI infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/12/26': {'feast': 'De die VII infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/10/26': {'feast': 'S Familiæ Jesu Mariæ et Joseph; Dominica I post Epiphaniam', 'rank': 'dm'},
 '01/17/26': {'feast': 'Dominica II post Epiphaniam', 'rank': 'sp'},
 '01/24/26': {'feast': 'Dominica III post Epiphaniam', 'rank': 'sp'},
 '02/17/26': {'feast': 'Dies Cinerum', 'rank': 'sp'},
 '02/17/26': {'feast': 'Feria V post Diem Cinerum', 'rank': 'sp'},
 '02/17/26': {'feast': 'Feria VI post Diem Cinerum', 'rank': 'sp'},
 '02/17/26': {'feast': 'Sabbato post Diem Cinerum', 'rank': 'sp'},
 '02/21/26': {'feast': 'Dominica I in Quadragesima', 'rank': 'sd1'},
 '02/22/26': {'feast': 'Feria II infra Hebd I in Quadragesima', 'rank': 'sp'},
 '02/23/26': {'feast': 'Feria III infra Hebd I in Quadragesima', 'rank': 'sp'},
 '02/24/26': {'feast': 'Feria IV Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '02/25/26': {'feast': 'Feria V infra Hebd I in Quadragesima', 'rank': 'sp'},
 '02/26/26': {'feast': 'Feria VI Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '02/27/26': {'feast': 'Sabbato Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '02/28/26': {'feast': 'Dominica II in Quadragesima', 'rank': 'sd1'},
 '03/01/26': {'feast': 'Feria II infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/02/26': {'feast': 'Feria III infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/03/26': {'feast': 'Feria IV infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/04/26': {'feast': 'Feria V infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/05/26': {'feast': 'Feria VI infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/06/26': {'feast': 'Sabbato infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/07/26': {'feast': 'Dominica III in Quadragesima', 'rank': 'sd1'},
 '03/08/26': {'feast': 'Feria II infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/09/26': {'feast': 'Feria III infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/10/26': {'feast': 'Feria IV infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/11/26': {'feast': 'Feria V infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/12/26': {'feast': 'Feria VI infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/13/26': {'feast': 'Sabbato infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/14/26': {'feast': 'Dominica IV in Quadragesima', 'rank': 'sd1'},
 '03/15/26': {'feast': 'Feria II infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/16/26': {'feast': 'Feria III infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/17/26': {'feast': 'Feria IV infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/18/26': {'feast': 'Feria V infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/19/26': {'feast': 'Feria VI infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/20/26': {'feast': 'Sabbato infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/21/26': {'feast': 'Dominica de Passione', 'rank': 'sd1'},
 '03/22/26': {'feast': 'Feria II infra Hebd de Passione', 'rank': 'sp'},
 '03/23/26': {'feast': 'Feria III infra Hebd de Passione', 'rank': 'sp'},
 '03/24/26': {'feast': 'Feria IV infra Hebd de Passione', 'rank': 'sp'},
 '03/25/26': {'feast': 'Feria V infra Hebd de Passione', 'rank': 'sp'},
 '03/26/26': {'feast': 'Septem Dolorum BMV', 'rank': 'dm'},
 '03/27/26': {'feast': 'Sabbato infra Hebd de Passione', 'rank': 'sp'},
 '03/28/26': {'feast': 'Dominica in Palmis', 'rank': 'sd1'},
 '03/29/26': {'feast': 'Feria II Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '03/30/26': {'feast': 'Feria III Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '03/31/26': {'feast': 'Feria IV Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/01/26': {'feast': 'Feria V in Cœna Domini', 'rank': 'd1'},
 '04/02/26': {'feast': 'Feria VI in Parasceve', 'rank': 'd1'},
 '04/03/26': {'feast': 'Sabbatum Sanctum', 'rank': 'd1'},
 '04/04/26': {'feast': 'Dominica Resurrectionis', 'rank': 'd1'},
 '04/05/26': {'feast': 'Feria II Paschatis', 'rank': 'd1'},
 '04/06/26': {'feast': 'Feria III Paschatis', 'rank': 'd1'},
 '04/07/26': {'feast': 'De die IV infra Oct Paschæ', 'rank': 'sd'},
 '04/08/26': {'feast': 'De die V infra Oct Paschæ', 'rank': 'sd'},
 '04/09/26': {'feast': 'De die VI infra Oct Paschæ', 'rank': 'sd'},
 '04/10/26': {'feast': 'Sabbatum in Albis', 'rank': 'sd'},
 '04/11/26': {'feast': 'Dominica in Albis', 'rank': 'sd'},
 '04/21/26': {'feast': 'Solemnitas S Joseph, Sponsi BMV C et Ecclesiæ Universalis Patroni', 'rank': 'd1'},
 '04/28/26': {'feast': 'Octava Solemnitas S Joseph', 'rank': 'dm'},
 '04/18/26': {'feast': 'Dominica II post Pascha', 'rank': 'sd'},
 '04/25/26': {'feast': 'Dominica III post Pascha', 'rank': 'sd'},
 '05/02/26': {'feast': 'Dominica IV post Pascha', 'rank': 'sd'},
 '05/10/26': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/11/26': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/12/26': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/12/26': {'feast': 'Vigilæ Ascensionis', 'rank': 'sp'},
 '05/13/26': {'feast': 'Ascensio DNJC', 'rank': 'd1'},
 '05/09/26': {'feast': 'Dominica V post Pascha', 'rank': 'sd'},
 '05/15/26': {'feast': 'De II die infra Oct Ascensionis', 'rank': 'sd'},
 '05/17/26': {'feast': 'De IV die infra Oct Ascensionis', 'rank': 'sd'},
 '05/18/26': {'feast': 'De V die infra Oct Ascensionis', 'rank': 'sd'},
 '05/19/26': {'feast': 'De VI die infra Oct Ascensionis', 'rank': 'sd'},
 '05/16/26': {'feast': 'Dominica infra Octavam Ascensionis', 'rank': 'sd'},
 '05/22/26': {'feast': 'Vigilia Pentecostes', 'rank': 'sd'},
 '05/23/26': {'feast': 'Dominica Pentecostes', 'rank': 'd1'},
 '05/15/26': {'feast': 'De II die infra Oct Pentecostes', 'rank': 'd1'},
 '05/16/26': {'feast': 'De III die infra Oct Pentecostes', 'rank': 'd1'},
 '05/17/26': {'feast': 'De IV die infra Oct Pentecostes', 'rank': 'd1'},
 '05/18/26': {'feast': 'De V die infra Oct Pentecostes', 'rank': 'd1'},
 '05/19/26': {'feast': 'De VI die infra Oct Pentecostes', 'rank': 'd1'},
 '05/20/26': {'feast': 'Sabbato die infra Oct Pentecostes', 'rank': 'd1'},
 '05/26/26': {'feast': 'Feria IV Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '05/28/26': {'feast': 'Feria VI Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '05/29/26': {'feast': 'Sabbato Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '05/30/26': {'feast': 'Dominica Sanctissimæ Trinitatis', 'rank': 'd1'},
 '06/04/26': {'feast': 'De II die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/05/26': {'feast': 'De III die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/07/26': {'feast': 'De V die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/08/26': {'feast': 'De VI die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/09/26': {'feast': 'De VII die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/03/26': {'feast': 'Sanctissimi Corporis Christi', 'rank': 'd1'},
 '06/10/26': {'feast': 'Octava SSmi Corporis Christi', 'rank': 'dm'},
 '06/06/26': {'feast': 'Dominica II post Pentecosten infra Octavam Corporis Christi', 'rank': 'sd'},
 '06/12/26': {'feast': 'De II die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/14/26': {'feast': 'De IV die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/15/26': {'feast': 'De V die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/16/26': {'feast': 'De VI die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/17/26': {'feast': 'De VII die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/11/26': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'd1'},
 '06/18/26': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'dm'},
 '06/13/26': {'feast': 'Dominica III post Pentecosten infra Octavam SSmi Cordis DNJC', 'rank': 'sd'},
 '06/20/26': {'feast': 'Dominica V post Pentecosten', 'rank': 'sd'},
 '06/27/26': {'feast': 'Dominica VI post Pentecosten', 'rank': 'sd'},
 '07/04/26': {'feast': 'Dominica VII post Pentecosten', 'rank': 'sd'},
 '07/11/26': {'feast': 'Dominica VIII post Pentecosten', 'rank': 'sd'},
 '07/18/26': {'feast': 'Dominica IX post Pentecosten', 'rank': 'sd'},
 '07/25/26': {'feast': 'Dominica X post Pentecosten', 'rank': 'sd'},
 '08/01/26': {'feast': 'Dominica XI post Pentecosten', 'rank': 'sd'},
 '08/08/26': {'feast': 'Dominica XII post Pentecosten', 'rank': 'sd'},
 '08/15/26': {'feast': 'Dominica XIII post Pentecosten', 'rank': 'sd'},
 '08/22/26': {'feast': 'Dominica XIV post Pentecosten', 'rank': 'sd'},
 '08/29/26': {'feast': 'Dominica XV post Pentecosten', 'rank': 'sd'},
 '09/05/26': {'feast': 'Dominica XVI post Pentecosten', 'rank': 'sd'},
 '09/12/26': {'feast': 'Dominica XVII post Pentecosten', 'rank': 'sd'},
 '09/15/26': {'feast': 'Feria IV Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/17/26': {'feast': 'Feria VI Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/18/26': {'feast': 'Sabbato Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/19/26': {'feast': 'Dominica XVIII post Pentecosten', 'rank': 'sd'},
 '09/26/26': {'feast': 'Dominica XIX post Pentecosten', 'rank': 'sd'},
 '10/03/26': {'feast': 'Dominica XX post Pentecosten', 'rank': 'sd'},
 '10/10/26': {'feast': 'Dominica XXI post Pentecosten', 'rank': 'sd'},
 '10/17/26': {'feast': 'Dominica XXII post Pentecosten', 'rank': 'sd'},
 '10/24/26': {'feast': 'Dominica XXIII post Pentecosten', 'rank': 'sd'},
 '10/31/26': {'feast': 'Dominica XXIV post Pentecosten', 'rank': 'sd'},
 '11/07/26': {'feast': 'Dominica XXV post Pentecosten', 'rank': 'sd'},
 '11/14/26': {'feast': 'Dominica XXVI post Pentecosten', 'rank': 'sd'},
 '11/21/26': {'feast': 'Dominica XXVII post Pentecosten', 'rank': 'sd'},
 '12/19/26': {'feast': 'Dominica IV Adventus', 'rank': 'sd2'},
 '12/12/26': {'feast': 'Dominica III Adventus', 'rank': 'sd2'},
 '12/15/26': {'feast': 'Feria IV Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/17/26': {'feast': 'Feria VI Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/18/26': {'feast': 'Sabbato Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/05/26': {'feast': 'Dominica II Adventus', 'rank': 'sd2'},
 '11/28/26': {'feast': 'Dominica I Adventus', 'rank': 'sd2'},
 '12/25/26': {'feast': 'Nativitas DNJC', 'rank': 'd1'},
 '12/30/26': {'feast': 'Dominica Infra Octavam Nativitatis reposit', 'rank': 'sd'},
 '12/26/26': {'feast': 'S Stephani Protomartyris', 'rank': 'd2'},
 '12/27/26': {'feast': 'S Joannis Ap & Ev', 'rank': 'd2'},
 '12/28/26': {'feast': 'Ss Innocentium Mm', 'rank': 'd2'},
 '12/29/26': {'feast': 'S Thomas EM', 'rank': 'd'},
 '12/31/26': {'feast': 'S Sylvestri I PC', 'rank': 'd'},
}
