temporal = {
 '01/01/33': {'feast': 'Circumcisio Domini et Oct Nativitatis', 'rank': 'd2'},
 '01/02/33': {'feast': 'Octava S Stephani Protomartyris', 'rank': 'sp'},
 '01/03/33': {'feast': 'Octava S Joannis Ap & Ev', 'rank': 'sp'},
 '01/04/33': {'feast': 'Octava Ss Innocentium Mm', 'rank': 'sp'},
 '01/02/33': {'feast': 'SS Nominis Jesu', 'rank': 'd2'},
 '02/03/33': {'feast': 'Dominica in Septuagesima', 'rank': 'sd2'},
 '02/10/33': {'feast': 'Dominica in Sexagesima', 'rank': 'sd2'},
 '02/17/33': {'feast': 'Dominica in Quinquagesima', 'rank': 'sd2'},
 '01/06/33': {'feast': 'Epiphania Domini', 'rank': 'd1'},
 '01/07/33': {'feast': 'De die II infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/08/33': {'feast': 'De die III infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/09/33': {'feast': 'De die IV infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/10/33': {'feast': 'De die V infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/11/33': {'feast': 'De die VI infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/12/33': {'feast': 'De die VII infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/13/33': {'feast': 'Octava Epiphaniæ; Dominica I post Epiphaniam', 'rank': 'dm'},
 '01/12/33': {'feast': 'S Familiæ Jesu Mariæ et Joseph', 'rank': 'dm'},
 '01/20/33': {'feast': 'Dominica II post Epiphaniam', 'rank': 'sp'},
 '01/27/33': {'feast': 'Dominica III post Epiphaniam', 'rank': 'sp'},
 '02/20/33': {'feast': 'Dies Cinerum', 'rank': 'sp'},
 '02/20/33': {'feast': 'Feria V post Diem Cinerum', 'rank': 'sp'},
 '02/20/33': {'feast': 'Feria VI post Diem Cinerum', 'rank': 'sp'},
 '02/20/33': {'feast': 'Sabbato post Diem Cinerum', 'rank': 'sp'},
 '02/24/33': {'feast': 'Dominica I in Quadragesima', 'rank': 'sd1'},
 '02/25/33': {'feast': 'Feria II infra Hebd I in Quadragesima', 'rank': 'sp'},
 '02/26/33': {'feast': 'Feria III infra Hebd I in Quadragesima', 'rank': 'sp'},
 '02/27/33': {'feast': 'Feria IV Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '02/28/33': {'feast': 'Feria V infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/01/33': {'feast': 'Feria VI Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/02/33': {'feast': 'Sabbato Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/03/33': {'feast': 'Dominica II in Quadragesima', 'rank': 'sd1'},
 '03/04/33': {'feast': 'Feria II infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/05/33': {'feast': 'Feria III infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/06/33': {'feast': 'Feria IV infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/07/33': {'feast': 'Feria V infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/08/33': {'feast': 'Feria VI infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/09/33': {'feast': 'Sabbato infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/10/33': {'feast': 'Dominica III in Quadragesima', 'rank': 'sd1'},
 '03/11/33': {'feast': 'Feria II infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/12/33': {'feast': 'Feria III infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/13/33': {'feast': 'Feria IV infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/14/33': {'feast': 'Feria V infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/15/33': {'feast': 'Feria VI infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/16/33': {'feast': 'Sabbato infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/17/33': {'feast': 'Dominica IV in Quadragesima', 'rank': 'sd1'},
 '03/18/33': {'feast': 'Feria II infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/19/33': {'feast': 'Feria III infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/20/33': {'feast': 'Feria IV infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/21/33': {'feast': 'Feria V infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/22/33': {'feast': 'Feria VI infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/23/33': {'feast': 'Sabbato infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/24/33': {'feast': 'Dominica de Passione', 'rank': 'sd1'},
 '03/25/33': {'feast': 'Feria II infra Hebd de Passione', 'rank': 'sp'},
 '03/26/33': {'feast': 'Feria III infra Hebd de Passione', 'rank': 'sp'},
 '03/27/33': {'feast': 'Feria IV infra Hebd de Passione', 'rank': 'sp'},
 '03/28/33': {'feast': 'Feria V infra Hebd de Passione', 'rank': 'sp'},
 '03/29/33': {'feast': 'Septem Dolorum BMV', 'rank': 'dm'},
 '03/30/33': {'feast': 'Sabbato infra Hebd de Passione', 'rank': 'sp'},
 '03/31/33': {'feast': 'Dominica in Palmis', 'rank': 'sd1'},
 '04/01/33': {'feast': 'Feria II Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/02/33': {'feast': 'Feria III Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/03/33': {'feast': 'Feria IV Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/04/33': {'feast': 'Feria V in Cœna Domini', 'rank': 'd1'},
 '04/05/33': {'feast': 'Feria VI in Parasceve', 'rank': 'd1'},
 '04/06/33': {'feast': 'Sabbatum Sanctum', 'rank': 'd1'},
 '04/07/33': {'feast': 'Dominica Resurrectionis', 'rank': 'd1'},
 '04/08/33': {'feast': 'Feria II Paschatis', 'rank': 'd1'},
 '04/09/33': {'feast': 'Feria III Paschatis', 'rank': 'd1'},
 '04/10/33': {'feast': 'De die IV infra Oct Paschæ', 'rank': 'sd'},
 '04/11/33': {'feast': 'De die V infra Oct Paschæ', 'rank': 'sd'},
 '04/12/33': {'feast': 'De die VI infra Oct Paschæ', 'rank': 'sd'},
 '04/13/33': {'feast': 'Sabbatum in Albis', 'rank': 'sd'},
 '04/14/33': {'feast': 'Dominica in Albis', 'rank': 'sd'},
 '04/24/33': {'feast': 'Solemnitas S Joseph, Sponsi BMV C et Ecclesiæ Universalis Patroni', 'rank': 'd1'},
 '05/01/33': {'feast': 'Octava Solemnitas S Joseph', 'rank': 'dm'},
 '04/21/33': {'feast': 'Dominica II post Pascha', 'rank': 'sd'},
 '04/28/33': {'feast': 'Dominica III post Pascha', 'rank': 'sd'},
 '05/05/33': {'feast': 'Dominica IV post Pascha', 'rank': 'sd'},
 '05/13/33': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/14/33': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/15/33': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/15/33': {'feast': 'Vigilæ Ascensionis', 'rank': 'sp'},
 '05/16/33': {'feast': 'Ascensio DNJC', 'rank': 'd1'},
 '05/12/33': {'feast': 'Dominica V post Pascha', 'rank': 'sd'},
 '05/18/33': {'feast': 'De II die infra Oct Ascensionis', 'rank': 'sd'},
 '05/20/33': {'feast': 'De IV die infra Oct Ascensionis', 'rank': 'sd'},
 '05/21/33': {'feast': 'De V die infra Oct Ascensionis', 'rank': 'sd'},
 '05/22/33': {'feast': 'De VI die infra Oct Ascensionis', 'rank': 'sd'},
 '05/19/33': {'feast': 'Dominica infra Octavam Ascensionis', 'rank': 'sd'},
 '05/25/33': {'feast': 'Vigilia Pentecostes', 'rank': 'sd'},
 '05/26/33': {'feast': 'Dominica Pentecostes', 'rank': 'd1'},
 '05/18/33': {'feast': 'De II die infra Oct Pentecostes', 'rank': 'd1'},
 '05/19/33': {'feast': 'De III die infra Oct Pentecostes', 'rank': 'd1'},
 '05/20/33': {'feast': 'De IV die infra Oct Pentecostes', 'rank': 'd1'},
 '05/21/33': {'feast': 'De V die infra Oct Pentecostes', 'rank': 'd1'},
 '05/22/33': {'feast': 'De VI die infra Oct Pentecostes', 'rank': 'd1'},
 '05/23/33': {'feast': 'Sabbato die infra Oct Pentecostes', 'rank': 'd1'},
 '05/29/33': {'feast': 'Feria IV Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '05/31/33': {'feast': 'Feria VI Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/01/33': {'feast': 'Sabbato Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/02/33': {'feast': 'Dominica Sanctissimæ Trinitatis', 'rank': 'd1'},
 '06/07/33': {'feast': 'De II die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/08/33': {'feast': 'De III die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/10/33': {'feast': 'De V die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/11/33': {'feast': 'De VI die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/12/33': {'feast': 'De VII die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/06/33': {'feast': 'Sanctissimi Corporis Christi', 'rank': 'd1'},
 '06/13/33': {'feast': 'Octava SSmi Corporis Christi', 'rank': 'dm'},
 '06/09/33': {'feast': 'Dominica II post Pentecosten infra Octavam Corporis Christi', 'rank': 'sd'},
 '06/15/33': {'feast': 'De II die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/17/33': {'feast': 'De IV die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/18/33': {'feast': 'De V die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/19/33': {'feast': 'De VI die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/20/33': {'feast': 'De VII die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/14/33': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'd1'},
 '06/21/33': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'dm'},
 '06/16/33': {'feast': 'Dominica III post Pentecosten infra Octavam SSmi Cordis DNJC', 'rank': 'sd'},
 '06/23/33': {'feast': 'Dominica V post Pentecosten', 'rank': 'sd'},
 '06/30/33': {'feast': 'Dominica VI post Pentecosten', 'rank': 'sd'},
 '07/07/33': {'feast': 'Dominica VII post Pentecosten', 'rank': 'sd'},
 '07/14/33': {'feast': 'Dominica VIII post Pentecosten', 'rank': 'sd'},
 '07/21/33': {'feast': 'Dominica IX post Pentecosten', 'rank': 'sd'},
 '07/28/33': {'feast': 'Dominica X post Pentecosten', 'rank': 'sd'},
 '08/04/33': {'feast': 'Dominica XI post Pentecosten', 'rank': 'sd'},
 '08/11/33': {'feast': 'Dominica XII post Pentecosten', 'rank': 'sd'},
 '08/18/33': {'feast': 'Dominica XIII post Pentecosten', 'rank': 'sd'},
 '08/25/33': {'feast': 'Dominica XIV post Pentecosten', 'rank': 'sd'},
 '09/01/33': {'feast': 'Dominica XV post Pentecosten', 'rank': 'sd'},
 '09/08/33': {'feast': 'Dominica XVI post Pentecosten', 'rank': 'sd'},
 '09/15/33': {'feast': 'Dominica XVII post Pentecosten', 'rank': 'sd'},
 '09/18/33': {'feast': 'Feria IV Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/20/33': {'feast': 'Feria VI Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/21/33': {'feast': 'Sabbato Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/22/33': {'feast': 'Dominica XVIII post Pentecosten', 'rank': 'sd'},
 '09/29/33': {'feast': 'Dominica XIX post Pentecosten', 'rank': 'sd'},
 '10/06/33': {'feast': 'Dominica XX post Pentecosten', 'rank': 'sd'},
 '10/13/33': {'feast': 'Dominica XXI post Pentecosten', 'rank': 'sd'},
 '10/20/33': {'feast': 'Dominica XXII post Pentecosten', 'rank': 'sd'},
 '10/27/33': {'feast': 'Dominica XXIII post Pentecosten', 'rank': 'sd'},
 '11/03/33': {'feast': 'Dominica XXIV post Pentecosten', 'rank': 'sd'},
 '11/10/33': {'feast': 'Dominica XXV post Pentecosten', 'rank': 'sd'},
 '11/17/33': {'feast': 'Dominica XXVI post Pentecosten', 'rank': 'sd'},
 '11/24/33': {'feast': 'Dominica XXVII post Pentecosten', 'rank': 'sd'},
 '12/22/33': {'feast': 'Dominica IV Adventus', 'rank': 'sd2'},
 '12/15/33': {'feast': 'Dominica III Adventus', 'rank': 'sd2'},
 '12/18/33': {'feast': 'Feria IV Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/20/33': {'feast': 'Feria VI Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/21/33': {'feast': 'Sabbato Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/08/33': {'feast': 'Dominica II Adventus', 'rank': 'sd2'},
 '12/01/33': {'feast': 'Dominica I Adventus', 'rank': 'sd2'},
 '12/25/33': {'feast': 'Nativitas DNJC', 'rank': 'd1'},
 '12/29/33': {'feast': 'Dominica Infra Octavam Nativitatis', 'rank': 'sd'},
 '12/30/33': {'feast': 'De VI Die infra Octavam Nativitatis', 'rank': 'sd'},
 '12/26/33': {'feast': 'S Stephani Protomartyris', 'rank': 'd2'},
 '12/27/33': {'feast': 'S Joannis Ap & Ev', 'rank': 'd2'},
 '12/28/33': {'feast': 'Ss Innocentium Mm', 'rank': 'd2'},
 '12/29/33': {'feast': 'S Thomas EM', 'rank': 'd'},
 '12/31/33': {'feast': 'S Sylvestri I PC', 'rank': 'd'},
}
