# frozen_string_literal: true

gem "jekyll"
group :jekyll_plugins do
  gem 'jekyll-sitemap'
  gem 'jekyll-seo-tag'
  gem 'jekyll-autoprefixer', '1.0.1'
end

source "https://rubygems.org"

# gem "rails"

gem "webrick", "~> 1.8"
gem "eventmachine", "~> 1.2.7"
