# COMPLETE: January, February, March, April, December
# todo May, June, July, August, September, October, November

sanctoral = {
    '01/14': {
        'feast': 'S Hilarii Episcopi ECD',
        # according to the accompanying charts -- only 4 digits for now
        'rank': [15, 'd'],
        # commemoration
        'comm2': {
            'S Felix SM': {
                'mass': {
                    'int': 'Lætabitur',
                    'glo': True, 'cre': True,
                    'pre': 'Communis'
                }
            }
        },
        'comm3': '',  # blank if no commemoration
        'office_proper': True,  # else, false
        # for a proper Communicantes: 'et Communicantes de *preface*'
        'mass': {
            'int': 'Missa',
            'glo': True,
            'cre': True,
            'pre': 'Communis'
        },
        # in Vespers 'propers' is for exceptions to a common office (e.g. St Teresa's hymn)
        'vespers': {
            'proper': False,
            'admag': 'O Doctor',
            'propers': {
                'hymn': '',
                'verse': ''
            },
            'oration': 'Deus, qui populo'
        },
    },
    '01/15': {
        'feast': 'S Pauli Primi Eremitæ C',
        'rank': [15, 'd'],
        'comm2': 'S Mauri Abb',
        'comm3': '',
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '01/16': {
        'feast': 'S Marcelli PM',
        'rank': [16.1, 'sd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '01/17': {
        'feast': 'S Antonii Abb',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '01/18': {
        'feast': 'Cathedræ S Petri Ap Romæ',
        'rank': [14, 'dm'],
        'comm2': 'S Pauli Apostoli',
        'comm3': 'S Priscæ VM',
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '01/19': {
        'feast': 'Ss Marii, Marthæ, Audifacis et Abachum Mm',
        'rank': [22, 's'],
        'comm2': 'S Canuti RM',
        'comm3': '',
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'mag': '',
    },
    '01/20': {
        'feast': 'Ss Fabiani P & Sebastiani Mm',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '01/21': {
        'feast': 'S Agnetis VM',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '01/22': {
        'feast': 'Ss Vincentii & Anastasii Mm',
        'rank': [16.1, 'sd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '01/23': {
        'feast': 'S Raymundi de Peñafort C mtv',
        'rank': [16.1, 'sd'],
        'comm2': 'S Emerentianæ VM',
        'comm3': '',
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '01/24': {
        'feast': 'S Timothei EM',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '01/25': {
        'feast': 'Conversio S Pauli Ap',
        'rank': [14, 'dm'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '01/26': {
        'feast': 'S Polycarpi EM',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '01/27': {
        'feast': 'S Joannis Chrysostomi',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '01/28': {
        'feast': 'S Petri Nolasci C mtv',
        'rank': [15, 'd'],
        'comm2': 'S Agnetis VM secundo',
        'comm3': '',
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '01/29': {
        'feast': 'S Francisci Salesii ECD',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '01/30': {
        'feast': 'S Martinæ VM',
        'rank': [16.1, 'sd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '01/31': {
        'feast': 'S Joannis Bosco C',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/01': {
        'feast': 'S Ignatii EM',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Mihi autem', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '02/02': {
        'feast': 'In Purificatione BMV',
        'rank': [10, 'd II cl'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Suscepisimus', 'glo': True, 'cre': True, 'pre': 'de Nativitate'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/03': {
        'feast': 'S Blasii EM',
        'rank': [22, 's'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Sacerdotes Dei', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/04': {
        'feast': 'S Andreæ Corsini EC',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Statuit', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/05': {
        'feast': 'S Agathæ VM',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Gaudeamus', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/06': {
        'feast': 'S Titi EC',
        'rank': [15, 'd'],
        'comm2': 'S Dorotheæ VM',
        'comm3': '',
        'mass': {'int': 'Statuit ei', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/07': {
        'feast': 'S Romualdi Abb',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Os justi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/08': {
        'feast': 'S Joannis de Matha C',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Os justi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/09': {
        'feast': 'S Cyrilli ECD',
        'rank': [15, 'd'],
        'comm2': 'S Apollonia VM',
        'comm3': '',
        'mass': {'int': 'In medio', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/10': {
        'feast': 'S Scholasticæ V',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Dilexisti', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/11': {
        'feast': 'In Apparitione BMV Immaculatæ',
        'rank': [14, 'dm'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Vidi civitatem', 'glo': True, 'cre': True, 'pre': 'de B Mariæ Virg'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/12': {
        'feast': 'Ss Septem Fundatorum Ordinis Servorum BMV C',  # ! see how this is written
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Justi decantaverunt', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/14': {
        'feast': 'S Valentini PM',
        'rank': [22, 's'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'In virtute', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/15': {
        'feast': 'Ss Faustini & Jovitæ',
        'rank': [22, 's'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Salus autem', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/18': {
        'feast': 'S Simeonis EM',
        'rank': [22, 's'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Statuit', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/22': {  # ! need the introit
        'feast': 'In Cathedra S Petri Ap',
        'rank': [14, 'dm'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': '', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/23': {
        'feast': 'S Petri Damiani ECD',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'In medio', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/23.': {
        'leapdate': '02/24',
        'feast': 'In Vigilia S Matthiæ',
        'rank': [19, 'v'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Ego autem', 'glo': False, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/24': {
        'leapdate': '02/25',
        'feast': 'S Matthiæ Ap',
        'rank': [10, 'd II cl'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Mihi autem', 'glo': True, 'cre': True, 'pre': 'de Apostolis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/27': {
        'leapdate': '02/28',
        'feast': 'S Gabrirlis a Virgine Perdolente',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Oculus Dei', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    # START - mostly compiled by Frankter Natera
    '03/04': {
        'feast': 'S Casimiri C',
        'rank': [16.1, 'sd'],
        'comm2': 'S Lucii I PM',
        'comm3': '',
        'mass': {'int': 'Os iusti', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '03/06': {
        'feast': 'Ss Perpetuae et Felicitatiis Mm',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Me expectaverunt', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '03/07': {
        'feast': 'S Thomas De Aquino C',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'In medio ecclesiae', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '03/08': {
        'feast': 'S Ioannis a Deo C',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Os iusti', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '03/09': {
        'feast': 'S Franciscae Romanae Vid',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Cognovi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '03/10': {
        'feast': 'Ss Quadraginta Mm',
        'rank': [16.1, 'sd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Clamaverunt iusti', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '03/12': {
        'feast': 'S Gregorii I Pp CD',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Sacerdotes Dei', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '03/17': {
        'feast': 'S Patricii Ep C',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Statuit', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '03/18': {
        'feast': 'S Cyrilli Ep CD',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'In media ecclesiae', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '03/19': {
        'feast': 'S Joseph Sponsi BMV C',
        'rank': [2, 'd I cl'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Justus ut', 'glo': True, 'cre': True, 'pre': 'De Sancto Ioseph'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '03/21': {
        'feast': 'S Benedicti Abb',
        'rank': [14, 'dm'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Os iusti', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '03/24': {
        'feast': 'S Gabrielis Arch',
        'rank': [14, 'dm'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Benedicite Dominum', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '03/25': {
        'feast': 'In Annuntiatione BMV',
        'rank': [2, 'd I cl'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Vultum tuum', 'glo': True, 'cre': True, 'pre': 'De B Maria Virg'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '03/27': {
        'feast': 'S Ioannis Damasceni CD',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Tenuisti manum', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '03/28': {
        'feast': 'S Ioannis a Capistrano C',
        'rank': [16.1, 'sd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Ego autem', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '04/02': {
        'feast': 'S Francisco de Paula C',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Iustus ut palma', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '04/04': {
        'feast': 'S Isidori CD',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'In medio ecclesiae', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '04/05': {
        'feast': 'S Vincentii Ferrerii C',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Os iusti', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '04/11': {
        'feast': 'S Leonis Pp CD',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'In medio ecclesiae', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '04/13': {
        'feast': 'S Hermenegildi M',
        'rank': [16.1, 'sd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'In virtute', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '04/14': {
        'feast': 'S Iustini M',
        'rank': [15, 'd'],
        'comm2': 'Ss Tiburtio, Valeriano et Maximo Mm',
        'comm3': '',
        'mass': {'int': 'Narraverunt mihi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '04/17': {
        'feast': 'S Aniceti Pp M',
        'rank': [21, 's'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Protexisti me', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '04/21': {
        'feast': 'S Anselmi Ep CD',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'In medio ecclesiae', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },

    '04/22': {
        'feast': 'Ss Soteris et Caii PP Mm',
        'rank': [16.1, 'sd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Sancti tai, Domine', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '04/23': {
        'feast': 'S Georgii M',
        'rank': [16.1, 'sd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Protexisti me', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '04/24': {
        'feast': 'S Fidelis a Sigmaringa',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Protexisti me', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '04/25': {
        'feast': 'S Marci Ev',
        'rank': [10, 'd II cl'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Protexisti me', 'glo': True, 'cre': True, 'pre': 'De Apostolis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '04/26': {
        'feast': 'Ss Cleti et Marcellini PP Mm',
        'rank': [16.1, 'sd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Sancti tai, Domine', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '04/27': {
        'feast': 'S Petri Canisii CD',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'In medio ecclesiae', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    # END   - mostly compiled by Frankter Natera
    '10/01': {
        'feast': 'S Remigii EC',
        'rank': [21, 's'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Statuit', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/02': {
        'feast': 'Ss Angelorum Custodum',
        'rank': [14, 'dm'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Benedicite', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/03': {
    'feast': 'S Teresiæ a Jesu Infante V',
    'rank': [15, 'd'],
    'comm2': '',
    'comm3': '',
    'mass': {'int': 'Veni de Libano', 'glo': True, 'cre': False, 'pre': 'Communis'},
    'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
},
    '10/04': {
        'feast': 'S Francisci C',
        'rank': [14, 'dm'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Mihi autem', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/05': {
        'feast': 'Ss Placidi & Sociorum Mm',
        'rank': [21, 's'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Salus autem', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/06': {
    'feast': 'S Brunonis C',
    'rank': [15, 'd'],
    'comm2': '',
    'comm3': '',
    'mass': {'int': 'Os justi', 'glo': True, 'cre': False, 'pre': 'Communis'},
    'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
},
    '10/07': {
        'feast': 'Sacratissimi Rosarii BMV',
        'rank': [10, 'd II cl'],
        'comm2': 'S Marco PC',
        'comm3': 'Ss Sergio, Baccho, Marcello & Apulejo MM',
        'mass': {'int': 'Gaudeamus', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/08': {
        'feast': 'S Birgittæ Vid',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Cognovi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/09': {
        'feast': 'S Joannis Leonardi C',
        'rank': [15, 'd'],
        'comm2': 'Ss Dionysii E, Rustici & Eleutherii Mm',
        'comm3': '',
        'mass': {'int': 'In sermonibus', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/10': {
        'feast': 'S Francisci Borgiæ C',
        'rank': [16.1, 'sd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Os justi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/11': {
        'feast': 'In Maternitate BMV',
        'rank': [10, 'd II cl'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Ecce Virgo', 'glo': True, 'cre': True, 'pre': 'de BMV'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/13': {
        'feast': 'S Eduardi Regis C',
        'rank': [16.1, 'sd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Os justi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/14': {
        'feast': 'S Callisti I PM',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Si diligis me', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/15': {
        'feast': 'S Teresiæ V',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Dilexisti', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/16': {
        'feast': 'S Hedwigis Vid',
        'rank': [16.1, 'sd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Cognovi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/17': {
        'feast': 'S Margaritæ Mariæ Alacoque V',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Sub unbra', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/18': {
        'feast': 'S Lucæ Ev',
        'rank': [10, 'd II cl'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Mihi autem', 'glo': True, 'cre': True, 'pre': 'de Apostolis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/19': {
    'feast': 'S Petri Alcantara C',
    'rank': [15, 'd'],
    'comm2': '',
    'comm3': '',
    'mass': {'int': 'Justus ut palma', 'glo': True, 'cre': False, 'pre': 'Communis'},
    'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
},
    '10/20': {
        'feast': 'S Joannis Cantii C',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Miseratio', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/21': {
    'feast': 'S Hilarionis Abb',
    'rank': [21, 's'],
    'comm2': 'Ss Ursula & Sociabus VM',
    'comm3': '',
    'mass': {'int': 'Os justi', 'glo': True, 'cre': False, 'pre': 'Communis'},
    'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
},
    '10/24': {
        'feast': 'S Raphaelis Arch',
        'rank': [14, 'dm'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Benedicite', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/25': {
    'feast': 'Ss Chrysanthi & Dariæ Mm',
    'rank': [21, 's'],
    'comm2': '',
    'comm3': '',
    'mass': {'int': 'Intret', 'glo': True, 'cre': False, 'pre': 'Communis'},
    'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
},
'10/26': {
    'feast': 'S Evaristi PM',
    'rank': [21, 's'],
    'comm2': '',
    'comm3': '',
    'mass': {'int': 'Si diligis mei', 'glo': True, 'cre': False, 'pre': 'Communis'},
    'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
},
'10/27': {
    'feast': 'In Vigilia Ss Simonis & Judæ App',
    'rank': [18, 'v'],
    'comm2': '',
    'comm3': '',
    'mass': {'int': 'Intret', 'glo': False, 'cre': False, 'pre': 'Communis'},
    'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
},
'10/28': {
    'feast': 'Ss Simonis & Judæ App',
    'rank': [10, 'd II cl'],
    'comm2': '',
    'comm3': '',
    'mass': {'int': 'Mihi autem', 'glo': True, 'cre': True, 'pre': 'de Apostolis'},
    'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
},
'10/31': {
    'feast': 'In Vigilia Omnium Sanctorum',
    'rank': [18, 'v'],
    'comm2': '',
    'comm3': '',
    'mass': {'int': 'Judicant', 'glo': False, 'cre': False, 'pre': 'Communis'},
    'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
},

    '11/01': {
        'feast': 'In Festo Omnium Sanctorum',
        'rank': [2, 'd I cl cum Oct communi'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Gaudeamus', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/02': {
        'feast': 'In Commemoratione Omnium Fidelium Defunctorum',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {
            'Ad Primam Missam': {'int': 'Requiem', 'glo': False, 'seq': 'Dies Iræ', 'cre': False, 'pre': 'Defunctorum'},
            'Ad Secundam Missam': {'int': 'Requiem', 'glo': False, 'seq': 'Dies Iræ', 'cre': False, 'pre': 'Defunctorum'},
            'Ad Tertiam Missam': {'int': 'Requiem', 'glo': False, 'seq': 'Dies Iræ', 'cre': False, 'pre': 'Defunctorum'},
        },
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/04': {
        'feast': 'S Caroli EC',
        'rank': [15, 'd'],
        'comm2': 'Ss Vitale & Agricola Mm',
        'comm3': '',
        'mass': {'int': 'Statuit ei', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/08': {
        'feast': 'Ss Quatuor Coronatis Mm',
        'rank': [16.1, 'sd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Intret in conspecu', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/09': {
        'feast': 'In Dedicatione Archibasilicæ Ssmi Salvatoris',
        'rank': [10, 'd II cl'],
        'comm2': {'private': True, 'com': 'S Theodoro M'},
        'comm3': '',
        'mass': {'int': 'Terribilis', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/10': {
        'feast': 'S Andreæ Avellini C',
        'rank': [15, 'd'],
        'comm2': 'Ss Tryphone, Respicio & Nympha VM',
        'comm3': '',
        'mass': {'int': 'Os justi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/11': {
        'feast': 'S Martini  EC',
        'rank': [15, 'd'],
        'comm2': 'S Menna M',
        'comm3': '',
        'mass': {'int': 'Statuit ei', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/12': {
        'feast': 'S Martini I PM',
        'rank': [16.1, 'sd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Si diligis me', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/13': {
        'feast': 'S Didaci C',
        'rank': [16.1, 'sd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Justus', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/14': {
        'feast': 'Josaphat EM',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Gaudeamus', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/15': {
        'feast': 'S Alberti Magni ECD',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'In medio', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/16': {
        'feast': 'S Gertrudis V',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Dilexisti', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },  # ! finish November
    '11/17': {
        'feast': 'S Gregorii Thaumaturgi EC',
        'rank': [16.1, 'sd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Statuit', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/18': {
        'feast': 'In Dedicatione Basilicarum Ss Petri & Pauli App',
        'rank': [14, 'dm'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Terribilis', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/19': {
        'feast': 'S Elisabeth Vid',
        'rank': [15, 'd'],
        'comm2': 'S Pontiano PM',
        'comm3': '',
        'mass': {'int': 'Cognovi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/20': {
        'feast': 'S Felicis de Valois C',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Justus', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/21': {
        'feast': 'In Præsentatione BMV',
        'rank': [14, 'dm'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Salve', 'glo': True, 'cre': True, 'pre': 'de BMV'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/22': {
        'feast': 'S Cæciliæ VM',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Loquebar', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/23': {
        'feast': 'S Clementis I PM',
        'rank': [15, 'd'],
        'comm2': 'S Felicitate M',
        'comm3': '',
        'mass': {'int': 'Dicit Dóminus', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/24': {
        'feast': 'S Joannis de Cruce CD',
        'rank': [15, 'd'],
        'comm2': 'S Chrysogono M',
        'comm3': '',
        'mass': {'int': 'In medio', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/25': {
        'feast': 'S Catharinæ VM',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Loquebar', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/26': {
        'feast': 'S Sylvestri Abb',
        'rank': [15, 'd'],
        'comm2': 'S Petro Alexandrino EM',
        'comm3': '',
        'mass': {'int': 'Os justi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/29': {
        'feast': 'In Vigilia S Andreæ Ap',
        'rank': [18, 'v'],
        'comm2': 'S Saturnino M',
        'comm3': '',
        'mass': {'int': 'Dominus secus', 'glo': False, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/30': {
        'feast': 'S Andreæ Ap',
        'rank': [10, 'd II cl'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Mihi autem', 'glo': True, 'cre': True, 'pre': 'de Apostolis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '12/02': {
        'feast': 'S Bibianæ VM',
        'rank': [16.1, 'sd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Me expectaverunt', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '12/03': {
        'feast': 'S Francisci Xaverii C',
        'rank': [14, 'dm'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Loquebar', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '12/04': {
        'feast': 'S Petri Chrysologi ECD',
        'rank': [15, 'd'],
        'comm2': 'S Barbara VM',
        'comm3': '',
        'mass': {'int': 'In medio', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '12/05': {
        'feast': 'S Sabba Abb',
        'rank': [21, 's'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Os justi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '12/06': {
        'feast': 'S Nicolai EC',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Statuit ei', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '12/07': {
        'feast': 'S Ambrosii ECD',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'In medio', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '12/07.': {
        'feast': 'In Vigilia Conceptionis Immaculatæ BMV',
        'rank': [18, 'v'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Venite, audite', 'glo': False, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    #! add a flag that makes all the days within the octaves of a given day after the calendar is built.
    '12/08': {
        'feast': 'In Conceptione Immaculata BMV',
        'rank': [2, 'd I cl cum Oct communi'],
        'octave': 4,
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Gaudens gaudebo', 'glo': True, 'cre': True, 'pre': 'de BMV'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '12/10': {
        'feast': 'S Melchide PM',
        'rank': [21, 's'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Si diligis me', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '12/11': {
        'feast': 'S Damasi I PC',
        'rank': [16.1, 'sd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Si diligis me', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '12/13': {
        'feast': 'S Luciæ VM',
        'rank': [15, 'd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Dilexisti', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '12/16': {
        'feast': 'S Eusebii EM',
        'rank': [16.1, 'sd'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Sacerdotes Dei', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '12/20': {
        'feast': 'In Vigilia S Thomæ Ap',
        'rank': [18, 'v'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Ego autem', 'glo': False, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '12/21': {
        'feast': 'S Thomæ Ap',
        'rank': [10, 'd II cl'],
        'comm2': '',
        'comm3': '',
        'mass': {'int': 'Mihi autem', 'glo': True, 'cre': True, 'pre': 'de Apostolis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
}
"""
'10/01': {
    'feast': '',
    'rank': [],
    'comm2': '',
    'comm3': '',
    'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'},
    'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
},
 """
