# COMPLETE: January, February, March, April, December
# todo May, June, July, August, September, October, November

sanctoral = {
    '01/14': {
        'feast': 'S Hilarii Episcopi ECD',
        'rank': [15, 'd'],
        'comm2': {'feast': 'S Felix SM', 'mass': {'int': 'Lætabitur', 'glo': True, 'cre': True, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'office_proper': True,
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': 'O Doctor', 'propers': {'hymn': '', 'verse': ''},
                    'oration': 'Deus, qui populo'
                    },
    },
    '01/15': {
        'feast': 'S Pauli Primi Eremitæ C',
        'rank': [15, 'd'],
        'comm2': {'feast': 'S Mauri Abb', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '01/16': {
        'feast': 'S Marcelli PM',
        'rank': [16.1, 'sd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '01/17': {
        'feast': 'S Antonii Abb',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '01/18': {
        'feast': 'Cathedræ S Petri Ap Romæ',
        'rank': [14, 'dm'],
        'comm2': {'feast': 'S Pauli Apostoli', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': 'S Priscæ VM', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '01/19': {
        'feast': 'Ss Marii, Marthæ, Audifacis et Abachum Mm',
        'rank': [22, 's'],
        'comm2': {'feast': 'S Canuti RM', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'mag': '',
    },
    '01/20': {
        'feast': 'Ss Fabiani P & Sebastiani Mm',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '01/21': {
        'feast': 'S Agnetis VM',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '01/22': {
        'feast': 'Ss Vincentii & Anastasii Mm',
        'rank': [16.1, 'sd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '01/23': {
        'feast': 'S Raymundi de Peñafort C mtv',
        'rank': [16.1, 'sd'],
        'comm2': {'feast': 'S Emerentianæ VM', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '01/24': {
        'feast': 'S Timothei EM',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '01/25': {
        'feast': 'Conversio S Pauli Ap',
        'rank': [14, 'dm'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '01/26': {
        'feast': 'S Polycarpi EM',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '01/27': {
        'feast': 'S Joannis Chrysostomi',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '01/28': {
        'feast': 'S Petri Nolasci C mtv',
        'rank': [15, 'd'],
        'comm2': {'feast': 'S Agnetis VM secundo', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '01/29': {
        'feast': 'S Francisci Salesii ECD',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '01/30': {
        'feast': 'S Martinæ VM',
        'rank': [16.1, 'sd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '01/31': {
        'feast': 'S Joannis Bosco C',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/01': {
        'feast': 'S Ignatii EM',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Mihi autem', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '02/02': {
        'feast': 'In Purificatione BMV',
        'rank': [10, 'd II cl'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Suscepisimus', 'glo': True, 'cre': True, 'pre': 'de Nativitate'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/03': {
        'feast': 'S Blasii EM',
        'rank': [22, 's'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Sacerdotes Dei', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/04': {
        'feast': 'S Andreæ Corsini EC',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Statuit', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/05': {
        'feast': 'S Agathæ VM',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Gaudeamus', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/06': {
        'feast': 'S Titi EC',
        'rank': [15, 'd'],
        'comm2': {'feast': 'S Dorotheæ VM', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Statuit ei', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/07': {
        'feast': 'S Romualdi Abb',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Os justi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/08': {
        'feast': 'S Joannis de Matha C',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Os justi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/09': {
        'feast': 'S Cyrilli ECD',
        'rank': [15, 'd'],
        'comm2': {'feast': 'S Apollonia VM', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'In medio', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/10': {
        'feast': 'S Scholasticæ V',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Dilexisti', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/11': {
        'feast': 'In Apparitione BMV Immaculatæ',
        'rank': [14, 'dm'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Vidi civitatem', 'glo': True, 'cre': True, 'pre': 'de B Mariæ Virg'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/12': {
        'feast': 'Ss Septem Fundatorum Ordinis Servorum BMV C',  # ! see how this is written
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Justi decantaverunt', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/14': {
        'feast': 'S Valentini PM',
        'rank': [22, 's'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'In virtute', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/15': {
        'feast': 'Ss Faustini & Jovitæ',
        'rank': [22, 's'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Salus autem', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/18': {
        'feast': 'S Simeonis EM',
        'rank': [22, 's'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Statuit', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/22': {  # ! need the introit
        'feast': 'In Cathedra S Petri Ap',
        'rank': [14, 'dm'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': '', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/23': {
        'feast': 'S Petri Damiani ECD',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'In medio', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/23.': {
        'leapdate': '02/24',
        'feast': 'In Vigilia S Matthiæ',
        'rank': [19, 'v'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Ego autem', 'glo': False, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/24': {
        'leapdate': '02/25',
        'feast': 'S Matthiæ Ap',
        'rank': [10, 'd II cl'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Mihi autem', 'glo': True, 'cre': True, 'pre': 'de Apostolis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '02/27': {
        'leapdate': '02/28',
        'feast': 'S Gabrirlis a Virgine Perdolente',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Oculus Dei', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    # START - mostly compiled by Frankter Natera
    '03/04': {
        'feast': 'S Casimiri C',
        'rank': [16.1, 'sd'],
        'comm2': {'feast': 'S Lucii I PM', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Os iusti', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '03/06': {
        'feast': 'Ss Perpetuae et Felicitatiis Mm',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Me expectaverunt', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '03/07': {
        'feast': 'S Thomas De Aquino C',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'In medio ecclesiae', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '03/08': {
        'feast': 'S Ioannis a Deo C',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Os iusti', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '03/09': {
        'feast': 'S Franciscae Romanae Vid',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Cognovi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '03/10': {
        'feast': 'Ss Quadraginta Mm',
        'rank': [16.1, 'sd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Clamaverunt iusti', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '03/12': {
        'feast': 'S Gregorii I Pp CD',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Sacerdotes Dei', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '03/17': {
        'feast': 'S Patricii Ep C',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Statuit', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '03/18': {
        'feast': 'S Cyrilli Ep CD',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'In media ecclesiae', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '03/19': {
        'feast': 'S Joseph Sponsi BMV C',
        'rank': [2, 'd I cl'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Justus ut', 'glo': True, 'cre': True, 'pre': 'De Sancto Ioseph'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '03/21': {
        'feast': 'S Benedicti Abb',
        'rank': [14, 'dm'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Os iusti', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '03/24': {
        'feast': 'S Gabrielis Arch',
        'rank': [14, 'dm'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Benedicite Dominum', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '03/25': {
        'feast': 'In Annuntiatione BMV',
        'rank': [2, 'd I cl'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Vultum tuum', 'glo': True, 'cre': True, 'pre': 'De B Maria Virg'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '03/27': {
        'feast': 'S Ioannis Damasceni CD',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Tenuisti manum', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '03/28': {
        'feast': 'S Ioannis a Capistrano C',
        'rank': [16.1, 'sd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Ego autem', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '04/02': {
        'feast': 'S Francisco de Paula C',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Iustus ut palma', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '04/04': {
        'feast': 'S Isidori CD',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'In medio ecclesiae', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '04/05': {
        'feast': 'S Vincentii Ferrerii C',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Os iusti', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '04/11': {
        'feast': 'S Leonis Pp CD',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'In medio ecclesiae', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '04/13': {
        'feast': 'S Hermenegildi M',
        'rank': [16.1, 'sd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'In virtute', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '04/14': {
        'feast': 'S Iustini M',
        'rank': [15, 'd'],
        'comm2': {'feast': 'Ss Tiburtio, Valeriano et Maximo Mm', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Narraverunt mihi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '04/17': {
        'feast': 'S Aniceti Pp M',
        'rank': [21, 's'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Protexisti me', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '04/21': {
        'feast': 'S Anselmi Ep CD',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'In medio ecclesiae', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },

    '04/22': {
        'feast': 'Ss Soteris et Caii PP Mm',
        'rank': [16.1, 'sd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Sancti tai, Domine', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '04/23': {
        'feast': 'S Georgii M',
        'rank': [16.1, 'sd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Protexisti me', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '04/24': {
        'feast': 'S Fidelis a Sigmaringa',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Protexisti me', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '04/25': {
        'feast': 'S Marci Ev',
        'rank': [10, 'd II cl'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Protexisti me', 'glo': True, 'cre': True, 'pre': 'De Apostolis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '04/26': {
        'feast': 'Ss Cleti et Marcellini PP Mm',
        'rank': [16.1, 'sd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Sancti tai, Domine', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    '04/27': {
        'feast': 'S Petri Canisii CD',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'In medio ecclesiae', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}
    },
    # END   - mostly compiled by Frankter Natera
    '08/01': {
        'feast': 'S Petri Ap, ad Vincula',
        'rank': [14, 'dm'],
        'comm2': {'feast': 'S Pauli Ap', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': 'Ss Machabæis Mm', 'mass': {'int': 'Clamaverunt', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Nunc scio vere', 'glo': True, 'cre': True, 'pre': 'de Apostolis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '08/02': {
        'feast': 's Alphonso Mariæ de Ligourio ECD',
        'rank': [15, 'd'],
        'comm2': {'feast': 'S Stephano PM', 'mass': {'int': 'Si diligis me', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Spiritus Domini', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '08/03': {
        'feast': 'In Inventione S Stephani Protomartyris',
        'rank': [16.1, 'sd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Sederunt', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '08/04': {
        'feast': 'S Dominici C',
        'rank': [14, 'dm'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Os justi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '08/05': {
        'feast': 'In Dedicatione Mariæ ad Nives',
        'rank': [14, 'dm'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Salve', 'glo': True, 'cre': True, 'pre': 'De BMV'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '08/06': {
        'feast': 'In Transfiguratione DNJC',
        'rank': [11, 'dm'],
        'comm2': {'feast': 'Ss Xysto P, Felicissimo & Agapito Mm', 'mass': {'int': 'Sapientiam', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Illuxerunt', 'glo': True, 'cre': True, 'pre': 'de Nativitate'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '08/07': {
        'feast': 'S Cajetani C',
        'rank': [15, 'd'],
        'comm2': {'feast': 'S Donato EM', 'mass': {'int': 'Sacerdotes Dei', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Os justi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '08/08': {
        'feast': 'Ss Cyriaci, Largi & Smaragdi Mm',
        'rank': [16.1, 'sd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Timete Dominum', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '08/09': {
        'feast': 'S Joannis Mariæ Vianney C',
        'rank': [15, 'd'],
        'comm2': {'feast': 'Vigilia S Laurentii M', 'mass': {'int': 'Dispersi', 'glo': False, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': 'S Romano M', 'mass': {'int': 'Lætabitur', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Os justi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '08/10': {
        'feast': 'S Laurentii M',
        'rank': [10, 'd II cl'],  # ? Octave
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Confessio', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '08/11': {
        'feast': 'Ss Tiburtii & Susannæ VM',
        'rank': [21, 's'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Salus autem', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '08/12': {
        'feast': 'S Claræ V',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Dilexisti', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '08/13': {
        'feast': 'Ss Hippolyti & Cassiani Mm',
        'rank': [21, 's'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Salus autem', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '08/14': {
        'feast': 'In Vigilia Assumptionis BMV',
        'rank': [18, 'v'],
        'comm2': {'feast': 'S Eusebio C', 'mass': {'int': 'Justus', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Vultum tuum', 'glo': False, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '08/15': {
        'feast': 'In Assumptione BMV',
        'rank': [2, 'd I cl cum Oct communi'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Signum magnum', 'glo': True, 'cre': True, 'pre': 'de BMV'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '08/16': {
        'feast': 'S Joachim Patris BMV',
        'rank': [10, 'd II cl'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'dispersit', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '08/17': {
        'feast': 'S Hyacinthi C',
        'rank': [15, 'd'],
        'comm2': {'feast': 'Octava S Laurentii M', 'mass': {'int': 'Probasti', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Os justi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '08/18': {
        'feast': 'S Agapito M',
        'rank': [21, 's'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Lætabitur', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '08/19': {
        'feast': 'S Joannis Eudes C',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Os justi', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '08/20': {
        'feast': 'S Bernardi AbbD',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'In medio', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '08/21': {
        'feast': 'S Joannæ Franciscæ Fremiot de Chantal Vid',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Cognovit', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '08/22': {
        'feast': 'In Festo Immaculati Cordis BMV',
        'rank': [10, 'd II cl'],
        'comm2': {'feast': 'Ss Timotheo, Hippolyto & Symphoriano Mm', 'mass': {'int': 'Salus autem', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Adeamus', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '08/23': {
        'feast': 'In Vigilia S Bartholomæi Ap',
        'rank': [18, 'v'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Ego autem', 'glo': False, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '08/24': {
        'feast': 'S Bartholomæi Ap',
        'rank': [10, 'd II cl'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Mihi autem', 'glo': True, 'cre': True, 'pre': 'de Apostolis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '08/25': {
        'feast': 'S Ludovici RC',
        'rank': [16.1, 'sd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Os justi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '08/26': {
        'feast': 'S Zephrini PM',
        'rank': [16.1, 'sd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Si diligis me', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '08/27': {
        'feast': 'S Josephi Calasantii C',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Venite, filii', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '08/28': {
        'feast': 'S Augustini ECD',
        'rank': [15, 'd'],
        'comm2': {'feast': 'S Hermete M', 'mass': {'int': 'Lætabitur', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'In medio', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '08/29': {
        'feast': 'In Decollatione S Joannis Baptistæ',
        'rank': [14, 'dm'],
        'comm2': {'feast': 'S Sabina M', 'mass': {'int': 'Me expectaverunt', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Loquebar', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '08/30': {
        'feast': 'S Rosæ a S Maria V',
        'rank': [15, 'd'],
        'comm2': {'feast': 'Ss Felice & Adaucto Mm', 'mass': {'int': 'Sapientiam', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Dilexisti', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '08/31': {
        'feast': 'S Raymundi Nonnati C',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Os justi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '09/01': {
        'feast': 'S Ægidii Abb',
        'rank': [21, 's'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Os justi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '09/02': {
        'feast': 'S Stephani Regis C',
        'rank': [16.1, 'sd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Os justi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '09/05': {
        'feast': 'S Laurentii Justiniani EC',
        'rank': [16.1, 'sd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Statuit ei', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '09/08': {
        'feast': 'In Nativitate BMV',
        'rank': [10, 'd II cl'],
        'comm2': {'feast': 'S Hadriano M', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Salve, sancta Parens', 'glo': True, 'cre': True, 'pre': 'de BMV'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '09/09': {
        'feast': 'S Gorgonii M',
        'rank': [21, 's'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Lætabitur', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '09/10': {
        'feast': 'S Nicolai de Tolentino C',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Justus', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '09/11': {
        'feast': 'Ss Proti & Hycinthi Mm',
        'rank': [21, 's'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Salus autem', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '09/12': {
        'feast': 'Ssmi Nominis Mariæ',
        'rank': [14, 'dm'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Vultum tuum', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '09/14': {
        'feast': 'in Exaltatione S Cruce',
        'rank': [14, 'dm'],  # ! check this one -- is it of Our Lord?
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Mos autem', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '09/15': {
        'feast': 'Septem Dolorum BMV',
        'rank': [10, 'd II cl'],
        'comm2': {'feast': 'S Nicomede M', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Stabant', 'glo': True, 'seq': 'Stabat Mater', 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '09/16': {
        'feast': 'Ss Cornelii P & Cypriani E Mm',
        'rank': [16.1, 'sd'],
        'comm2': {'feast': 'Ss Euphemia V, Lucia & Geminiano Mm', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Intret', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '09/17': {
        'feast': 'In Impressione Ss Stigmatum S Francisci C',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Mihi autem', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '09/18': {
        'feast': 'S Joseph a Cupertino C',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Dilectio', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '09/20': {
        'feast': 'Ss Eustachii & Soc Mm',
        'rank': [15, 'd'],
        'comm2': {'feast': 'In Vigilia S Matthæi ApEv', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Sapientiam', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '09/21': {
        'feast': 'S Matthæi ApEv',
        'rank': [20, 'd II cl'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Os justi', 'glo': True, 'cre': True, 'pre': 'de Apostolis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '09/22': {
        'feast': 'S Thomæ de Villanova EC',
        'rank': [15, 'd'],
        'comm2': {'feast': 'Ss Mauritio & Soc Mm', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Statuit', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '09/23': {
        'feast': 'S Lini',
        'rank': [16.1, 'sd'],
        'comm2': {'feast': 'S Thecla VM', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Si diligis me', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '09/24': {
        'feast': 'BMV de Merdece',
        'rank': [14, 'dm'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Salve', 'glo': True, 'cre': True, 'pre': 'de BMV'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '09/26': {
        'feast': 'Ss Cypriani & Justinæ Mm',
        'rank': [21, 's'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Salus autem', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '09/27': {
        'feast': 'Ss Cosmæ & Damiani Mm',
        'rank': [21, 's'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Sapientiam', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '09/28': {
        'feast': 'S Wenceslau Ducis M',
        'rank': [16.1, 'sd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'In virtute', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '09/29': {
        'feast': 'In Dedicatione S Michaelis Arch',
        'rank': [2, 'd I cl'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Benedicite', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '09/30': {
        'feast': 'S Hieronymi SCD',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'In medio', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/01': {
        'feast': 'S Remigii EC',
        'rank': [21, 's'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Statuit', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/02': {
        'feast': 'Ss Angelorum Custodum',
        'rank': [14, 'dm'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Benedicite', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/03': {
        'feast': 'S Teresiæ a Jesu Infante V',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Veni de Libano', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/04': {
        'feast': 'S Francisci C',
        'rank': [14, 'dm'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Mihi autem', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/05': {
        'feast': 'Ss Placidi & Sociorum Mm',
        'rank': [21, 's'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Salus autem', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/06': {
        'feast': 'S Brunonis C',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Os justi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/07': {
        'feast': 'Sacratissimi Rosarii BMV',
        'rank': [10, 'd II cl'],
        'comm2': {'feast': 'S Marco PC', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': 'Ss Sergio, Baccho, Marcello & Apulejo MM', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Gaudeamus', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/08': {
        'feast': 'S Birgittæ Vid',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Cognovi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/09': {
        'feast': 'S Joannis Leonardi C',
        'rank': [15, 'd'],
        'comm2': {'feast': 'Ss Dionysii E, Rustici & Eleutherii Mm', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'In sermonibus', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/10': {
        'feast': 'S Francisci Borgiæ C',
        'rank': [16.1, 'sd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Os justi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/11': {
        'feast': 'In Maternitate BMV',
        'rank': [10, 'd II cl'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Ecce Virgo', 'glo': True, 'cre': True, 'pre': 'de BMV'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/13': {
        'feast': 'S Eduardi Regis C',
        'rank': [16.1, 'sd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Os justi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/14': {
        'feast': 'S Callisti I PM',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Si diligis me', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/15': {
        'feast': 'S Teresiæ V',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Dilexisti', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/16': {
        'feast': 'S Hedwigis Vid',
        'rank': [16.1, 'sd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Cognovi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/17': {
        'feast': 'S Margaritæ Mariæ Alacoque V',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Sub unbra', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/18': {
        'feast': 'S Lucæ Ev',
        'rank': [10, 'd II cl'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Mihi autem', 'glo': True, 'cre': True, 'pre': 'de Apostolis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/19': {
        'feast': 'S Petri Alcantara C',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Justus ut palma', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/20': {
        'feast': 'S Joannis Cantii C',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Miseratio', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/21': {
        'feast': 'S Hilarionis Abb',
        'rank': [21, 's'],
        'comm2': {'feast': 'Ss Ursula & Sociabus VM', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Os justi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/24': {
        'feast': 'S Raphaelis Arch',
        'rank': [14, 'dm'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Benedicite', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/25': {
        'feast': 'Ss Chrysanthi & Dariæ Mm',
        'rank': [21, 's'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Intret', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/26': {
        'feast': 'S Evaristi PM',
        'rank': [21, 's'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Si diligis mei', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/27': {
        'feast': 'In Vigilia Ss Simonis & Judæ App',
        'rank': [18, 'v'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Intret', 'glo': False, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/28': {
        'feast': 'Ss Simonis & Judæ App',
        'rank': [10, 'd II cl'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Mihi autem', 'glo': True, 'cre': True, 'pre': 'de Apostolis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '10/31': {
        'feast': 'In Vigilia Omnium Sanctorum',
        'rank': [18, 'v'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Judicant', 'glo': False, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },

    '11/01': {
        'feast': 'In Festo Omnium Sanctorum',
        'rank': [2, 'd I cl cum Oct communi'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Gaudeamus', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/02': {
        'feast': 'In Commemoratione Omnium Fidelium Defunctorum',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {
            'Ad Primam Missam': {'int': 'Requiem', 'glo': False, 'seq': 'Dies Iræ', 'cre': False, 'pre': 'Defunctorum'},
            'Ad Secundam Missam': {'int': 'Requiem', 'glo': False, 'seq': 'Dies Iræ', 'cre': False, 'pre': 'Defunctorum'},
            'Ad Tertiam Missam': {'int': 'Requiem', 'glo': False, 'seq': 'Dies Iræ', 'cre': False, 'pre': 'Defunctorum'},
        },
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/04': {
        'feast': 'S Caroli EC',
        'rank': [15, 'd'],
        'comm2': {'feast': 'Ss Vitale & Agricola Mm', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Statuit ei', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/08': {
        'feast': 'Ss Quatuor Coronatis Mm',
        'rank': [16.1, 'sd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Intret in conspecu', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/09': {
        'feast': 'In Dedicatione Archibasilicæ Ssmi Salvatoris',
        'rank': [10, 'd II cl'],
        'comm2': {'feast': 'S Theodoro M', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Terribilis', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/10': {
        'feast': 'S Andreæ Avellini C',
        'rank': [15, 'd'],
        'comm2': {'feast': 'Ss Tryphone, Respicio & Nympha VM', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Os justi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/11': {
        'feast': 'S Martini  EC',
        'rank': [15, 'd'],
        'comm2': {'feast': 'S Menna M', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Statuit ei', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/12': {
        'feast': 'S Martini I PM',
        'rank': [16.1, 'sd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Si diligis me', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/13': {
        'feast': 'S Didaci C',
        'rank': [16.1, 'sd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Justus', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/14': {
        'feast': 'Josaphat EM',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Gaudeamus', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/15': {
        'feast': 'S Alberti Magni ECD',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'In medio', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/16': {
        'feast': 'S Gertrudis V',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Dilexisti', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },  # ! finish November
    '11/17': {
        'feast': 'S Gregorii Thaumaturgi EC',
        'rank': [16.1, 'sd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Statuit', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/18': {
        'feast': 'In Dedicatione Basilicarum Ss Petri & Pauli App',
        'rank': [14, 'dm'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Terribilis', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/19': {
        'feast': 'S Elisabeth Vid',
        'rank': [15, 'd'],
        'comm2': {'feast': 'S Pontiano PM', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Cognovi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/20': {
        'feast': 'S Felicis de Valois C',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Justus', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/21': {
        'feast': 'In Præsentatione BMV',
        'rank': [14, 'dm'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Salve', 'glo': True, 'cre': True, 'pre': 'de BMV'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/22': {
        'feast': 'S Cæciliæ VM',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Loquebar', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/23': {
        'feast': 'S Clementis I PM',
        'rank': [15, 'd'],
        'comm2': {'feast': 'S Felicitate M', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Dicit Dóminus', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/24': {
        'feast': 'S Joannis de Cruce CD',
        'rank': [15, 'd'],
        'comm2': {'feast': 'S Chrysogono M', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'In medio', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/25': {
        'feast': 'S Catharinæ VM',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Loquebar', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/26': {
        'feast': 'S Sylvestri Abb',
        'rank': [15, 'd'],
        'comm2': {'feast': 'S Petro Alexandrino EM', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Os justi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/29': {
        'feast': 'In Vigilia S Andreæ Ap',
        'rank': [18, 'v'],
        'comm2': {'feast': 'S Saturnino M', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Dominus secus', 'glo': False, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '11/30': {
        'feast': 'S Andreæ Ap',
        'rank': [10, 'd II cl'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Mihi autem', 'glo': True, 'cre': True, 'pre': 'de Apostolis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '12/02': {
        'feast': 'S Bibianæ VM',
        'rank': [16.1, 'sd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Me expectaverunt', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '12/03': {
        'feast': 'S Francisci Xaverii C',
        'rank': [14, 'dm'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Loquebar', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '12/04': {
        'feast': 'S Petri Chrysologi ECD',
        'rank': [15, 'd'],
        'comm2': {'feast': 'S Barbara VM', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'In medio', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '12/05': {
        'feast': 'S Sabba Abb',
        'rank': [21, 's'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Os justi', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '12/06': {
        'feast': 'S Nicolai EC',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Statuit ei', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '12/07': {
        'feast': 'S Ambrosii ECD',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'In medio', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '12/07.': {
        'feast': 'In Vigilia Conceptionis Immaculatæ BMV',
        'rank': [18, 'v'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Venite, audite', 'glo': False, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    #! add a flag that makes all the days within the octaves of a given day after the calendar is built.
    '12/08': {
        'feast': 'In Conceptione Immaculata BMV',
        'rank': [2, 'd I cl cum Oct communi'],
        'octave': 4,
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Gaudens gaudebo', 'glo': True, 'cre': True, 'pre': 'de BMV'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '12/10': {
        'feast': 'S Melchide PM',
        'rank': [21, 's'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Si diligis me', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '12/11': {
        'feast': 'S Damasi I PC',
        'rank': [16.1, 'sd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Si diligis me', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '12/13': {
        'feast': 'S Luciæ VM',
        'rank': [15, 'd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Dilexisti', 'glo': True, 'cre': True, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '12/16': {
        'feast': 'S Eusebii EM',
        'rank': [16.1, 'sd'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Sacerdotes Dei', 'glo': True, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '12/20': {
        'feast': 'In Vigilia S Thomæ Ap',
        'rank': [18, 'v'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Ego autem', 'glo': False, 'cre': False, 'pre': 'Communis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
    '12/21': {
        'feast': 'S Thomæ Ap',
        'rank': [10, 'd II cl'],
        'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
        'mass': {'int': 'Mihi autem', 'glo': True, 'cre': True, 'pre': 'de Apostolis'},
        'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
    },
}

""" '08/01': {
    'feast': '',
    'rank': [],
    'comm2': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
    'comm3': {'feast': '', 'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'}},
    'mass': {'int': '', 'glo': True, 'cre': False, 'pre': 'Communis'},
    'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''},
},
 """
