calen_2022 = {
'01/01' : {'feast': 'Circumcisio DNJC et Oct. Nativitatis', 'rank': [3, 'd II cl'], 'mass': {'int': 'Dum medium', 'glo': True, 'com1': 'S. Telesphori PM', 'cre': True, 'pre': 'et Communicantes de Nativitate'}},
'01/02' : {'feast': 'Ssmi Nominis Jesu', 'rank': [10, 'd II cl'], 'mass': {'int': 'In nomine Jesu', 'glo': True, 'cre': True, 'pre': 'de Nativitate'}, 'com1': 'Octava S. Stephani Protomartyris'},
'01/03' : {'feast': 'Octava S. Joannis Ap Ev', 'rank': [18, 's'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'01/04' : {'feast': 'Octava Ss Innocentium Mm.', 'rank': [18, 's'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'01/05' : {'feast': 'Vigilia Epiphaniæ', 'rank': [12, 'sd Vig privil 2 cl'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'01/06' : {'feast': 'Epiphania DNJC', 'rank': [2, 'd I cl cum Oct privil 2 ord'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'01/07' : {'feast': 'Feria I infra Oct. Epiphaniæ', 'rank': [9, 'feria'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'01/08' : {'feast': 'Feria II infra Oct. Epiphaniæ', 'rank': [9, 'feria'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'01/09' : {'feast': 'S. Familiæ Jesu, Mariæ, Joseph; Dominica I infra Oct. Epiphaniæ', 'rank': [11, 'dm'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'01/10' : {'feast': 'Feria IV infra Oct. Epiphaniæ', 'rank': [9, 'feria'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'01/11' : {'feast': 'Feria V infra Oct. Epiphaniæ', 'rank': [9, 'feria'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'01/12' : {'feast': 'Feria VI infra Oct. Epiphaniæ', 'rank': [9, 'feria'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'01/13' : {'feast': 'Octava Epiphaniæ', 'rank': [13, 'dm'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'01/14' : {'feast': 'S Hilarii Episcopi ECD', 'rank': [15, 'd'], 'comm2': {'S Felix SM': {'mass': {'int': 'Lætabitur', 'glo': True, 'cre': True, 'pre': 'Communis'}}}, 'comm3': '', 'office_proper': True, 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}, 'vespers': {'proper': False, 'admag': 'O Doctor', 'propers': {'hymn': '', 'verse': ''}, 'oration': 'Deus, qui populo'}},
'01/15' : {'feast': 'S Pauli Primi Eremitæ C', 'rank': [15, 'd'], 'comm2': 'S Mauri Abb', 'comm3': '', 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}},
'01/16' : {'feast': 'Dominica II post Epiphaniam', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}, 'com1': 'S Marcelli PM'},
'01/17' : {'feast': 'S Antonii Abb', 'rank': [15, 'd'], 'comm2': '', 'comm3': '', 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}},
'01/18' : {'feast': 'Cathedræ S Petri Ap Romæ', 'rank': [14, 'dm'], 'comm2': 'S Pauli Apostoli', 'comm3': 'S Priscæ VM', 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}},
'01/19' : {'feast': 'Ss Marii, Marthæ, Audifacis et Abachum Mm', 'rank': [22, 's'], 'comm2': 'S Canuti RM', 'comm3': '', 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}, 'mag': ''},
'01/20' : {'feast': 'Ss Fabiani P & Sebastiani Mm', 'rank': [15, 'd'], 'comm2': '', 'comm3': '', 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}},
'01/21' : {'feast': 'S Agnetis VM', 'rank': [15, 'd'], 'comm2': '', 'comm3': '', 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}},
'01/22' : {'feast': 'Ss Vincentii & Anastasii Mm', 'rank': [16.1, 'sd'], 'comm2': '', 'comm3': '', 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}},
'01/23' : {'feast': 'Dominica III post Epiphaniam', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}, 'com1': 'S Raymundi de Peñafort C mtv'},
'01/24' : {'feast': 'S Timothei EM', 'rank': [15, 'd'], 'comm2': '', 'comm3': '', 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}},
'01/25' : {'feast': 'Conversio S Pauli Ap', 'rank': [14, 'dm'], 'comm2': '', 'comm3': '', 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}},
'01/26' : {'feast': 'S Polycarpi EM', 'rank': [15, 'd'], 'comm2': '', 'comm3': '', 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}},
'01/27' : {'feast': 'S Joannis Chrysostomi', 'rank': [15, 'd'], 'comm2': '', 'comm3': '', 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}},
'01/28' : {'feast': 'S Petri Nolasci C mtv', 'rank': [15, 'd'], 'comm2': 'S Agnetis VM secundo', 'comm3': '', 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}},
'01/29' : {'feast': 'S Francisci Salesii ECD', 'rank': [15, 'd'], 'comm2': '', 'comm3': '', 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}},
'01/30' : {'feast': 'Dominica IV post Epiphaniam', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}, 'com1': 'S Martinæ VM'},
'01/31' : {'feast': 'S Joannis Bosco C', 'rank': [15, 'd'], 'comm2': '', 'comm3': '', 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}},
'02/06' : {'feast': 'Dominica V post Epiphaniam', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'02/13' : {'feast': 'Dominica in Septuagesima', 'rank': [8, 'sd II cl'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'02/20' : {'feast': 'Dominica in Sexagesima', 'rank': [8, 'sd II cl'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'02/27' : {'feast': 'Dominica in Quinquagesima', 'rank': [8, 'sd II cl'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'03/04' : {'feast': 'S Casimiri C', 'rank': [16.1, 'sd'], 'comm2': 'S Lucii I PM', 'comm3': '', 'mass': {'int': 'Os iusti', 'glo': True, 'cre': False, 'pre': 'Communis'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}},
'03/06' : {'feast': 'Ss Perpetuae et Felicitatiis Mm', 'rank': [15, 'd'], 'comm2': '', 'comm3': '', 'mass': {'int': 'Me expectaverunt', 'glo': True, 'cre': False, 'pre': 'Communis'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}},
'03/07' : {'feast': 'S Thomas De Aquino C', 'rank': [15, 'd'], 'comm2': '', 'comm3': '', 'mass': {'int': 'In medio ecclesiae', 'glo': True, 'cre': False, 'pre': 'Communis'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}},
'03/08' : {'feast': 'S Ioannis a Deo C', 'rank': [15, 'd'], 'comm2': '', 'comm3': '', 'mass': {'int': 'Os iusti', 'glo': True, 'cre': False, 'pre': 'Communis'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}},
'03/09' : {'feast': 'Dies Cinerum', 'rank': [3, 'feria'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'03/10' : {'feast': 'Ss Quadraginta Mm', 'rank': [16.1, 'sd'], 'comm2': '', 'comm3': '', 'mass': {'int': 'Clamaverunt iusti', 'glo': True, 'cre': False, 'pre': 'Communis'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}, 'com1': 'Feria V post Diem Cinerum'},
'03/11' : {'feast': 'Feria VI post Diem Cinerum', 'rank': [18, 'feria'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'03/12' : {'feast': 'S Gregorii I Pp CD', 'rank': [15, 'd'], 'comm2': '', 'comm3': '', 'mass': {'int': 'Sacerdotes Dei', 'glo': True, 'cre': False, 'pre': 'Communis'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}, 'com1': 'Sabbatum post Diem Cinerum'},
'03/13' : {'feast': 'Dominica I in Quadragesima', 'rank': [1, 'sd I cl'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'03/14' : {'feast': 'Feria II infra Hebd I in Quadragesima', 'rank': [18, 'feria'], 'mass': {'int': 'Miserere mihi', 'glo': False, 'cre': False, 'pre': 'de Quadragesima'}},
'03/15' : {'feast': 'Feria III infra Hebd I in Quadragesima', 'rank': [18, 'feria'], 'mass': {'int': 'Sicut oculi', 'glo': False, 'cre': False, 'pre': 'de Quadragesima'}},
'03/16' : {'feast': 'Feria IV Quatuor Temporum Quadragesimæ', 'rank': [3, 'feria'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'03/17' : {'feast': 'S Patricii Ep C', 'rank': [15, 'd'], 'comm2': '', 'comm3': '', 'mass': {'int': 'Statuit', 'glo': True, 'cre': False, 'pre': 'Communis'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}, 'com1': 'Feria V infra Hebd I in Quadragesima'},
'03/18' : {'feast': 'Feria VI Quatuor Temporum Quadragesimæ', 'rank': [3, 'feria'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'03/19' : {'feast': 'S Joseph Sponsi BMV C', 'rank': [2, 'd I cl'], 'comm2': '', 'comm3': '', 'mass': {'int': 'Justus ut', 'glo': True, 'cre': True, 'pre': 'De Sancto Ioseph'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}},
'03/20' : {'feast': 'Dominica II in Quadragesima', 'rank': [1, 'sd I cl'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'03/21' : {'feast': 'S Benedicti Abb', 'rank': [14, 'dm'], 'comm2': '', 'comm3': '', 'mass': {'int': 'Os iusti', 'glo': True, 'cre': False, 'pre': 'Communis'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}, 'com1': 'Feria II infra Hebd II in Quadragesima'},
'03/22' : {'feast': 'Feria III infra Hebd II in Quadragesima', 'rank': [18, 'feria'], 'mass': {'int': 'Sicut oculi', 'glo': False, 'cre': False, 'pre': 'de Quadragesima'}},
'03/23' : {'feast': 'Feria IV infra Hebd II in Quadragesima', 'rank': [18, 'feria'], 'mass': {'int': 'Domine refugium', 'glo': False, 'cre': False, 'pre': 'de Quadragesima'}},
'03/24' : {'feast': 'S Gabrielis Arch', 'rank': [14, 'dm'], 'comm2': '', 'comm3': '', 'mass': {'int': 'Benedicite Dominum', 'glo': True, 'cre': True, 'pre': 'Communis'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}, 'com1': 'Feria V infra Hebd II in Quadragesima'},
'03/25' : {'feast': 'In Annuntiatione BMV', 'rank': [2, 'd I cl'], 'comm2': '', 'comm3': '', 'mass': {'int': 'Vultum tuum', 'glo': True, 'cre': True, 'pre': 'De B Maria Virg'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}},
'03/26' : {'feast': 'Sabbatum infra Hebd II in Quadragesima', 'rank': [18, 'feria'], 'mass': {'int': 'De necessitatibus', 'glo': False, 'cre': False, 'pre': 'de Quadragesima'}},
'03/27' : {'feast': 'Dominica III in Quadragesima', 'rank': [1, 'sd I cl'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'03/28' : {'feast': 'S Ioannis a Capistrano C', 'rank': [16.1, 'sd'], 'comm2': '', 'comm3': '', 'mass': {'int': 'Ego autem', 'glo': True, 'cre': False, 'pre': 'Communis'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}, 'com1': 'Feria II infra Hebd III in Quadragesima'},
'03/29' : {'feast': 'Feria III infra Hebd III in Quadragesima', 'rank': [18, 'feria'], 'mass': {'int': 'Sicut oculi', 'glo': False, 'cre': False, 'pre': 'de Quadragesima'}},
'03/30' : {'feast': 'Feria IV infra Hebd III in Quadragesima', 'rank': [18, 'feria'], 'mass': {'int': 'Domine refugium', 'glo': False, 'cre': False, 'pre': 'de Quadragesima'}},
'03/31' : {'feast': 'Feria V infra Hebd III in Quadragesima', 'rank': [18, 'feria'], 'mass': {'int': 'Reminíscere', 'glo': False, 'cre': False, 'pre': 'de Quadragesima'}},
'04/01' : {'feast': 'Feria VI infra Hebd III in Quadragesima', 'rank': [18, 'feria'], 'mass': {'int': 'Confessio', 'glo': False, 'cre': False, 'pre': 'de Quadragesima'}},
'04/02' : {'feast': 'S Francisco de Paula C', 'rank': [15, 'd'], 'comm2': '', 'comm3': '', 'mass': {'int': 'Iustus ut palma', 'glo': True, 'cre': False, 'pre': 'Communis'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}, 'com1': 'Sabbatum infra Hebd III in Quadragesima'},
'04/03' : {'feast': 'Dominica IV in Quadragesima (Lætare)', 'rank': [1, 'sd I cl'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'04/04' : {'feast': 'S Isidori CD', 'rank': [15, 'd'], 'comm2': '', 'comm3': '', 'mass': {'int': 'In medio ecclesiae', 'glo': True, 'cre': True, 'pre': 'Communis'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}, 'com1': 'Feria II infra Hebd IV in Quadragesima '},
'04/05' : {'feast': 'S Vincentii Ferrerii C', 'rank': [15, 'd'], 'comm2': '', 'comm3': '', 'mass': {'int': 'Os iusti', 'glo': True, 'cre': False, 'pre': 'Communis'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}, 'com1': 'Feria III infra Hebd IV in Quadragesima '},
'04/06' : {'feast': 'Feria IV infra Hebd IV in Quadragesima ', 'rank': [18, 'feria'], 'mass': {'int': 'Domine refugium', 'glo': False, 'cre': False, 'pre': 'de Quadragesima'}},
'04/07' : {'feast': 'Feria V infra Hebd IV in Quadragesima ', 'rank': [18, 'feria'], 'mass': {'int': 'Reminíscere', 'glo': False, 'cre': False, 'pre': 'de Quadragesima'}},
'04/08' : {'feast': 'Feria VI infra Hebd IV in Quadragesima ', 'rank': [18, 'feria'], 'mass': {'int': 'Confessio', 'glo': False, 'cre': False, 'pre': 'de Quadragesima'}},
'04/09' : {'feast': 'Sabbatum infra Hebd IV in Quadragesima ', 'rank': [18, 'feria'], 'mass': {'int': 'De necessitatibus', 'glo': False, 'cre': False, 'pre': 'de Quadragesima'}},
'04/10' : {'feast': 'Dominica de Passione', 'rank': [1, 'sd I cl'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'04/11' : {'feast': 'S Leonis Pp CD', 'rank': [15, 'd'], 'comm2': '', 'comm3': '', 'mass': {'int': 'In medio ecclesiae', 'glo': True, 'cre': True, 'pre': 'Communis'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}, 'com1': 'Feria II infra Hebd de Passione'},
'04/12' : {'feast': 'Feria III infra Hebd de Passione', 'rank': [18, 'feria'], 'mass': {'int': 'Sicut oculi', 'glo': False, 'cre': False, 'pre': 'de Cruce'}},
'04/13' : {'feast': 'S Hermenegildi M', 'rank': [16.1, 'sd'], 'comm2': '', 'comm3': '', 'mass': {'int': 'In virtute', 'glo': True, 'cre': False, 'pre': 'Communis'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}, 'com1': 'Feria IV infra Hebd de Passione'},
'04/14' : {'feast': 'S Iustini M', 'rank': [15, 'd'], 'comm2': 'Ss Tiburtio, Valeriano et Maximo Mm', 'comm3': '', 'mass': {'int': 'Narraverunt mihi', 'glo': True, 'cre': False, 'pre': 'Communis'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}, 'com1': 'Feria V infra Hebd de Passione'},
'04/15' : {'feast': 'Septem Dolorum BMV', 'rank': [14, 'dm'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'04/16' : {'feast': 'Sabbatum infra Hebd de Passione', 'rank': [18, 'feria'], 'mass': {'int': 'De necessitatibus', 'glo': False, 'cre': False, 'pre': 'de Cruce'}},
'04/17' : {'feast': 'Dominica in Palmis', 'rank': [1, 'sd I cl'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'04/17.' : {'feast': 'Dominica in Albis', 'rank': [1, 'dm'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'04/18' : {'feast': 'Feria II infra Oct. Paschæ', 'rank': [2, 'd I cl'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'04/19' : {'feast': 'Feria III infra Oct. Paschæ', 'rank': [2, 'd I cl'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'04/20' : {'feast': 'Feria IV Majoris Hebd', 'rank': [3, 'feria'], 'mass': {'int': 'In nomine Jesu', 'glo': False, 'cre': False, 'pre': 'de Cruce'}},
'04/20.' : {'feast': 'Feria IV infra Oct. Paschæ', 'rank': [3, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'04/21' : {'feast': 'Feria V in Cœna Domini', 'rank': [2, 'd I cl'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'04/22' : {'feast': 'Feria VI in Parasceve', 'rank': [2, 'd I cl'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'04/23' : {'feast': 'Sabbatum Sanctum', 'rank': [2, 'd I cl'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'04/24' : {'feast': 'Dominica II post Pascha', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}, 'com1': 'S Fidelis a Sigmaringa'},
'04/25' : {'feast': 'S Marci Ev', 'rank': [10, 'd II cl'], 'comm2': '', 'comm3': '', 'mass': {'int': 'Protexisti me', 'glo': True, 'cre': True, 'pre': 'De Apostolis'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}},
'04/26' : {'feast': 'Ss Cleti et Marcellini PP Mm', 'rank': [16.1, 'sd'], 'comm2': '', 'comm3': '', 'mass': {'int': 'Sancti tai, Domine', 'glo': True, 'cre': False, 'pre': 'Communis'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}},
'04/27' : {'feast': 'Solemnitas S. Joseph, Sponsi BMV C. et Ecclesiæ Universalis Patroni', 'rank': [2, 'd I cl cum Oct Communi'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'05/01' : {'feast': 'Dominica III post Pascha', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'05/04' : {'feast': 'Octava Solemnitatis S. Joseph', 'rank': [13, 'dm'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'05/08' : {'feast': 'Dominica IV post Pascha', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'05/15' : {'feast': 'Dominica V post Pascha', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'05/16' : {'feast': 'In Rogationibus', 'rank': [21, 's'], 'mass': {'int': 'Exaudivit', 'glo': False, 'cre': False, 'pre': 'Paschalis'}},
'05/17' : {'feast': 'In Rogationibus', 'rank': [21, 's'], 'mass': {'int': 'Exaudivit', 'glo': False, 'cre': False, 'pre': 'Paschalis'}},
'05/18' : {'feast': 'Vigilæ Ascensionis', 'rank': [18, 'feria'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}, 'com1': 'In Rogationibus'},
'05/19' : {'feast': 'Ascensio DNJC', 'rank': [2, 'd I cl cum Oct privil 3 ord'], 'mass': {'int': 'Viri Galilæi', 'glo': True, 'cre': True, 'pre': 'et Communicantes de Ascensione'}},
'05/21' : {'feast': 'Vigilia Pentecostes', 'rank': [3, 'd I cl Vig privil I cl'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'05/22' : {'feast': 'Dominica Pentecostes', 'rank': [1, 'd I cl cum Oct privil I ord'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'05/23' : {'feast': 'Feria II infra Oct. Pentecostes', 'rank': [2, 'd I cl'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'05/24' : {'feast': 'Feria III infra Oct. Pentecostes', 'rank': [2, 'd I cl'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'05/25' : {'feast': 'Feria VI infra Oct. Ascensionis', 'rank': [16, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}, 'com1': 'Feria IV Quatuor Temporum infra Oct. Pentecostes'},
'05/26' : {'feast': 'Feria V infra Oct. Pentecostes', 'rank': [3, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'05/27' : {'feast': 'Feria VI infra Oct. Pentecostes', 'rank': [3, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'05/28' : {'feast': 'Sabbatum infra Oct. Pentecostes', 'rank': [3, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'05/29' : {'feast': 'Festum Sanctissimæ Trinitatis', 'rank': [2, 'd I cl'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'06/02' : {'feast': 'Sanctissimi Corporis Christi', 'rank': [2, 'd I cl cum Oct privil 2 ord'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'06/03' : {'feast': 'Feria VI infra Oct. Ssmi Corporis Christi', 'rank': [9, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'06/04' : {'feast': 'Sabbatum infra Oct. Ssmi Corporis Christi', 'rank': [9, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'06/05' : {'feast': 'Dominica infra Oct. Ssmi Corporis Christi (Dominica II post Pentecosten)', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'06/06' : {'feast': 'Feria II infra Oct. Ssmi Corporis Christi', 'rank': [9, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'06/07' : {'feast': 'Feria III infra Oct. Ssmi Corporis Christi', 'rank': [9, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'06/08' : {'feast': 'Feria IV infra Oct. Ssmi Corporis Christi', 'rank': [9, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'06/09' : {'feast': 'Octava Ssmi Corporis Christi', 'rank': [4, 'dm'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'06/10' : {'feast': 'Sacratissimi Cordis Jesu', 'rank': [2, 'd I cl cum Oct privil 3 ord'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'06/11' : {'feast': 'Sabbatum infra Oct. Ssmi Cordis Jesu', 'rank': [17, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'06/12' : {'feast': 'Dominica infra Oct. Ssmi Cordis DNJC (Dominica III post Pentecosten)', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'06/13' : {'feast': 'Feria II infra Oct. Ssmi Cordis Jesu', 'rank': [17, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'06/14' : {'feast': 'Feria III infra Oct. Ssmi Cordis Jesu', 'rank': [17, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'06/15' : {'feast': 'Feria IV infra Oct. Ssmi Cordis Jesu', 'rank': [17, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'06/16' : {'feast': 'Feria V infra Oct. Ssmi Cordis Jesu', 'rank': [17, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'06/17' : {'feast': 'Octava Sacratissimi Cordis Jesu', 'rank': [13, 'dm'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'06/19' : {'feast': 'Dominica IV post Pentecosten', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'06/26' : {'feast': 'Dominica V post Pentecosten', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'07/03' : {'feast': 'Dominica VI post Pentecosten', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'07/10' : {'feast': 'Dominica VII post Pentecosten', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'07/17' : {'feast': 'Dominica VIII post Pentecosten', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'07/24' : {'feast': 'Dominica IX post Pentecosten', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'07/31' : {'feast': 'Dominica X post Pentecosten', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'08/07' : {'feast': 'Dominica XI post Pentecosten', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'08/14' : {'feast': 'Dominica XII post Pentecosten', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'08/21' : {'feast': 'Dominica XIII post Pentecosten', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'08/28' : {'feast': 'Dominica XIV post Pentecosten', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'09/04' : {'feast': 'Dominica XV post Pentecosten', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'09/11' : {'feast': 'Dominica XVI post Pentecosten', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'09/14' : {'feast': 'Feria IV Quatuor Temporum Septembris', 'rank': [18, 'feria'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'09/16' : {'feast': 'Feria VI Quatuor Temporum Septembris', 'rank': [18, 'feria'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'09/17' : {'feast': 'Sabbatum Quatuor Temporum Septembris', 'rank': [18, 'feria'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'09/18' : {'feast': 'Dominica XVII post Pentecosten', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'09/25' : {'feast': 'Dominica XVIII post Pentecosten', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'10/02' : {'feast': 'Dominica XIX post Pentecosten', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'10/09' : {'feast': 'Dominica XX post Pentecosten', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'10/16' : {'feast': 'Dominica XXI post Pentecosten', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'10/23' : {'feast': 'Dominica XXII post Pentecosten', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'10/30' : {'feast': 'In Festo DNJC Regis', 'rank': [2, 'd I cl'], 'mass': {'int': 'Dignus est', 'glo': True, 'cre': True, 'pre': 'de DNJC Rege'}},
'11/06' : {'feast': 'Dominica XXIV post Pentecosten', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'11/13' : {'feast': 'Dominica XXV post Pentecosten', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'11/20' : {'feast': 'Dominica XXVI post Pentecosten', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'11/27' : {'feast': 'Dominica I Adventus', 'rank': [1, 'sd'], 'mass': {'int': 'Ad te levavi', 'glo': False, 'cre': True, 'pre': 'de Trinitate'}},
'12/04' : {'feast': 'Dominica II Adventus', 'rank': [8, 'sd II cl'], 'mass': {'int': 'Populus Sion', 'glo': False, 'cre': True, 'pre': 'de Trinitate'}},
'12/11' : {'feast': 'Dominica III Adventus', 'rank': [8, 'sd II cl'], 'mass': {'int': 'Gaudete', 'glo': False, 'cre': True, 'pre': 'de Trinitate'}},
'12/14' : {'feast': 'Feria IV Quatuor Temporum in Adventus', 'rank': [18, 'feria'], 'mass': {'int': 'Rorate cæli', 'glo': False, 'cre': False, 'pre': 'Communis'}},
'12/16' : {'feast': 'Feria VI Quatuor Temporum in Adventus', 'rank': [18, 'feria'], 'mass': {'int': 'Prope es tu', 'glo': False, 'cre': False, 'pre': 'Communis'}},
'12/17' : {'feast': 'Sabbatum Quatuor Temporum in Adventus', 'rank': [18, 'feria'], 'mass': {'int': 'Veni, et ostende', 'glo': False, 'cre': False, 'pre': 'Communis'}},
'12/18' : {'feast': 'Dominica IV Adventus', 'rank': [8, 'sd II cl'], 'mass': {'int': 'Rorate cæli', 'glo': False, 'cre': True, 'pre': 'de Trinitate'}},
'12/24' : {'feast': 'Vigilia Nativitas DNJC', 'rank': [3, 'd I cl Vig privil I cl'], 'mass': {'int': 'Hodie scietis', 'glo': False, 'cre': False, 'pre': 'Communis'}},
'12/25' : {'feast': 'Nativitas DNJC', 'rank': [2, 'd I cl cum Oct privil 3 ord'], 'mass': {'Ad Primam Missam': {'int': 'Domine dixit', 'glo': True, 'cre': True, 'pre': 'et Communicantes (in hac Missa tantum dicitur "noctem") de Nativitate'}, 'Ad Secundam Missam': {'int': 'Lux fulgebit', 'glo': True, 'cre': True, 'pre': 'et Communicantes de Nativitate'}, 'Ad Tertiam Missam': {'int': 'Puer natus', 'glo': True, 'cre': True, 'pre': 'et Communicantes de Nativitate'}}},
'12/26' : {'feast': 'S. Stephani Protomartyris', 'rank': [10, 'd II cl cum Oct simplici'], 'mass': {'int': 'Sederunt', 'glo': True, 'cre': True, 'pre': 'et Communicantes de Nativitate'}},
'12/27' : {'feast': 'S. Joannis Ap. Ev.', 'rank': [10, 'd II cl cum Oct simplici'], 'mass': {'int': 'In medio ecclesiæ', 'glo': True, 'cre': True, 'pre': 'et Communicantes de Nativitate'}},
'12/28' : {'feast': 'Ss Innocentium Mm.', 'rank': [10, 'd II cl cum Oct simplici'], 'mass': {'int': 'Ex ore infantium', 'glo': True, 'cre': True, 'pre': 'et Communicantes de Nativitate'}},
'12/29' : {'feast': 'S. Thomæ E.M.', 'rank': [15, 'd'], 'mass': {'int': 'Gaudeamus omnes', 'glo': True, 'cre': True, 'pre': 'et Communicantes de Nativitate'}},
'12/30' : {'feast': 'Dominica Infra Octavam Nativitatis reposita', 'rank': [12, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'12/31' : {'feast': 'S. Silvestri I P.C.', 'rank': [15, 'd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'et Communicantes de Nativitate'}},
'trans 03/19' : {'feast': 'S Joseph Sponsi BMV C', 'rank': [2, 'd I cl'], 'comm2': '', 'comm3': '', 'mass': {'int': 'Justus ut', 'glo': True, 'cre': True, 'pre': 'De Sancto Ioseph'}, 'vespers': {'proper': False, 'admag': '', 'propers': {}, 'oration': ''}},
'trans 04/18' : {'feast': 'Feria II infra Oct. Paschæ', 'rank': [2, 'd I cl'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'trans 04/19' : {'feast': 'Feria III infra Oct. Paschæ', 'rank': [2, 'd I cl'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'trans 04/21' : {'feast': 'Feria V infra Oct. Paschæ', 'rank': [3, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'trans 04/22' : {'feast': 'Feria VI infra Oct. Paschæ', 'rank': [3, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
'trans 04/23' : {'feast': 'Sabbatum in Albis', 'rank': [3, 'sd'], 'mass': {'int': 'Missa', 'glo': True, 'cre': True, 'pre': 'Communis'}},
}