temporal = {
 '01/01/72': {'feast': 'Circumcisio Domini et Oct Nativitatis', 'rank': 'd2'},
 '01/02/72': {'feast': 'Octava S Stephani Protomartyris', 'rank': 'sp'},
 '01/03/72': {'feast': 'Octava S Joannis Ap & Ev', 'rank': 'sp'},
 '01/04/72': {'feast': 'Octava Ss Innocentium Mm', 'rank': 'sp'},
 '01/02/72': {'feast': 'SS Nominis Jesu', 'rank': 'd2'},
 '02/18/72': {'feast': 'Dominica in Septuagesima', 'rank': 'sd2'},
 '02/25/72': {'feast': 'Dominica in Sexagesima', 'rank': 'sd2'},
 '03/03/72': {'feast': 'Dominica in Quinquagesima', 'rank': 'sd2'},
 '01/08/72': {'feast': 'De die III infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/09/72': {'feast': 'De die IV infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/10/72': {'feast': 'De die V infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/11/72': {'feast': 'De die VI infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/12/72': {'feast': 'De die VII infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/07/72': {'feast': 'S Familiæ Jesu Mariæ et Joseph; Dominica I post Epiphaniam', 'rank': 'dm'},
 '01/14/72': {'feast': 'Dominica II post Epiphaniam', 'rank': 'sp'},
 '01/21/72': {'feast': 'Dominica III post Epiphaniam', 'rank': 'sp'},
 '01/28/72': {'feast': 'Dominica IV post Epiphaniam', 'rank': 'sp'},
 '02/04/72': {'feast': 'Dominica V post Epiphaniam', 'rank': 'sp'},
 '02/11/72': {'feast': 'Dominica VI post Epiphaniam', 'rank': 'sp'},
 '03/06/72': {'feast': 'Dies Cinerum', 'rank': 'sp'},
 '03/06/72': {'feast': 'Feria V post Diem Cinerum', 'rank': 'sp'},
 '03/06/72': {'feast': 'Feria VI post Diem Cinerum', 'rank': 'sp'},
 '03/06/72': {'feast': 'Sabbato post Diem Cinerum', 'rank': 'sp'},
 '03/10/72': {'feast': 'Dominica I in Quadragesima', 'rank': 'sd1'},
 '03/11/72': {'feast': 'Feria II infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/12/72': {'feast': 'Feria III infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/13/72': {'feast': 'Feria IV Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/14/72': {'feast': 'Feria V infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/15/72': {'feast': 'Feria VI Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/16/72': {'feast': 'Sabbato Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/17/72': {'feast': 'Dominica II in Quadragesima', 'rank': 'sd1'},
 '03/18/72': {'feast': 'Feria II infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/19/72': {'feast': 'Feria III infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/20/72': {'feast': 'Feria IV infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/21/72': {'feast': 'Feria V infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/22/72': {'feast': 'Feria VI infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/23/72': {'feast': 'Sabbato infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/24/72': {'feast': 'Dominica III in Quadragesima', 'rank': 'sd1'},
 '03/25/72': {'feast': 'Feria II infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/26/72': {'feast': 'Feria III infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/27/72': {'feast': 'Feria IV infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/28/72': {'feast': 'Feria V infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/29/72': {'feast': 'Feria VI infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/30/72': {'feast': 'Sabbato infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/31/72': {'feast': 'Dominica IV in Quadragesima', 'rank': 'sd1'},
 '04/01/72': {'feast': 'Feria II infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/02/72': {'feast': 'Feria III infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/03/72': {'feast': 'Feria IV infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/04/72': {'feast': 'Feria V infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/05/72': {'feast': 'Feria VI infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/06/72': {'feast': 'Sabbato infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/07/72': {'feast': 'Dominica de Passione', 'rank': 'sd1'},
 '04/08/72': {'feast': 'Feria II infra Hebd de Passione', 'rank': 'sp'},
 '04/09/72': {'feast': 'Feria III infra Hebd de Passione', 'rank': 'sp'},
 '04/10/72': {'feast': 'Feria IV infra Hebd de Passione', 'rank': 'sp'},
 '04/11/72': {'feast': 'Feria V infra Hebd de Passione', 'rank': 'sp'},
 '04/12/72': {'feast': 'Septem Dolorum BMV', 'rank': 'dm'},
 '04/13/72': {'feast': 'Sabbato infra Hebd de Passione', 'rank': 'sp'},
 '04/14/72': {'feast': 'Dominica in Palmis', 'rank': 'sd1'},
 '04/15/72': {'feast': 'Feria II Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/16/72': {'feast': 'Feria III Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/17/72': {'feast': 'Feria IV Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/18/72': {'feast': 'Feria V in Cœna Domini', 'rank': 'd1'},
 '04/19/72': {'feast': 'Feria VI in Parasceve', 'rank': 'd1'},
 '04/20/72': {'feast': 'Sabbatum Sanctum', 'rank': 'd1'},
 '04/21/72': {'feast': 'Dominica Resurrectionis', 'rank': 'd1'},
 '04/22/72': {'feast': 'Feria II Paschatis', 'rank': 'd1'},
 '04/23/72': {'feast': 'Feria III Paschatis', 'rank': 'd1'},
 '04/24/72': {'feast': 'De die IV infra Oct Paschæ', 'rank': 'sd'},
 '04/25/72': {'feast': 'De die V infra Oct Paschæ', 'rank': 'sd'},
 '04/26/72': {'feast': 'De die VI infra Oct Paschæ', 'rank': 'sd'},
 '04/27/72': {'feast': 'Sabbatum in Albis', 'rank': 'sd'},
 '04/28/72': {'feast': 'Dominica in Albis', 'rank': 'sd'},
 '05/08/72': {'feast': 'Solemnitas S Joseph, Sponsi BMV C et Ecclesiæ Universalis Patroni', 'rank': 'd1'},
 '05/15/72': {'feast': 'Octava Solemnitas S Joseph', 'rank': 'dm'},
 '05/05/72': {'feast': 'Dominica II post Pascha', 'rank': 'sd'},
 '05/12/72': {'feast': 'Dominica III post Pascha', 'rank': 'sd'},
 '05/19/72': {'feast': 'Dominica IV post Pascha', 'rank': 'sd'},
 '05/27/72': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/28/72': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/29/72': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/29/72': {'feast': 'Vigilæ Ascensionis', 'rank': 'sp'},
 '05/30/72': {'feast': 'Ascensio DNJC', 'rank': 'd1'},
 '05/26/72': {'feast': 'Dominica V post Pascha', 'rank': 'sd'},
 '06/01/72': {'feast': 'De II die infra Oct Ascensionis', 'rank': 'sd'},
 '06/03/72': {'feast': 'De IV die infra Oct Ascensionis', 'rank': 'sd'},
 '06/04/72': {'feast': 'De V die infra Oct Ascensionis', 'rank': 'sd'},
 '06/05/72': {'feast': 'De VI die infra Oct Ascensionis', 'rank': 'sd'},
 '06/02/72': {'feast': 'Dominica infra Octavam Ascensionis', 'rank': 'sd'},
 '06/08/72': {'feast': 'Vigilia Pentecostes', 'rank': 'sd'},
 '06/09/72': {'feast': 'Dominica Pentecostes', 'rank': 'd1'},
 '06/01/72': {'feast': 'De II die infra Oct Pentecostes', 'rank': 'd1'},
 '06/02/72': {'feast': 'De III die infra Oct Pentecostes', 'rank': 'd1'},
 '06/03/72': {'feast': 'De IV die infra Oct Pentecostes', 'rank': 'd1'},
 '06/04/72': {'feast': 'De V die infra Oct Pentecostes', 'rank': 'd1'},
 '06/05/72': {'feast': 'De VI die infra Oct Pentecostes', 'rank': 'd1'},
 '06/06/72': {'feast': 'Sabbato die infra Oct Pentecostes', 'rank': 'd1'},
 '06/12/72': {'feast': 'Feria IV Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/14/72': {'feast': 'Feria VI Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/15/72': {'feast': 'Sabbato Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/16/72': {'feast': 'Dominica Sanctissimæ Trinitatis', 'rank': 'd1'},
 '06/21/72': {'feast': 'De II die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/22/72': {'feast': 'De III die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/24/72': {'feast': 'De V die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/25/72': {'feast': 'De VI die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/26/72': {'feast': 'De VII die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/20/72': {'feast': 'Sanctissimi Corporis Christi', 'rank': 'd1'},
 '06/27/72': {'feast': 'Octava SSmi Corporis Christi', 'rank': 'dm'},
 '06/23/72': {'feast': 'Dominica II post Pentecosten infra Octavam Corporis Christi', 'rank': 'sd'},
 '06/29/72': {'feast': 'De II die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '07/01/72': {'feast': 'De IV die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '07/02/72': {'feast': 'De V die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '07/03/72': {'feast': 'De VI die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '07/04/72': {'feast': 'De VII die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/28/72': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'd1'},
 '07/05/72': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'dm'},
 '06/30/72': {'feast': 'Dominica III post Pentecosten infra Octavam SSmi Cordis DNJC', 'rank': 'sd'},
 '07/07/72': {'feast': 'Dominica V post Pentecosten', 'rank': 'sd'},
 '07/14/72': {'feast': 'Dominica VI post Pentecosten', 'rank': 'sd'},
 '07/21/72': {'feast': 'Dominica VII post Pentecosten', 'rank': 'sd'},
 '07/28/72': {'feast': 'Dominica VIII post Pentecosten', 'rank': 'sd'},
 '08/04/72': {'feast': 'Dominica IX post Pentecosten', 'rank': 'sd'},
 '08/11/72': {'feast': 'Dominica X post Pentecosten', 'rank': 'sd'},
 '08/18/72': {'feast': 'Dominica XI post Pentecosten', 'rank': 'sd'},
 '08/25/72': {'feast': 'Dominica XII post Pentecosten', 'rank': 'sd'},
 '09/01/72': {'feast': 'Dominica XIII post Pentecosten', 'rank': 'sd'},
 '09/08/72': {'feast': 'Dominica XIV post Pentecosten', 'rank': 'sd'},
 '09/15/72': {'feast': 'Dominica XV post Pentecosten', 'rank': 'sd'},
 '09/18/72': {'feast': 'Feria IV Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/20/72': {'feast': 'Feria VI Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/21/72': {'feast': 'Sabbato Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/22/72': {'feast': 'Dominica XVI post Pentecosten', 'rank': 'sd'},
 '09/29/72': {'feast': 'Dominica XVII post Pentecosten', 'rank': 'sd'},
 '10/06/72': {'feast': 'Dominica XVIII post Pentecosten', 'rank': 'sd'},
 '10/13/72': {'feast': 'Dominica XIX post Pentecosten', 'rank': 'sd'},
 '10/20/72': {'feast': 'Dominica XX post Pentecosten', 'rank': 'sd'},
 '10/27/72': {'feast': 'Dominica XXI post Pentecosten', 'rank': 'sd'},
 '11/03/72': {'feast': 'Dominica XXII post Pentecosten', 'rank': 'sd'},
 '11/10/72': {'feast': 'Dominica XXIII post Pentecosten', 'rank': 'sd'},
 '11/17/72': {'feast': 'Dominica XXIV post Pentecosten', 'rank': 'sd'},
 '11/24/72': {'feast': 'Dominica XXV post Pentecosten', 'rank': 'sd'},
 '12/01/72': {'feast': 'Dominica XXVI post Pentecosten', 'rank': 'sd'},
 '12/22/72': {'feast': 'Dominica IV Adventus', 'rank': 'sd2'},
 '12/15/72': {'feast': 'Dominica III Adventus', 'rank': 'sd2'},
 '12/18/72': {'feast': 'Feria IV Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/20/72': {'feast': 'Feria VI Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/21/72': {'feast': 'Sabbato Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/08/72': {'feast': 'Dominica II Adventus', 'rank': 'sd2'},
 '12/01/72': {'feast': 'Dominica I Adventus', 'rank': 'sd2'},
 '12/25/72': {'feast': 'Nativitas DNJC', 'rank': 'd1'},
 '12/29/72': {'feast': 'Dominica Infra Octavam Nativitatis', 'rank': 'sd'},
 '12/30/72': {'feast': 'De VI Die infra Octavam Nativitatis', 'rank': 'sd'},
 '12/26/72': {'feast': 'S Stephani Protomartyris', 'rank': 'd2'},
 '12/27/72': {'feast': 'S Joannis Ap & Ev', 'rank': 'd2'},
 '12/28/72': {'feast': 'Ss Innocentium Mm', 'rank': 'd2'},
 '12/29/72': {'feast': 'S Thomas EM', 'rank': 'd'},
 '12/31/72': {'feast': 'S Sylvestri I PC', 'rank': 'd'},
}
