temporal = {
 '01/01/46': {'feast': 'Circumcisio Domini et Oct Nativitatis', 'rank': 'd2'},
 '01/02/46': {'feast': 'Octava S Stephani Protomartyris', 'rank': 'sp'},
 '01/03/46': {'feast': 'Octava S Joannis Ap & Ev', 'rank': 'sp'},
 '01/04/46': {'feast': 'Octava Ss Innocentium Mm', 'rank': 'sp'},
 '01/02/46': {'feast': 'SS Nominis Jesu', 'rank': 'd2'},
 '01/21/46': {'feast': 'Dominica in Septuagesima', 'rank': 'sd2'},
 '01/28/46': {'feast': 'Dominica in Sexagesima', 'rank': 'sd2'},
 '02/04/46': {'feast': 'Dominica in Quinquagesima', 'rank': 'sd2'},
 '01/08/46': {'feast': 'De die III infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/09/46': {'feast': 'De die IV infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/10/46': {'feast': 'De die V infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/11/46': {'feast': 'De die VI infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/12/46': {'feast': 'De die VII infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/07/46': {'feast': 'S Familiæ Jesu Mariæ et Joseph; Dominica I post Epiphaniam', 'rank': 'dm'},
 '01/14/46': {'feast': 'Dominica II post Epiphaniam', 'rank': 'sp'},
 '02/07/46': {'feast': 'Dies Cinerum', 'rank': 'sp'},
 '02/07/46': {'feast': 'Feria V post Diem Cinerum', 'rank': 'sp'},
 '02/07/46': {'feast': 'Feria VI post Diem Cinerum', 'rank': 'sp'},
 '02/07/46': {'feast': 'Sabbato post Diem Cinerum', 'rank': 'sp'},
 '02/11/46': {'feast': 'Dominica I in Quadragesima', 'rank': 'sd1'},
 '02/12/46': {'feast': 'Feria II infra Hebd I in Quadragesima', 'rank': 'sp'},
 '02/13/46': {'feast': 'Feria III infra Hebd I in Quadragesima', 'rank': 'sp'},
 '02/14/46': {'feast': 'Feria IV Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '02/15/46': {'feast': 'Feria V infra Hebd I in Quadragesima', 'rank': 'sp'},
 '02/16/46': {'feast': 'Feria VI Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '02/17/46': {'feast': 'Sabbato Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '02/18/46': {'feast': 'Dominica II in Quadragesima', 'rank': 'sd1'},
 '02/19/46': {'feast': 'Feria II infra Hebd II in Quadragesima', 'rank': 'sp'},
 '02/20/46': {'feast': 'Feria III infra Hebd II in Quadragesima', 'rank': 'sp'},
 '02/21/46': {'feast': 'Feria IV infra Hebd II in Quadragesima', 'rank': 'sp'},
 '02/22/46': {'feast': 'Feria V infra Hebd II in Quadragesima', 'rank': 'sp'},
 '02/23/46': {'feast': 'Feria VI infra Hebd II in Quadragesima', 'rank': 'sp'},
 '02/24/46': {'feast': 'Sabbato infra Hebd II in Quadragesima', 'rank': 'sp'},
 '02/25/46': {'feast': 'Dominica III in Quadragesima', 'rank': 'sd1'},
 '02/26/46': {'feast': 'Feria II infra Hebd III in Quadragesima', 'rank': 'sp'},
 '02/27/46': {'feast': 'Feria III infra Hebd III in Quadragesima', 'rank': 'sp'},
 '02/28/46': {'feast': 'Feria IV infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/01/46': {'feast': 'Feria V infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/02/46': {'feast': 'Feria VI infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/03/46': {'feast': 'Sabbato infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/04/46': {'feast': 'Dominica IV in Quadragesima', 'rank': 'sd1'},
 '03/05/46': {'feast': 'Feria II infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/06/46': {'feast': 'Feria III infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/07/46': {'feast': 'Feria IV infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/08/46': {'feast': 'Feria V infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/09/46': {'feast': 'Feria VI infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/10/46': {'feast': 'Sabbato infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/11/46': {'feast': 'Dominica de Passione', 'rank': 'sd1'},
 '03/12/46': {'feast': 'Feria II infra Hebd de Passione', 'rank': 'sp'},
 '03/13/46': {'feast': 'Feria III infra Hebd de Passione', 'rank': 'sp'},
 '03/14/46': {'feast': 'Feria IV infra Hebd de Passione', 'rank': 'sp'},
 '03/15/46': {'feast': 'Feria V infra Hebd de Passione', 'rank': 'sp'},
 '03/16/46': {'feast': 'Septem Dolorum BMV', 'rank': 'dm'},
 '03/17/46': {'feast': 'Sabbato infra Hebd de Passione', 'rank': 'sp'},
 '03/18/46': {'feast': 'Dominica in Palmis', 'rank': 'sd1'},
 '03/19/46': {'feast': 'Feria II Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '03/20/46': {'feast': 'Feria III Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '03/21/46': {'feast': 'Feria IV Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '03/22/46': {'feast': 'Feria V in Cœna Domini', 'rank': 'd1'},
 '03/23/46': {'feast': 'Feria VI in Parasceve', 'rank': 'd1'},
 '03/24/46': {'feast': 'Sabbatum Sanctum', 'rank': 'd1'},
 '03/25/46': {'feast': 'Dominica Resurrectionis', 'rank': 'd1'},
 '03/26/46': {'feast': 'Feria II Paschatis', 'rank': 'd1'},
 '03/27/46': {'feast': 'Feria III Paschatis', 'rank': 'd1'},
 '03/28/46': {'feast': 'De die IV infra Oct Paschæ', 'rank': 'sd'},
 '03/29/46': {'feast': 'De die V infra Oct Paschæ', 'rank': 'sd'},
 '03/30/46': {'feast': 'De die VI infra Oct Paschæ', 'rank': 'sd'},
 '03/31/46': {'feast': 'Sabbatum in Albis', 'rank': 'sd'},
 '04/01/46': {'feast': 'Dominica in Albis', 'rank': 'sd'},
 '04/11/46': {'feast': 'Solemnitas S Joseph, Sponsi BMV C et Ecclesiæ Universalis Patroni', 'rank': 'd1'},
 '04/18/46': {'feast': 'Octava Solemnitas S Joseph', 'rank': 'dm'},
 '04/08/46': {'feast': 'Dominica II post Pascha', 'rank': 'sd'},
 '04/15/46': {'feast': 'Dominica III post Pascha', 'rank': 'sd'},
 '04/22/46': {'feast': 'Dominica IV post Pascha', 'rank': 'sd'},
 '04/30/46': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/01/46': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/02/46': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/02/46': {'feast': 'Vigilæ Ascensionis', 'rank': 'sp'},
 '05/03/46': {'feast': 'Ascensio DNJC', 'rank': 'd1'},
 '04/29/46': {'feast': 'Dominica V post Pascha', 'rank': 'sd'},
 '05/05/46': {'feast': 'De II die infra Oct Ascensionis', 'rank': 'sd'},
 '05/07/46': {'feast': 'De IV die infra Oct Ascensionis', 'rank': 'sd'},
 '05/08/46': {'feast': 'De V die infra Oct Ascensionis', 'rank': 'sd'},
 '05/09/46': {'feast': 'De VI die infra Oct Ascensionis', 'rank': 'sd'},
 '05/06/46': {'feast': 'Dominica infra Octavam Ascensionis', 'rank': 'sd'},
 '05/12/46': {'feast': 'Vigilia Pentecostes', 'rank': 'sd'},
 '05/13/46': {'feast': 'Dominica Pentecostes', 'rank': 'd1'},
 '05/05/46': {'feast': 'De II die infra Oct Pentecostes', 'rank': 'd1'},
 '05/06/46': {'feast': 'De III die infra Oct Pentecostes', 'rank': 'd1'},
 '05/07/46': {'feast': 'De IV die infra Oct Pentecostes', 'rank': 'd1'},
 '05/08/46': {'feast': 'De V die infra Oct Pentecostes', 'rank': 'd1'},
 '05/09/46': {'feast': 'De VI die infra Oct Pentecostes', 'rank': 'd1'},
 '05/10/46': {'feast': 'Sabbato die infra Oct Pentecostes', 'rank': 'd1'},
 '05/16/46': {'feast': 'Feria IV Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '05/18/46': {'feast': 'Feria VI Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '05/19/46': {'feast': 'Sabbato Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '05/20/46': {'feast': 'Dominica Sanctissimæ Trinitatis', 'rank': 'd1'},
 '05/25/46': {'feast': 'De II die infra Oct Corporis Christi', 'rank': 'sd'},
 '05/26/46': {'feast': 'De III die infra Oct Corporis Christi', 'rank': 'sd'},
 '05/28/46': {'feast': 'De V die infra Oct Corporis Christi', 'rank': 'sd'},
 '05/29/46': {'feast': 'De VI die infra Oct Corporis Christi', 'rank': 'sd'},
 '05/30/46': {'feast': 'De VII die infra Oct Corporis Christi', 'rank': 'sd'},
 '05/24/46': {'feast': 'Sanctissimi Corporis Christi', 'rank': 'd1'},
 '05/31/46': {'feast': 'Octava SSmi Corporis Christi', 'rank': 'dm'},
 '05/27/46': {'feast': 'Dominica II post Pentecosten infra Octavam Corporis Christi', 'rank': 'sd'},
 '06/02/46': {'feast': 'De II die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/04/46': {'feast': 'De IV die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/05/46': {'feast': 'De V die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/06/46': {'feast': 'De VI die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/07/46': {'feast': 'De VII die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/01/46': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'd1'},
 '06/08/46': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'dm'},
 '06/03/46': {'feast': 'Dominica III post Pentecosten infra Octavam SSmi Cordis DNJC', 'rank': 'sd'},
 '06/10/46': {'feast': 'Dominica V post Pentecosten', 'rank': 'sd'},
 '06/17/46': {'feast': 'Dominica VI post Pentecosten', 'rank': 'sd'},
 '06/24/46': {'feast': 'Dominica VII post Pentecosten', 'rank': 'sd'},
 '07/01/46': {'feast': 'Dominica VIII post Pentecosten', 'rank': 'sd'},
 '07/08/46': {'feast': 'Dominica IX post Pentecosten', 'rank': 'sd'},
 '07/15/46': {'feast': 'Dominica X post Pentecosten', 'rank': 'sd'},
 '07/22/46': {'feast': 'Dominica XI post Pentecosten', 'rank': 'sd'},
 '07/29/46': {'feast': 'Dominica XII post Pentecosten', 'rank': 'sd'},
 '08/05/46': {'feast': 'Dominica XIII post Pentecosten', 'rank': 'sd'},
 '08/12/46': {'feast': 'Dominica XIV post Pentecosten', 'rank': 'sd'},
 '08/19/46': {'feast': 'Dominica XV post Pentecosten', 'rank': 'sd'},
 '08/26/46': {'feast': 'Dominica XVI post Pentecosten', 'rank': 'sd'},
 '09/02/46': {'feast': 'Dominica XVII post Pentecosten', 'rank': 'sd'},
 '09/09/46': {'feast': 'Dominica XVIII post Pentecosten', 'rank': 'sd'},
 '09/16/46': {'feast': 'Dominica XIX post Pentecosten', 'rank': 'sd'},
 '09/19/46': {'feast': 'Feria IV Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/21/46': {'feast': 'Feria VI Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/22/46': {'feast': 'Sabbato Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/23/46': {'feast': 'Dominica XX post Pentecosten', 'rank': 'sd'},
 '09/30/46': {'feast': 'Dominica XXI post Pentecosten', 'rank': 'sd'},
 '10/07/46': {'feast': 'Dominica XXII post Pentecosten', 'rank': 'sd'},
 '10/14/46': {'feast': 'Dominica XXIII post Pentecosten', 'rank': 'sd'},
 '10/21/46': {'feast': 'Dominica XXIV post Pentecosten', 'rank': 'sd'},
 '10/28/46': {'feast': 'Dominica XXV post Pentecosten', 'rank': 'sd'},
 '11/04/46': {'feast': 'Dominica XXVI post Pentecosten', 'rank': 'sd'},
 '11/11/46': {'feast': 'Dominica XXVII post Pentecosten', 'rank': 'sd'},
 '12/23/46': {'feast': 'Dominica IV Adventus', 'rank': 'sd2'},
 '12/16/46': {'feast': 'Dominica III Adventus', 'rank': 'sd2'},
 '12/19/46': {'feast': 'Feria IV Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/21/46': {'feast': 'Feria VI Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/22/46': {'feast': 'Sabbato Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/09/46': {'feast': 'Dominica II Adventus', 'rank': 'sd2'},
 '12/02/46': {'feast': 'Dominica I Adventus', 'rank': 'sd2'},
 '12/25/46': {'feast': 'Nativitas DNJC', 'rank': 'd1'},
 '12/30/46': {'feast': 'Dominica Infra Octavam Nativitatis', 'rank': 'sd'},
 '12/30/46': {'feast': 'De VI Die infra Octavam Nativitatis', 'rank': 'sd'},
 '12/26/46': {'feast': 'S Stephani Protomartyris', 'rank': 'd2'},
 '12/27/46': {'feast': 'S Joannis Ap & Ev', 'rank': 'd2'},
 '12/28/46': {'feast': 'Ss Innocentium Mm', 'rank': 'd2'},
 '12/29/46': {'feast': 'S Thomas EM', 'rank': 'd'},
 '12/31/46': {'feast': 'S Sylvestri I PC', 'rank': 'd'},
}
