temporal = {
 '01/01/82': {'feast': 'Circumcisio Domini et Oct Nativitatis', 'rank': 'd2'},
 '01/02/82': {'feast': 'Octava S Stephani Protomartyris', 'rank': 'sp'},
 '01/03/82': {'feast': 'Octava S Joannis Ap & Ev', 'rank': 'sp'},
 '01/04/82': {'feast': 'Octava Ss Innocentium Mm', 'rank': 'sp'},
 '01/02/82': {'feast': 'SS Nominis Jesu', 'rank': 'd2'},
 '02/19/82': {'feast': 'Dominica in Septuagesima', 'rank': 'sd2'},
 '02/26/82': {'feast': 'Dominica in Sexagesima', 'rank': 'sd2'},
 '03/05/82': {'feast': 'Dominica in Quinquagesima', 'rank': 'sd2'},
 '01/07/82': {'feast': 'De die II infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/09/82': {'feast': 'De die IV infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/10/82': {'feast': 'De die V infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/11/82': {'feast': 'De die VI infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/12/82': {'feast': 'De die VII infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/08/82': {'feast': 'S Familiæ Jesu Mariæ et Joseph; Dominica I post Epiphaniam', 'rank': 'dm'},
 '01/15/82': {'feast': 'Dominica II post Epiphaniam', 'rank': 'sp'},
 '01/22/82': {'feast': 'Dominica III post Epiphaniam', 'rank': 'sp'},
 '01/29/82': {'feast': 'Dominica IV post Epiphaniam', 'rank': 'sp'},
 '02/05/82': {'feast': 'Dominica V post Epiphaniam', 'rank': 'sp'},
 '02/12/82': {'feast': 'Dominica VI post Epiphaniam', 'rank': 'sp'},
 '03/08/82': {'feast': 'Dies Cinerum', 'rank': 'sp'},
 '03/08/82': {'feast': 'Feria V post Diem Cinerum', 'rank': 'sp'},
 '03/08/82': {'feast': 'Feria VI post Diem Cinerum', 'rank': 'sp'},
 '03/08/82': {'feast': 'Sabbato post Diem Cinerum', 'rank': 'sp'},
 '03/12/82': {'feast': 'Dominica I in Quadragesima', 'rank': 'sd1'},
 '03/13/82': {'feast': 'Feria II infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/14/82': {'feast': 'Feria III infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/15/82': {'feast': 'Feria IV Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/16/82': {'feast': 'Feria V infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/17/82': {'feast': 'Feria VI Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/18/82': {'feast': 'Sabbato Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/19/82': {'feast': 'Dominica II in Quadragesima', 'rank': 'sd1'},
 '03/20/82': {'feast': 'Feria II infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/21/82': {'feast': 'Feria III infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/22/82': {'feast': 'Feria IV infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/23/82': {'feast': 'Feria V infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/24/82': {'feast': 'Feria VI infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/25/82': {'feast': 'Sabbato infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/26/82': {'feast': 'Dominica III in Quadragesima', 'rank': 'sd1'},
 '03/27/82': {'feast': 'Feria II infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/28/82': {'feast': 'Feria III infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/29/82': {'feast': 'Feria IV infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/30/82': {'feast': 'Feria V infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/31/82': {'feast': 'Feria VI infra Hebd III in Quadragesima', 'rank': 'sp'},
 '04/01/82': {'feast': 'Sabbato infra Hebd III in Quadragesima', 'rank': 'sp'},
 '04/02/82': {'feast': 'Dominica IV in Quadragesima', 'rank': 'sd1'},
 '04/03/82': {'feast': 'Feria II infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/04/82': {'feast': 'Feria III infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/05/82': {'feast': 'Feria IV infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/06/82': {'feast': 'Feria V infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/07/82': {'feast': 'Feria VI infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/08/82': {'feast': 'Sabbato infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/09/82': {'feast': 'Dominica de Passione', 'rank': 'sd1'},
 '04/10/82': {'feast': 'Feria II infra Hebd de Passione', 'rank': 'sp'},
 '04/11/82': {'feast': 'Feria III infra Hebd de Passione', 'rank': 'sp'},
 '04/12/82': {'feast': 'Feria IV infra Hebd de Passione', 'rank': 'sp'},
 '04/13/82': {'feast': 'Feria V infra Hebd de Passione', 'rank': 'sp'},
 '04/14/82': {'feast': 'Septem Dolorum BMV', 'rank': 'dm'},
 '04/15/82': {'feast': 'Sabbato infra Hebd de Passione', 'rank': 'sp'},
 '04/16/82': {'feast': 'Dominica in Palmis', 'rank': 'sd1'},
 '04/17/82': {'feast': 'Feria II Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/18/82': {'feast': 'Feria III Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/19/82': {'feast': 'Feria IV Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/20/82': {'feast': 'Feria V in Cœna Domini', 'rank': 'd1'},
 '04/21/82': {'feast': 'Feria VI in Parasceve', 'rank': 'd1'},
 '04/22/82': {'feast': 'Sabbatum Sanctum', 'rank': 'd1'},
 '04/23/82': {'feast': 'Dominica Resurrectionis', 'rank': 'd1'},
 '04/24/82': {'feast': 'Feria II Paschatis', 'rank': 'd1'},
 '04/25/82': {'feast': 'Feria III Paschatis', 'rank': 'd1'},
 '04/26/82': {'feast': 'De die IV infra Oct Paschæ', 'rank': 'sd'},
 '04/27/82': {'feast': 'De die V infra Oct Paschæ', 'rank': 'sd'},
 '04/28/82': {'feast': 'De die VI infra Oct Paschæ', 'rank': 'sd'},
 '04/29/82': {'feast': 'Sabbatum in Albis', 'rank': 'sd'},
 '04/30/82': {'feast': 'Dominica in Albis', 'rank': 'sd'},
 '05/10/82': {'feast': 'Solemnitas S Joseph, Sponsi BMV C et Ecclesiæ Universalis Patroni', 'rank': 'd1'},
 '05/17/82': {'feast': 'Octava Solemnitas S Joseph', 'rank': 'dm'},
 '05/07/82': {'feast': 'Dominica II post Pascha', 'rank': 'sd'},
 '05/14/82': {'feast': 'Dominica III post Pascha', 'rank': 'sd'},
 '05/21/82': {'feast': 'Dominica IV post Pascha', 'rank': 'sd'},
 '05/29/82': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/30/82': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/31/82': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/31/82': {'feast': 'Vigilæ Ascensionis', 'rank': 'sp'},
 '06/01/82': {'feast': 'Ascensio DNJC', 'rank': 'd1'},
 '05/28/82': {'feast': 'Dominica V post Pascha', 'rank': 'sd'},
 '06/03/82': {'feast': 'De II die infra Oct Ascensionis', 'rank': 'sd'},
 '06/05/82': {'feast': 'De IV die infra Oct Ascensionis', 'rank': 'sd'},
 '06/06/82': {'feast': 'De V die infra Oct Ascensionis', 'rank': 'sd'},
 '06/07/82': {'feast': 'De VI die infra Oct Ascensionis', 'rank': 'sd'},
 '06/04/82': {'feast': 'Dominica infra Octavam Ascensionis', 'rank': 'sd'},
 '06/10/82': {'feast': 'Vigilia Pentecostes', 'rank': 'sd'},
 '06/11/82': {'feast': 'Dominica Pentecostes', 'rank': 'd1'},
 '06/03/82': {'feast': 'De II die infra Oct Pentecostes', 'rank': 'd1'},
 '06/04/82': {'feast': 'De III die infra Oct Pentecostes', 'rank': 'd1'},
 '06/05/82': {'feast': 'De IV die infra Oct Pentecostes', 'rank': 'd1'},
 '06/06/82': {'feast': 'De V die infra Oct Pentecostes', 'rank': 'd1'},
 '06/07/82': {'feast': 'De VI die infra Oct Pentecostes', 'rank': 'd1'},
 '06/08/82': {'feast': 'Sabbato die infra Oct Pentecostes', 'rank': 'd1'},
 '06/14/82': {'feast': 'Feria IV Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/16/82': {'feast': 'Feria VI Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/17/82': {'feast': 'Sabbato Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/18/82': {'feast': 'Dominica Sanctissimæ Trinitatis', 'rank': 'd1'},
 '06/23/82': {'feast': 'De II die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/24/82': {'feast': 'De III die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/26/82': {'feast': 'De V die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/27/82': {'feast': 'De VI die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/28/82': {'feast': 'De VII die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/22/82': {'feast': 'Sanctissimi Corporis Christi', 'rank': 'd1'},
 '06/29/82': {'feast': 'Octava SSmi Corporis Christi', 'rank': 'dm'},
 '06/25/82': {'feast': 'Dominica II post Pentecosten infra Octavam Corporis Christi', 'rank': 'sd'},
 '07/01/82': {'feast': 'De II die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '07/03/82': {'feast': 'De IV die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '07/04/82': {'feast': 'De V die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '07/05/82': {'feast': 'De VI die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '07/06/82': {'feast': 'De VII die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/30/82': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'd1'},
 '07/07/82': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'dm'},
 '07/02/82': {'feast': 'Dominica III post Pentecosten infra Octavam SSmi Cordis DNJC', 'rank': 'sd'},
 '07/09/82': {'feast': 'Dominica V post Pentecosten', 'rank': 'sd'},
 '07/16/82': {'feast': 'Dominica VI post Pentecosten', 'rank': 'sd'},
 '07/23/82': {'feast': 'Dominica VII post Pentecosten', 'rank': 'sd'},
 '07/30/82': {'feast': 'Dominica VIII post Pentecosten', 'rank': 'sd'},
 '08/06/82': {'feast': 'Dominica IX post Pentecosten', 'rank': 'sd'},
 '08/13/82': {'feast': 'Dominica X post Pentecosten', 'rank': 'sd'},
 '08/20/82': {'feast': 'Dominica XI post Pentecosten', 'rank': 'sd'},
 '08/27/82': {'feast': 'Dominica XII post Pentecosten', 'rank': 'sd'},
 '09/03/82': {'feast': 'Dominica XIII post Pentecosten', 'rank': 'sd'},
 '09/10/82': {'feast': 'Dominica XIV post Pentecosten', 'rank': 'sd'},
 '09/17/82': {'feast': 'Dominica XV post Pentecosten', 'rank': 'sd'},
 '09/20/82': {'feast': 'Feria IV Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/22/82': {'feast': 'Feria VI Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/23/82': {'feast': 'Sabbato Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/24/82': {'feast': 'Dominica XVI post Pentecosten', 'rank': 'sd'},
 '10/01/82': {'feast': 'Dominica XVII post Pentecosten', 'rank': 'sd'},
 '10/08/82': {'feast': 'Dominica XVIII post Pentecosten', 'rank': 'sd'},
 '10/15/82': {'feast': 'Dominica XIX post Pentecosten', 'rank': 'sd'},
 '10/22/82': {'feast': 'Dominica XX post Pentecosten', 'rank': 'sd'},
 '10/29/82': {'feast': 'Dominica XXI post Pentecosten', 'rank': 'sd'},
 '11/05/82': {'feast': 'Dominica XXII post Pentecosten', 'rank': 'sd'},
 '11/12/82': {'feast': 'Dominica XXIII post Pentecosten', 'rank': 'sd'},
 '11/19/82': {'feast': 'Dominica XXIV post Pentecosten', 'rank': 'sd'},
 '11/26/82': {'feast': 'Dominica XXV post Pentecosten', 'rank': 'sd'},
 '12/24/82': {'feast': 'Dominica IV Adventus', 'rank': 'sd2'},
 '12/17/82': {'feast': 'Dominica III Adventus', 'rank': 'sd2'},
 '12/20/82': {'feast': 'Feria IV Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/22/82': {'feast': 'Feria VI Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/23/82': {'feast': 'Sabbato Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/10/82': {'feast': 'Dominica II Adventus', 'rank': 'sd2'},
 '12/03/82': {'feast': 'Dominica I Adventus', 'rank': 'sd2'},
 '12/25/82': {'feast': 'Nativitas DNJC', 'rank': 'd1'},
 '12/31/82': {'feast': 'Dominica Infra Octavam Nativitatis', 'rank': 'sd'},
 '12/26/82': {'feast': 'S Stephani Protomartyris', 'rank': 'd2'},
 '12/27/82': {'feast': 'S Joannis Ap & Ev', 'rank': 'd2'},
 '12/28/82': {'feast': 'Ss Innocentium Mm', 'rank': 'd2'},
 '12/29/82': {'feast': 'S Thomas EM', 'rank': 'd'},
 '12/31/82': {'feast': 'S Sylvestri I PC', 'rank': 'd'},
}
