temporal = {
 '01/01/85': {'feast': 'Circumcisio Domini et Oct Nativitatis', 'rank': 'd2'},
 '01/02/85': {'feast': 'Octava S Stephani Protomartyris', 'rank': 'sp'},
 '01/03/85': {'feast': 'Octava S Joannis Ap & Ev', 'rank': 'sp'},
 '01/04/85': {'feast': 'Octava Ss Innocentium Mm', 'rank': 'sp'},
 '01/04/85': {'feast': 'SS Nominis Jesu', 'rank': 'd2'},
 '02/08/85': {'feast': 'Dominica in Septuagesima', 'rank': 'sd2'},
 '02/15/85': {'feast': 'Dominica in Sexagesima', 'rank': 'sd2'},
 '02/22/85': {'feast': 'Dominica in Quinquagesima', 'rank': 'sd2'},
 '01/07/85': {'feast': 'De die II infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/08/85': {'feast': 'De die III infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/09/85': {'feast': 'De die IV infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/10/85': {'feast': 'De die V infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/12/85': {'feast': 'De die VII infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/11/85': {'feast': 'S Familiæ Jesu Mariæ et Joseph; Dominica I post Epiphaniam', 'rank': 'dm'},
 '01/18/85': {'feast': 'Dominica II post Epiphaniam', 'rank': 'sp'},
 '01/25/85': {'feast': 'Dominica III post Epiphaniam', 'rank': 'sp'},
 '02/01/85': {'feast': 'Dominica IV post Epiphaniam', 'rank': 'sp'},
 '02/25/85': {'feast': 'Dies Cinerum', 'rank': 'sp'},
 '02/25/85': {'feast': 'Feria V post Diem Cinerum', 'rank': 'sp'},
 '02/25/85': {'feast': 'Feria VI post Diem Cinerum', 'rank': 'sp'},
 '02/25/85': {'feast': 'Sabbato post Diem Cinerum', 'rank': 'sp'},
 '03/01/85': {'feast': 'Dominica I in Quadragesima', 'rank': 'sd1'},
 '03/02/85': {'feast': 'Feria II infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/03/85': {'feast': 'Feria III infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/04/85': {'feast': 'Feria IV Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/05/85': {'feast': 'Feria V infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/06/85': {'feast': 'Feria VI Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/07/85': {'feast': 'Sabbato Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/08/85': {'feast': 'Dominica II in Quadragesima', 'rank': 'sd1'},
 '03/09/85': {'feast': 'Feria II infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/10/85': {'feast': 'Feria III infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/11/85': {'feast': 'Feria IV infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/12/85': {'feast': 'Feria V infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/13/85': {'feast': 'Feria VI infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/14/85': {'feast': 'Sabbato infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/15/85': {'feast': 'Dominica III in Quadragesima', 'rank': 'sd1'},
 '03/16/85': {'feast': 'Feria II infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/17/85': {'feast': 'Feria III infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/18/85': {'feast': 'Feria IV infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/19/85': {'feast': 'Feria V infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/20/85': {'feast': 'Feria VI infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/21/85': {'feast': 'Sabbato infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/22/85': {'feast': 'Dominica IV in Quadragesima', 'rank': 'sd1'},
 '03/23/85': {'feast': 'Feria II infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/24/85': {'feast': 'Feria III infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/25/85': {'feast': 'Feria IV infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/26/85': {'feast': 'Feria V infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/27/85': {'feast': 'Feria VI infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/28/85': {'feast': 'Sabbato infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/29/85': {'feast': 'Dominica de Passione', 'rank': 'sd1'},
 '03/30/85': {'feast': 'Feria II infra Hebd de Passione', 'rank': 'sp'},
 '03/31/85': {'feast': 'Feria III infra Hebd de Passione', 'rank': 'sp'},
 '04/01/85': {'feast': 'Feria IV infra Hebd de Passione', 'rank': 'sp'},
 '04/02/85': {'feast': 'Feria V infra Hebd de Passione', 'rank': 'sp'},
 '04/03/85': {'feast': 'Septem Dolorum BMV', 'rank': 'dm'},
 '04/04/85': {'feast': 'Sabbato infra Hebd de Passione', 'rank': 'sp'},
 '04/05/85': {'feast': 'Dominica in Palmis', 'rank': 'sd1'},
 '04/06/85': {'feast': 'Feria II Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/07/85': {'feast': 'Feria III Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/08/85': {'feast': 'Feria IV Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/09/85': {'feast': 'Feria V in Cœna Domini', 'rank': 'd1'},
 '04/10/85': {'feast': 'Feria VI in Parasceve', 'rank': 'd1'},
 '04/11/85': {'feast': 'Sabbatum Sanctum', 'rank': 'd1'},
 '04/12/85': {'feast': 'Dominica Resurrectionis', 'rank': 'd1'},
 '04/13/85': {'feast': 'Feria II Paschatis', 'rank': 'd1'},
 '04/14/85': {'feast': 'Feria III Paschatis', 'rank': 'd1'},
 '04/15/85': {'feast': 'De die IV infra Oct Paschæ', 'rank': 'sd'},
 '04/16/85': {'feast': 'De die V infra Oct Paschæ', 'rank': 'sd'},
 '04/17/85': {'feast': 'De die VI infra Oct Paschæ', 'rank': 'sd'},
 '04/18/85': {'feast': 'Sabbatum in Albis', 'rank': 'sd'},
 '04/19/85': {'feast': 'Dominica in Albis', 'rank': 'sd'},
 '04/29/85': {'feast': 'Solemnitas S Joseph, Sponsi BMV C et Ecclesiæ Universalis Patroni', 'rank': 'd1'},
 '05/06/85': {'feast': 'Octava Solemnitas S Joseph', 'rank': 'dm'},
 '04/26/85': {'feast': 'Dominica II post Pascha', 'rank': 'sd'},
 '05/03/85': {'feast': 'Dominica III post Pascha', 'rank': 'sd'},
 '05/10/85': {'feast': 'Dominica IV post Pascha', 'rank': 'sd'},
 '05/18/85': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/19/85': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/20/85': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/20/85': {'feast': 'Vigilæ Ascensionis', 'rank': 'sp'},
 '05/21/85': {'feast': 'Ascensio DNJC', 'rank': 'd1'},
 '05/17/85': {'feast': 'Dominica V post Pascha', 'rank': 'sd'},
 '05/23/85': {'feast': 'De II die infra Oct Ascensionis', 'rank': 'sd'},
 '05/25/85': {'feast': 'De IV die infra Oct Ascensionis', 'rank': 'sd'},
 '05/26/85': {'feast': 'De V die infra Oct Ascensionis', 'rank': 'sd'},
 '05/27/85': {'feast': 'De VI die infra Oct Ascensionis', 'rank': 'sd'},
 '05/24/85': {'feast': 'Dominica infra Octavam Ascensionis', 'rank': 'sd'},
 '05/30/85': {'feast': 'Vigilia Pentecostes', 'rank': 'sd'},
 '05/31/85': {'feast': 'Dominica Pentecostes', 'rank': 'd1'},
 '05/23/85': {'feast': 'De II die infra Oct Pentecostes', 'rank': 'd1'},
 '05/24/85': {'feast': 'De III die infra Oct Pentecostes', 'rank': 'd1'},
 '05/25/85': {'feast': 'De IV die infra Oct Pentecostes', 'rank': 'd1'},
 '05/26/85': {'feast': 'De V die infra Oct Pentecostes', 'rank': 'd1'},
 '05/27/85': {'feast': 'De VI die infra Oct Pentecostes', 'rank': 'd1'},
 '05/28/85': {'feast': 'Sabbato die infra Oct Pentecostes', 'rank': 'd1'},
 '06/03/85': {'feast': 'Feria IV Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/05/85': {'feast': 'Feria VI Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/06/85': {'feast': 'Sabbato Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/07/85': {'feast': 'Dominica Sanctissimæ Trinitatis', 'rank': 'd1'},
 '06/12/85': {'feast': 'De II die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/13/85': {'feast': 'De III die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/15/85': {'feast': 'De V die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/16/85': {'feast': 'De VI die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/17/85': {'feast': 'De VII die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/11/85': {'feast': 'Sanctissimi Corporis Christi', 'rank': 'd1'},
 '06/18/85': {'feast': 'Octava SSmi Corporis Christi', 'rank': 'dm'},
 '06/14/85': {'feast': 'Dominica II post Pentecosten infra Octavam Corporis Christi', 'rank': 'sd'},
 '06/20/85': {'feast': 'De II die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/22/85': {'feast': 'De IV die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/23/85': {'feast': 'De V die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/24/85': {'feast': 'De VI die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/25/85': {'feast': 'De VII die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/19/85': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'd1'},
 '06/26/85': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'dm'},
 '06/21/85': {'feast': 'Dominica III post Pentecosten infra Octavam SSmi Cordis DNJC', 'rank': 'sd'},
 '06/28/85': {'feast': 'Dominica V post Pentecosten', 'rank': 'sd'},
 '07/05/85': {'feast': 'Dominica VI post Pentecosten', 'rank': 'sd'},
 '07/12/85': {'feast': 'Dominica VII post Pentecosten', 'rank': 'sd'},
 '07/19/85': {'feast': 'Dominica VIII post Pentecosten', 'rank': 'sd'},
 '07/26/85': {'feast': 'Dominica IX post Pentecosten', 'rank': 'sd'},
 '08/02/85': {'feast': 'Dominica X post Pentecosten', 'rank': 'sd'},
 '08/09/85': {'feast': 'Dominica XI post Pentecosten', 'rank': 'sd'},
 '08/16/85': {'feast': 'Dominica XII post Pentecosten', 'rank': 'sd'},
 '08/23/85': {'feast': 'Dominica XIII post Pentecosten', 'rank': 'sd'},
 '08/30/85': {'feast': 'Dominica XIV post Pentecosten', 'rank': 'sd'},
 '09/06/85': {'feast': 'Dominica XV post Pentecosten', 'rank': 'sd'},
 '09/13/85': {'feast': 'Dominica XVI post Pentecosten', 'rank': 'sd'},
 '09/16/85': {'feast': 'Feria IV Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/18/85': {'feast': 'Feria VI Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/19/85': {'feast': 'Sabbato Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/20/85': {'feast': 'Dominica XVII post Pentecosten', 'rank': 'sd'},
 '09/27/85': {'feast': 'Dominica XVIII post Pentecosten', 'rank': 'sd'},
 '10/04/85': {'feast': 'Dominica XIX post Pentecosten', 'rank': 'sd'},
 '10/11/85': {'feast': 'Dominica XX post Pentecosten', 'rank': 'sd'},
 '10/18/85': {'feast': 'Dominica XXI post Pentecosten', 'rank': 'sd'},
 '10/25/85': {'feast': 'Dominica XXII post Pentecosten', 'rank': 'sd'},
 '11/01/85': {'feast': 'Dominica XXIII post Pentecosten', 'rank': 'sd'},
 '11/08/85': {'feast': 'Dominica XXIV post Pentecosten', 'rank': 'sd'},
 '11/15/85': {'feast': 'Dominica XXV post Pentecosten', 'rank': 'sd'},
 '11/22/85': {'feast': 'Dominica XXVI post Pentecosten', 'rank': 'sd'},
 '11/29/85': {'feast': 'Dominica XXVII post Pentecosten', 'rank': 'sd'},
 '12/20/85': {'feast': 'Dominica IV Adventus', 'rank': 'sd2'},
 '12/13/85': {'feast': 'Dominica III Adventus', 'rank': 'sd2'},
 '12/16/85': {'feast': 'Feria IV Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/18/85': {'feast': 'Feria VI Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/19/85': {'feast': 'Sabbato Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/06/85': {'feast': 'Dominica II Adventus', 'rank': 'sd2'},
 '11/29/85': {'feast': 'Dominica I Adventus', 'rank': 'sd2'},
 '12/25/85': {'feast': 'Nativitas DNJC', 'rank': 'd1'},
 '12/30/85': {'feast': 'Dominica Infra Octavam Nativitatis reposit', 'rank': 'sd'},
 '12/26/85': {'feast': 'S Stephani Protomartyris', 'rank': 'd2'},
 '12/27/85': {'feast': 'S Joannis Ap & Ev', 'rank': 'd2'},
 '12/28/85': {'feast': 'Ss Innocentium Mm', 'rank': 'd2'},
 '12/29/85': {'feast': 'S Thomas EM', 'rank': 'd'},
 '12/31/85': {'feast': 'S Sylvestri I PC', 'rank': 'd'},
}
