temporal = {
 '01/01/59': {'feast': 'Circumcisio Domini et Oct Nativitatis', 'rank': 'd2'},
 '01/02/59': {'feast': 'Octava S Stephani Protomartyris', 'rank': 'sp'},
 '01/03/59': {'feast': 'Octava S Joannis Ap & Ev', 'rank': 'sp'},
 '01/04/59': {'feast': 'Octava Ss Innocentium Mm', 'rank': 'sp'},
 '01/02/59': {'feast': 'SS Nominis Jesu', 'rank': 'd2'},
 '02/20/59': {'feast': 'Dominica in Septuagesima', 'rank': 'sd2'},
 '02/27/59': {'feast': 'Dominica in Sexagesima', 'rank': 'sd2'},
 '03/06/59': {'feast': 'Dominica in Quinquagesima', 'rank': 'sd2'},
 '01/07/59': {'feast': 'De die II infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/08/59': {'feast': 'De die III infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/10/59': {'feast': 'De die V infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/11/59': {'feast': 'De die VI infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/12/59': {'feast': 'De die VII infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/09/59': {'feast': 'S Familiæ Jesu Mariæ et Joseph; Dominica I post Epiphaniam', 'rank': 'dm'},
 '01/16/59': {'feast': 'Dominica II post Epiphaniam', 'rank': 'sp'},
 '01/23/59': {'feast': 'Dominica III post Epiphaniam', 'rank': 'sp'},
 '01/30/59': {'feast': 'Dominica IV post Epiphaniam', 'rank': 'sp'},
 '02/06/59': {'feast': 'Dominica V post Epiphaniam', 'rank': 'sp'},
 '02/13/59': {'feast': 'Dominica VI post Epiphaniam', 'rank': 'sp'},
 '03/09/59': {'feast': 'Dies Cinerum', 'rank': 'sp'},
 '03/09/59': {'feast': 'Feria V post Diem Cinerum', 'rank': 'sp'},
 '03/09/59': {'feast': 'Feria VI post Diem Cinerum', 'rank': 'sp'},
 '03/09/59': {'feast': 'Sabbato post Diem Cinerum', 'rank': 'sp'},
 '03/13/59': {'feast': 'Dominica I in Quadragesima', 'rank': 'sd1'},
 '03/14/59': {'feast': 'Feria II infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/15/59': {'feast': 'Feria III infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/16/59': {'feast': 'Feria IV Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/17/59': {'feast': 'Feria V infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/18/59': {'feast': 'Feria VI Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/19/59': {'feast': 'Sabbato Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/20/59': {'feast': 'Dominica II in Quadragesima', 'rank': 'sd1'},
 '03/21/59': {'feast': 'Feria II infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/22/59': {'feast': 'Feria III infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/23/59': {'feast': 'Feria IV infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/24/59': {'feast': 'Feria V infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/25/59': {'feast': 'Feria VI infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/26/59': {'feast': 'Sabbato infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/27/59': {'feast': 'Dominica III in Quadragesima', 'rank': 'sd1'},
 '03/28/59': {'feast': 'Feria II infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/29/59': {'feast': 'Feria III infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/30/59': {'feast': 'Feria IV infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/31/59': {'feast': 'Feria V infra Hebd III in Quadragesima', 'rank': 'sp'},
 '04/01/59': {'feast': 'Feria VI infra Hebd III in Quadragesima', 'rank': 'sp'},
 '04/02/59': {'feast': 'Sabbato infra Hebd III in Quadragesima', 'rank': 'sp'},
 '04/03/59': {'feast': 'Dominica IV in Quadragesima', 'rank': 'sd1'},
 '04/04/59': {'feast': 'Feria II infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/05/59': {'feast': 'Feria III infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/06/59': {'feast': 'Feria IV infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/07/59': {'feast': 'Feria V infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/08/59': {'feast': 'Feria VI infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/09/59': {'feast': 'Sabbato infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/10/59': {'feast': 'Dominica de Passione', 'rank': 'sd1'},
 '04/11/59': {'feast': 'Feria II infra Hebd de Passione', 'rank': 'sp'},
 '04/12/59': {'feast': 'Feria III infra Hebd de Passione', 'rank': 'sp'},
 '04/13/59': {'feast': 'Feria IV infra Hebd de Passione', 'rank': 'sp'},
 '04/14/59': {'feast': 'Feria V infra Hebd de Passione', 'rank': 'sp'},
 '04/15/59': {'feast': 'Septem Dolorum BMV', 'rank': 'dm'},
 '04/16/59': {'feast': 'Sabbato infra Hebd de Passione', 'rank': 'sp'},
 '04/17/59': {'feast': 'Dominica in Palmis', 'rank': 'sd1'},
 '04/18/59': {'feast': 'Feria II Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/19/59': {'feast': 'Feria III Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/20/59': {'feast': 'Feria IV Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/21/59': {'feast': 'Feria V in Cœna Domini', 'rank': 'd1'},
 '04/22/59': {'feast': 'Feria VI in Parasceve', 'rank': 'd1'},
 '04/23/59': {'feast': 'Sabbatum Sanctum', 'rank': 'd1'},
 '04/24/59': {'feast': 'Dominica Resurrectionis', 'rank': 'd1'},
 '04/25/59': {'feast': 'Feria II Paschatis', 'rank': 'd1'},
 '04/26/59': {'feast': 'Feria III Paschatis', 'rank': 'd1'},
 '04/27/59': {'feast': 'De die IV infra Oct Paschæ', 'rank': 'sd'},
 '04/28/59': {'feast': 'De die V infra Oct Paschæ', 'rank': 'sd'},
 '04/29/59': {'feast': 'De die VI infra Oct Paschæ', 'rank': 'sd'},
 '04/30/59': {'feast': 'Sabbatum in Albis', 'rank': 'sd'},
 '05/01/59': {'feast': 'Dominica in Albis', 'rank': 'sd'},
 '05/11/59': {'feast': 'Solemnitas S Joseph, Sponsi BMV C et Ecclesiæ Universalis Patroni', 'rank': 'd1'},
 '05/18/59': {'feast': 'Octava Solemnitas S Joseph', 'rank': 'dm'},
 '05/08/59': {'feast': 'Dominica II post Pascha', 'rank': 'sd'},
 '05/15/59': {'feast': 'Dominica III post Pascha', 'rank': 'sd'},
 '05/22/59': {'feast': 'Dominica IV post Pascha', 'rank': 'sd'},
 '05/30/59': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/31/59': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '06/01/59': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '06/01/59': {'feast': 'Vigilæ Ascensionis', 'rank': 'sp'},
 '06/02/59': {'feast': 'Ascensio DNJC', 'rank': 'd1'},
 '05/29/59': {'feast': 'Dominica V post Pascha', 'rank': 'sd'},
 '06/04/59': {'feast': 'De II die infra Oct Ascensionis', 'rank': 'sd'},
 '06/06/59': {'feast': 'De IV die infra Oct Ascensionis', 'rank': 'sd'},
 '06/07/59': {'feast': 'De V die infra Oct Ascensionis', 'rank': 'sd'},
 '06/08/59': {'feast': 'De VI die infra Oct Ascensionis', 'rank': 'sd'},
 '06/05/59': {'feast': 'Dominica infra Octavam Ascensionis', 'rank': 'sd'},
 '06/11/59': {'feast': 'Vigilia Pentecostes', 'rank': 'sd'},
 '06/12/59': {'feast': 'Dominica Pentecostes', 'rank': 'd1'},
 '06/04/59': {'feast': 'De II die infra Oct Pentecostes', 'rank': 'd1'},
 '06/05/59': {'feast': 'De III die infra Oct Pentecostes', 'rank': 'd1'},
 '06/06/59': {'feast': 'De IV die infra Oct Pentecostes', 'rank': 'd1'},
 '06/07/59': {'feast': 'De V die infra Oct Pentecostes', 'rank': 'd1'},
 '06/08/59': {'feast': 'De VI die infra Oct Pentecostes', 'rank': 'd1'},
 '06/09/59': {'feast': 'Sabbato die infra Oct Pentecostes', 'rank': 'd1'},
 '06/15/59': {'feast': 'Feria IV Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/17/59': {'feast': 'Feria VI Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/18/59': {'feast': 'Sabbato Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/19/59': {'feast': 'Dominica Sanctissimæ Trinitatis', 'rank': 'd1'},
 '06/24/59': {'feast': 'De II die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/25/59': {'feast': 'De III die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/27/59': {'feast': 'De V die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/28/59': {'feast': 'De VI die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/29/59': {'feast': 'De VII die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/23/59': {'feast': 'Sanctissimi Corporis Christi', 'rank': 'd1'},
 '06/30/59': {'feast': 'Octava SSmi Corporis Christi', 'rank': 'dm'},
 '06/26/59': {'feast': 'Dominica II post Pentecosten infra Octavam Corporis Christi', 'rank': 'sd'},
 '07/02/59': {'feast': 'De II die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '07/04/59': {'feast': 'De IV die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '07/05/59': {'feast': 'De V die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '07/06/59': {'feast': 'De VI die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '07/07/59': {'feast': 'De VII die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '07/01/59': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'd1'},
 '07/08/59': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'dm'},
 '07/03/59': {'feast': 'Dominica III post Pentecosten infra Octavam SSmi Cordis DNJC', 'rank': 'sd'},
 '07/10/59': {'feast': 'Dominica V post Pentecosten', 'rank': 'sd'},
 '07/17/59': {'feast': 'Dominica VI post Pentecosten', 'rank': 'sd'},
 '07/24/59': {'feast': 'Dominica VII post Pentecosten', 'rank': 'sd'},
 '07/31/59': {'feast': 'Dominica VIII post Pentecosten', 'rank': 'sd'},
 '08/07/59': {'feast': 'Dominica IX post Pentecosten', 'rank': 'sd'},
 '08/14/59': {'feast': 'Dominica X post Pentecosten', 'rank': 'sd'},
 '08/21/59': {'feast': 'Dominica XI post Pentecosten', 'rank': 'sd'},
 '08/28/59': {'feast': 'Dominica XII post Pentecosten', 'rank': 'sd'},
 '09/04/59': {'feast': 'Dominica XIII post Pentecosten', 'rank': 'sd'},
 '09/11/59': {'feast': 'Dominica XIV post Pentecosten', 'rank': 'sd'},
 '09/14/59': {'feast': 'Feria IV Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/16/59': {'feast': 'Feria VI Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/17/59': {'feast': 'Sabbato Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/18/59': {'feast': 'Dominica XV post Pentecosten', 'rank': 'sd'},
 '09/25/59': {'feast': 'Dominica XVI post Pentecosten', 'rank': 'sd'},
 '10/02/59': {'feast': 'Dominica XVII post Pentecosten', 'rank': 'sd'},
 '10/09/59': {'feast': 'Dominica XVIII post Pentecosten', 'rank': 'sd'},
 '10/16/59': {'feast': 'Dominica XIX post Pentecosten', 'rank': 'sd'},
 '10/23/59': {'feast': 'Dominica XX post Pentecosten', 'rank': 'sd'},
 '10/30/59': {'feast': 'Dominica XXI post Pentecosten', 'rank': 'sd'},
 '11/06/59': {'feast': 'Dominica XXII post Pentecosten', 'rank': 'sd'},
 '11/13/59': {'feast': 'Dominica XXIII post Pentecosten', 'rank': 'sd'},
 '11/20/59': {'feast': 'Dominica XXIV post Pentecosten', 'rank': 'sd'},
 '11/27/59': {'feast': 'Dominica XXV post Pentecosten', 'rank': 'sd'},
 '12/25/59': {'feast': 'Dominica IV Adventus', 'rank': 'sd2'},
 '12/18/59': {'feast': 'Dominica III Adventus', 'rank': 'sd2'},
 '12/21/59': {'feast': 'Feria IV Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/23/59': {'feast': 'Feria VI Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/24/59': {'feast': 'Sabbato Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/11/59': {'feast': 'Dominica II Adventus', 'rank': 'sd2'},
 '12/04/59': {'feast': 'Dominica I Adventus', 'rank': 'sd2'},
 '12/25/59': {'feast': 'Nativitas DNJC', 'rank': 'd1'},
 '12/30/59': {'feast': 'Dominica Infra Octavam Nativitatis reposit', 'rank': 'sd'},
 '12/26/59': {'feast': 'S Stephani Protomartyris', 'rank': 'd2'},
 '12/27/59': {'feast': 'S Joannis Ap & Ev', 'rank': 'd2'},
 '12/28/59': {'feast': 'Ss Innocentium Mm', 'rank': 'd2'},
 '12/29/59': {'feast': 'S Thomas EM', 'rank': 'd'},
 '12/31/59': {'feast': 'S Sylvestri I PC', 'rank': 'd'},
}
