temporal = {
 '01/01/73': {'feast': 'Circumcisio Domini et Oct Nativitatis', 'rank': 'd2'},
 '01/02/73': {'feast': 'Octava S Stephani Protomartyris', 'rank': 'sp'},
 '01/03/73': {'feast': 'Octava S Joannis Ap & Ev', 'rank': 'sp'},
 '01/04/73': {'feast': 'Octava Ss Innocentium Mm', 'rank': 'sp'},
 '01/02/73': {'feast': 'SS Nominis Jesu', 'rank': 'd2'},
 '01/22/73': {'feast': 'Dominica in Septuagesima', 'rank': 'sd2'},
 '01/29/73': {'feast': 'Dominica in Sexagesima', 'rank': 'sd2'},
 '02/05/73': {'feast': 'Dominica in Quinquagesima', 'rank': 'sd2'},
 '01/07/73': {'feast': 'De die II infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/09/73': {'feast': 'De die IV infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/10/73': {'feast': 'De die V infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/11/73': {'feast': 'De die VI infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/12/73': {'feast': 'De die VII infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/08/73': {'feast': 'S Familiæ Jesu Mariæ et Joseph; Dominica I post Epiphaniam', 'rank': 'dm'},
 '01/15/73': {'feast': 'Dominica II post Epiphaniam', 'rank': 'sp'},
 '02/08/73': {'feast': 'Dies Cinerum', 'rank': 'sp'},
 '02/08/73': {'feast': 'Feria V post Diem Cinerum', 'rank': 'sp'},
 '02/08/73': {'feast': 'Feria VI post Diem Cinerum', 'rank': 'sp'},
 '02/08/73': {'feast': 'Sabbato post Diem Cinerum', 'rank': 'sp'},
 '02/12/73': {'feast': 'Dominica I in Quadragesima', 'rank': 'sd1'},
 '02/13/73': {'feast': 'Feria II infra Hebd I in Quadragesima', 'rank': 'sp'},
 '02/14/73': {'feast': 'Feria III infra Hebd I in Quadragesima', 'rank': 'sp'},
 '02/15/73': {'feast': 'Feria IV Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '02/16/73': {'feast': 'Feria V infra Hebd I in Quadragesima', 'rank': 'sp'},
 '02/17/73': {'feast': 'Feria VI Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '02/18/73': {'feast': 'Sabbato Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '02/19/73': {'feast': 'Dominica II in Quadragesima', 'rank': 'sd1'},
 '02/20/73': {'feast': 'Feria II infra Hebd II in Quadragesima', 'rank': 'sp'},
 '02/21/73': {'feast': 'Feria III infra Hebd II in Quadragesima', 'rank': 'sp'},
 '02/22/73': {'feast': 'Feria IV infra Hebd II in Quadragesima', 'rank': 'sp'},
 '02/23/73': {'feast': 'Feria V infra Hebd II in Quadragesima', 'rank': 'sp'},
 '02/24/73': {'feast': 'Feria VI infra Hebd II in Quadragesima', 'rank': 'sp'},
 '02/25/73': {'feast': 'Sabbato infra Hebd II in Quadragesima', 'rank': 'sp'},
 '02/26/73': {'feast': 'Dominica III in Quadragesima', 'rank': 'sd1'},
 '02/27/73': {'feast': 'Feria II infra Hebd III in Quadragesima', 'rank': 'sp'},
 '02/28/73': {'feast': 'Feria III infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/01/73': {'feast': 'Feria IV infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/02/73': {'feast': 'Feria V infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/03/73': {'feast': 'Feria VI infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/04/73': {'feast': 'Sabbato infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/05/73': {'feast': 'Dominica IV in Quadragesima', 'rank': 'sd1'},
 '03/06/73': {'feast': 'Feria II infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/07/73': {'feast': 'Feria III infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/08/73': {'feast': 'Feria IV infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/09/73': {'feast': 'Feria V infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/10/73': {'feast': 'Feria VI infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/11/73': {'feast': 'Sabbato infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/12/73': {'feast': 'Dominica de Passione', 'rank': 'sd1'},
 '03/13/73': {'feast': 'Feria II infra Hebd de Passione', 'rank': 'sp'},
 '03/14/73': {'feast': 'Feria III infra Hebd de Passione', 'rank': 'sp'},
 '03/15/73': {'feast': 'Feria IV infra Hebd de Passione', 'rank': 'sp'},
 '03/16/73': {'feast': 'Feria V infra Hebd de Passione', 'rank': 'sp'},
 '03/17/73': {'feast': 'Septem Dolorum BMV', 'rank': 'dm'},
 '03/18/73': {'feast': 'Sabbato infra Hebd de Passione', 'rank': 'sp'},
 '03/19/73': {'feast': 'Dominica in Palmis', 'rank': 'sd1'},
 '03/20/73': {'feast': 'Feria II Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '03/21/73': {'feast': 'Feria III Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '03/22/73': {'feast': 'Feria IV Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '03/23/73': {'feast': 'Feria V in Cœna Domini', 'rank': 'd1'},
 '03/24/73': {'feast': 'Feria VI in Parasceve', 'rank': 'd1'},
 '03/25/73': {'feast': 'Sabbatum Sanctum', 'rank': 'd1'},
 '03/26/73': {'feast': 'Dominica Resurrectionis', 'rank': 'd1'},
 '03/27/73': {'feast': 'Feria II Paschatis', 'rank': 'd1'},
 '03/28/73': {'feast': 'Feria III Paschatis', 'rank': 'd1'},
 '03/29/73': {'feast': 'De die IV infra Oct Paschæ', 'rank': 'sd'},
 '03/30/73': {'feast': 'De die V infra Oct Paschæ', 'rank': 'sd'},
 '03/31/73': {'feast': 'De die VI infra Oct Paschæ', 'rank': 'sd'},
 '04/01/73': {'feast': 'Sabbatum in Albis', 'rank': 'sd'},
 '04/02/73': {'feast': 'Dominica in Albis', 'rank': 'sd'},
 '04/12/73': {'feast': 'Solemnitas S Joseph, Sponsi BMV C et Ecclesiæ Universalis Patroni', 'rank': 'd1'},
 '04/19/73': {'feast': 'Octava Solemnitas S Joseph', 'rank': 'dm'},
 '04/09/73': {'feast': 'Dominica II post Pascha', 'rank': 'sd'},
 '04/16/73': {'feast': 'Dominica III post Pascha', 'rank': 'sd'},
 '04/23/73': {'feast': 'Dominica IV post Pascha', 'rank': 'sd'},
 '05/01/73': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/02/73': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/03/73': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/03/73': {'feast': 'Vigilæ Ascensionis', 'rank': 'sp'},
 '05/04/73': {'feast': 'Ascensio DNJC', 'rank': 'd1'},
 '04/30/73': {'feast': 'Dominica V post Pascha', 'rank': 'sd'},
 '05/06/73': {'feast': 'De II die infra Oct Ascensionis', 'rank': 'sd'},
 '05/08/73': {'feast': 'De IV die infra Oct Ascensionis', 'rank': 'sd'},
 '05/09/73': {'feast': 'De V die infra Oct Ascensionis', 'rank': 'sd'},
 '05/10/73': {'feast': 'De VI die infra Oct Ascensionis', 'rank': 'sd'},
 '05/07/73': {'feast': 'Dominica infra Octavam Ascensionis', 'rank': 'sd'},
 '05/13/73': {'feast': 'Vigilia Pentecostes', 'rank': 'sd'},
 '05/14/73': {'feast': 'Dominica Pentecostes', 'rank': 'd1'},
 '05/06/73': {'feast': 'De II die infra Oct Pentecostes', 'rank': 'd1'},
 '05/07/73': {'feast': 'De III die infra Oct Pentecostes', 'rank': 'd1'},
 '05/08/73': {'feast': 'De IV die infra Oct Pentecostes', 'rank': 'd1'},
 '05/09/73': {'feast': 'De V die infra Oct Pentecostes', 'rank': 'd1'},
 '05/10/73': {'feast': 'De VI die infra Oct Pentecostes', 'rank': 'd1'},
 '05/11/73': {'feast': 'Sabbato die infra Oct Pentecostes', 'rank': 'd1'},
 '05/17/73': {'feast': 'Feria IV Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '05/19/73': {'feast': 'Feria VI Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '05/20/73': {'feast': 'Sabbato Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '05/21/73': {'feast': 'Dominica Sanctissimæ Trinitatis', 'rank': 'd1'},
 '05/26/73': {'feast': 'De II die infra Oct Corporis Christi', 'rank': 'sd'},
 '05/27/73': {'feast': 'De III die infra Oct Corporis Christi', 'rank': 'sd'},
 '05/29/73': {'feast': 'De V die infra Oct Corporis Christi', 'rank': 'sd'},
 '05/30/73': {'feast': 'De VI die infra Oct Corporis Christi', 'rank': 'sd'},
 '05/31/73': {'feast': 'De VII die infra Oct Corporis Christi', 'rank': 'sd'},
 '05/25/73': {'feast': 'Sanctissimi Corporis Christi', 'rank': 'd1'},
 '06/01/73': {'feast': 'Octava SSmi Corporis Christi', 'rank': 'dm'},
 '05/28/73': {'feast': 'Dominica II post Pentecosten infra Octavam Corporis Christi', 'rank': 'sd'},
 '06/03/73': {'feast': 'De II die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/05/73': {'feast': 'De IV die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/06/73': {'feast': 'De V die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/07/73': {'feast': 'De VI die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/08/73': {'feast': 'De VII die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/02/73': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'd1'},
 '06/09/73': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'dm'},
 '06/04/73': {'feast': 'Dominica III post Pentecosten infra Octavam SSmi Cordis DNJC', 'rank': 'sd'},
 '06/11/73': {'feast': 'Dominica V post Pentecosten', 'rank': 'sd'},
 '06/18/73': {'feast': 'Dominica VI post Pentecosten', 'rank': 'sd'},
 '06/25/73': {'feast': 'Dominica VII post Pentecosten', 'rank': 'sd'},
 '07/02/73': {'feast': 'Dominica VIII post Pentecosten', 'rank': 'sd'},
 '07/09/73': {'feast': 'Dominica IX post Pentecosten', 'rank': 'sd'},
 '07/16/73': {'feast': 'Dominica X post Pentecosten', 'rank': 'sd'},
 '07/23/73': {'feast': 'Dominica XI post Pentecosten', 'rank': 'sd'},
 '07/30/73': {'feast': 'Dominica XII post Pentecosten', 'rank': 'sd'},
 '08/06/73': {'feast': 'Dominica XIII post Pentecosten', 'rank': 'sd'},
 '08/13/73': {'feast': 'Dominica XIV post Pentecosten', 'rank': 'sd'},
 '08/20/73': {'feast': 'Dominica XV post Pentecosten', 'rank': 'sd'},
 '08/27/73': {'feast': 'Dominica XVI post Pentecosten', 'rank': 'sd'},
 '09/03/73': {'feast': 'Dominica XVII post Pentecosten', 'rank': 'sd'},
 '09/10/73': {'feast': 'Dominica XVIII post Pentecosten', 'rank': 'sd'},
 '09/17/73': {'feast': 'Dominica XIX post Pentecosten', 'rank': 'sd'},
 '09/20/73': {'feast': 'Feria IV Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/22/73': {'feast': 'Feria VI Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/23/73': {'feast': 'Sabbato Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/24/73': {'feast': 'Dominica XX post Pentecosten', 'rank': 'sd'},
 '10/01/73': {'feast': 'Dominica XXI post Pentecosten', 'rank': 'sd'},
 '10/08/73': {'feast': 'Dominica XXII post Pentecosten', 'rank': 'sd'},
 '10/15/73': {'feast': 'Dominica XXIII post Pentecosten', 'rank': 'sd'},
 '10/22/73': {'feast': 'Dominica XXIV post Pentecosten', 'rank': 'sd'},
 '10/29/73': {'feast': 'Dominica XXV post Pentecosten', 'rank': 'sd'},
 '11/05/73': {'feast': 'Dominica XXVI post Pentecosten', 'rank': 'sd'},
 '11/12/73': {'feast': 'Dominica XXVII post Pentecosten', 'rank': 'sd'},
 '12/24/73': {'feast': 'Dominica IV Adventus', 'rank': 'sd2'},
 '12/17/73': {'feast': 'Dominica III Adventus', 'rank': 'sd2'},
 '12/20/73': {'feast': 'Feria IV Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/22/73': {'feast': 'Feria VI Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/23/73': {'feast': 'Sabbato Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/10/73': {'feast': 'Dominica II Adventus', 'rank': 'sd2'},
 '12/03/73': {'feast': 'Dominica I Adventus', 'rank': 'sd2'},
 '12/25/73': {'feast': 'Nativitas DNJC', 'rank': 'd1'},
 '12/31/73': {'feast': 'Dominica Infra Octavam Nativitatis', 'rank': 'sd'},
 '12/26/73': {'feast': 'S Stephani Protomartyris', 'rank': 'd2'},
 '12/27/73': {'feast': 'S Joannis Ap & Ev', 'rank': 'd2'},
 '12/28/73': {'feast': 'Ss Innocentium Mm', 'rank': 'd2'},
 '12/29/73': {'feast': 'S Thomas EM', 'rank': 'd'},
 '12/31/73': {'feast': 'S Sylvestri I PC', 'rank': 'd'},
}
