temporal = {
 '01/01/01': {'feast': 'Circumcisio Domini et Oct Nativitatis', 'rank': 'd2'},
 '01/02/01': {'feast': 'Octava S Stephani Protomartyris', 'rank': 'sp'},
 '01/03/01': {'feast': 'Octava S Joannis Ap & Ev', 'rank': 'sp'},
 '01/04/01': {'feast': 'Octava Ss Innocentium Mm', 'rank': 'sp'},
 '01/02/01': {'feast': 'SS Nominis Jesu', 'rank': 'd2'},
 '02/17/01': {'feast': 'Dominica in Septuagesima', 'rank': 'sd2'},
 '02/24/01': {'feast': 'Dominica in Sexagesima', 'rank': 'sd2'},
 '03/03/01': {'feast': 'Dominica in Quinquagesima', 'rank': 'sd2'},
 '01/06/01': {'feast': 'Epiphania Domini', 'rank': 'd1'},
 '01/07/01': {'feast': 'De die II infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/08/01': {'feast': 'De die III infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/09/01': {'feast': 'De die IV infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/10/01': {'feast': 'De die V infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/11/01': {'feast': 'De die VI infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/12/01': {'feast': 'De die VII infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/13/01': {'feast': 'Octava Epiphaniæ; Dominica I post Epiphaniam', 'rank': 'dm'},
 '01/12/01': {'feast': 'S Familiæ Jesu Mariæ et Joseph', 'rank': 'dm'},
 '01/20/01': {'feast': 'Dominica II post Epiphaniam', 'rank': 'sp'},
 '01/27/01': {'feast': 'Dominica III post Epiphaniam', 'rank': 'sp'},
 '02/03/01': {'feast': 'Dominica IV post Epiphaniam', 'rank': 'sp'},
 '02/10/01': {'feast': 'Dominica V post Epiphaniam', 'rank': 'sp'},
 '03/06/01': {'feast': 'Dies Cinerum', 'rank': 'sp'},
 '03/06/01': {'feast': 'Feria V post Diem Cinerum', 'rank': 'sp'},
 '03/06/01': {'feast': 'Feria VI post Diem Cinerum', 'rank': 'sp'},
 '03/06/01': {'feast': 'Sabbato post Diem Cinerum', 'rank': 'sp'},
 '03/10/01': {'feast': 'Dominica I in Quadragesima', 'rank': 'sd1'},
 '03/11/01': {'feast': 'Feria II infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/12/01': {'feast': 'Feria III infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/13/01': {'feast': 'Feria IV Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/14/01': {'feast': 'Feria V infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/15/01': {'feast': 'Feria VI Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/16/01': {'feast': 'Sabbato Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/17/01': {'feast': 'Dominica II in Quadragesima', 'rank': 'sd1'},
 '03/18/01': {'feast': 'Feria II infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/19/01': {'feast': 'Feria III infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/20/01': {'feast': 'Feria IV infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/21/01': {'feast': 'Feria V infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/22/01': {'feast': 'Feria VI infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/23/01': {'feast': 'Sabbato infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/24/01': {'feast': 'Dominica III in Quadragesima', 'rank': 'sd1'},
 '03/25/01': {'feast': 'Feria II infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/26/01': {'feast': 'Feria III infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/27/01': {'feast': 'Feria IV infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/28/01': {'feast': 'Feria V infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/29/01': {'feast': 'Feria VI infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/30/01': {'feast': 'Sabbato infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/31/01': {'feast': 'Dominica IV in Quadragesima', 'rank': 'sd1'},
 '04/01/01': {'feast': 'Feria II infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/02/01': {'feast': 'Feria III infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/03/01': {'feast': 'Feria IV infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/04/01': {'feast': 'Feria V infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/05/01': {'feast': 'Feria VI infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/06/01': {'feast': 'Sabbato infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '04/07/01': {'feast': 'Dominica de Passione', 'rank': 'sd1'},
 '04/08/01': {'feast': 'Feria II infra Hebd de Passione', 'rank': 'sp'},
 '04/09/01': {'feast': 'Feria III infra Hebd de Passione', 'rank': 'sp'},
 '04/10/01': {'feast': 'Feria IV infra Hebd de Passione', 'rank': 'sp'},
 '04/11/01': {'feast': 'Feria V infra Hebd de Passione', 'rank': 'sp'},
 '04/12/01': {'feast': 'Septem Dolorum BMV', 'rank': 'dm'},
 '04/13/01': {'feast': 'Sabbato infra Hebd de Passione', 'rank': 'sp'},
 '04/14/01': {'feast': 'Dominica in Palmis', 'rank': 'sd1'},
 '04/15/01': {'feast': 'Feria II Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/16/01': {'feast': 'Feria III Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/17/01': {'feast': 'Feria IV Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/18/01': {'feast': 'Feria V in Cœna Domini', 'rank': 'd1'},
 '04/19/01': {'feast': 'Feria VI in Parasceve', 'rank': 'd1'},
 '04/20/01': {'feast': 'Sabbatum Sanctum', 'rank': 'd1'},
 '04/21/01': {'feast': 'Dominica Resurrectionis', 'rank': 'd1'},
 '04/22/01': {'feast': 'Feria II Paschatis', 'rank': 'd1'},
 '04/23/01': {'feast': 'Feria III Paschatis', 'rank': 'd1'},
 '04/24/01': {'feast': 'De die IV infra Oct Paschæ', 'rank': 'sd'},
 '04/25/01': {'feast': 'De die V infra Oct Paschæ', 'rank': 'sd'},
 '04/26/01': {'feast': 'De die VI infra Oct Paschæ', 'rank': 'sd'},
 '04/27/01': {'feast': 'Sabbatum in Albis', 'rank': 'sd'},
 '04/28/01': {'feast': 'Dominica in Albis', 'rank': 'sd'},
 '05/08/01': {'feast': 'Solemnitas S Joseph, Sponsi BMV C et Ecclesiæ Universalis Patroni', 'rank': 'd1'},
 '05/15/01': {'feast': 'Octava Solemnitas S Joseph', 'rank': 'dm'},
 '05/05/01': {'feast': 'Dominica II post Pascha', 'rank': 'sd'},
 '05/12/01': {'feast': 'Dominica III post Pascha', 'rank': 'sd'},
 '05/19/01': {'feast': 'Dominica IV post Pascha', 'rank': 'sd'},
 '05/27/01': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/28/01': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/29/01': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/29/01': {'feast': 'Vigilæ Ascensionis', 'rank': 'sp'},
 '05/30/01': {'feast': 'Ascensio DNJC', 'rank': 'd1'},
 '05/26/01': {'feast': 'Dominica V post Pascha', 'rank': 'sd'},
 '06/01/01': {'feast': 'De II die infra Oct Ascensionis', 'rank': 'sd'},
 '06/03/01': {'feast': 'De IV die infra Oct Ascensionis', 'rank': 'sd'},
 '06/04/01': {'feast': 'De V die infra Oct Ascensionis', 'rank': 'sd'},
 '06/05/01': {'feast': 'De VI die infra Oct Ascensionis', 'rank': 'sd'},
 '06/02/01': {'feast': 'Dominica infra Octavam Ascensionis', 'rank': 'sd'},
 '06/08/01': {'feast': 'Vigilia Pentecostes', 'rank': 'sd'},
 '06/09/01': {'feast': 'Dominica Pentecostes', 'rank': 'd1'},
 '06/01/01': {'feast': 'De II die infra Oct Pentecostes', 'rank': 'd1'},
 '06/02/01': {'feast': 'De III die infra Oct Pentecostes', 'rank': 'd1'},
 '06/03/01': {'feast': 'De IV die infra Oct Pentecostes', 'rank': 'd1'},
 '06/04/01': {'feast': 'De V die infra Oct Pentecostes', 'rank': 'd1'},
 '06/05/01': {'feast': 'De VI die infra Oct Pentecostes', 'rank': 'd1'},
 '06/06/01': {'feast': 'Sabbato die infra Oct Pentecostes', 'rank': 'd1'},
 '06/12/01': {'feast': 'Feria IV Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/14/01': {'feast': 'Feria VI Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/15/01': {'feast': 'Sabbato Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/16/01': {'feast': 'Dominica Sanctissimæ Trinitatis', 'rank': 'd1'},
 '06/21/01': {'feast': 'De II die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/22/01': {'feast': 'De III die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/24/01': {'feast': 'De V die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/25/01': {'feast': 'De VI die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/26/01': {'feast': 'De VII die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/20/01': {'feast': 'Sanctissimi Corporis Christi', 'rank': 'd1'},
 '06/27/01': {'feast': 'Octava SSmi Corporis Christi', 'rank': 'dm'},
 '06/23/01': {'feast': 'Dominica II post Pentecosten infra Octavam Corporis Christi', 'rank': 'sd'},
 '06/29/01': {'feast': 'De II die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '07/01/01': {'feast': 'De IV die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '07/02/01': {'feast': 'De V die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '07/03/01': {'feast': 'De VI die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '07/04/01': {'feast': 'De VII die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/28/01': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'd1'},
 '07/05/01': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'dm'},
 '06/30/01': {'feast': 'Dominica III post Pentecosten infra Octavam SSmi Cordis DNJC', 'rank': 'sd'},
 '07/07/01': {'feast': 'Dominica V post Pentecosten', 'rank': 'sd'},
 '07/14/01': {'feast': 'Dominica VI post Pentecosten', 'rank': 'sd'},
 '07/21/01': {'feast': 'Dominica VII post Pentecosten', 'rank': 'sd'},
 '07/28/01': {'feast': 'Dominica VIII post Pentecosten', 'rank': 'sd'},
 '08/04/01': {'feast': 'Dominica IX post Pentecosten', 'rank': 'sd'},
 '08/11/01': {'feast': 'Dominica X post Pentecosten', 'rank': 'sd'},
 '08/18/01': {'feast': 'Dominica XI post Pentecosten', 'rank': 'sd'},
 '08/25/01': {'feast': 'Dominica XII post Pentecosten', 'rank': 'sd'},
 '09/01/01': {'feast': 'Dominica XIII post Pentecosten', 'rank': 'sd'},
 '09/08/01': {'feast': 'Dominica XIV post Pentecosten', 'rank': 'sd'},
 '09/15/01': {'feast': 'Dominica XV post Pentecosten', 'rank': 'sd'},
 '09/18/01': {'feast': 'Feria IV Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/20/01': {'feast': 'Feria VI Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/21/01': {'feast': 'Sabbato Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/22/01': {'feast': 'Dominica XVI post Pentecosten', 'rank': 'sd'},
 '09/29/01': {'feast': 'Dominica XVII post Pentecosten', 'rank': 'sd'},
 '10/06/01': {'feast': 'Dominica XVIII post Pentecosten', 'rank': 'sd'},
 '10/13/01': {'feast': 'Dominica XIX post Pentecosten', 'rank': 'sd'},
 '10/20/01': {'feast': 'Dominica XX post Pentecosten', 'rank': 'sd'},
 '10/27/01': {'feast': 'Dominica XXI post Pentecosten', 'rank': 'sd'},
 '11/03/01': {'feast': 'Dominica XXII post Pentecosten', 'rank': 'sd'},
 '11/10/01': {'feast': 'Dominica XXIII post Pentecosten', 'rank': 'sd'},
 '11/17/01': {'feast': 'Dominica XXIV post Pentecosten', 'rank': 'sd'},
 '11/24/01': {'feast': 'Dominica XXV post Pentecosten', 'rank': 'sd'},
 '12/01/01': {'feast': 'Dominica XXVI post Pentecosten', 'rank': 'sd'},
 '12/22/01': {'feast': 'Dominica IV Adventus', 'rank': 'sd2'},
 '12/15/01': {'feast': 'Dominica III Adventus', 'rank': 'sd2'},
 '12/18/01': {'feast': 'Feria IV Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/20/01': {'feast': 'Feria VI Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/21/01': {'feast': 'Sabbato Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/08/01': {'feast': 'Dominica II Adventus', 'rank': 'sd2'},
 '12/01/01': {'feast': 'Dominica I Adventus', 'rank': 'sd2'},
 '12/25/01': {'feast': 'Nativitas DNJC', 'rank': 'd1'},
 '12/29/01': {'feast': 'Dominica Infra Octavam Nativitatis', 'rank': 'sd'},
 '12/30/01': {'feast': 'De VI Die infra Octavam Nativitatis', 'rank': 'sd'},
 '12/26/01': {'feast': 'S Stephani Protomartyris', 'rank': 'd2'},
 '12/27/01': {'feast': 'S Joannis Ap & Ev', 'rank': 'd2'},
 '12/28/01': {'feast': 'Ss Innocentium Mm', 'rank': 'd2'},
 '12/29/01': {'feast': 'S Thomas EM', 'rank': 'd'},
 '12/31/01': {'feast': 'S Sylvestri I PC', 'rank': 'd'},
}
