temporal = {
 '01/01/03': {'feast': 'Circumcisio Domini et Oct Nativitatis', 'rank': 'd2'},
 '01/02/03': {'feast': 'Octava S Stephani Protomartyris', 'rank': 'sp'},
 '01/03/03': {'feast': 'Octava S Joannis Ap & Ev', 'rank': 'sp'},
 '01/04/03': {'feast': 'Octava Ss Innocentium Mm', 'rank': 'sp'},
 '01/04/03': {'feast': 'SS Nominis Jesu', 'rank': 'd2'},
 '01/18/03': {'feast': 'Dominica in Septuagesima', 'rank': 'sd2'},
 '01/25/03': {'feast': 'Dominica in Sexagesima', 'rank': 'sd2'},
 '02/01/03': {'feast': 'Dominica in Quinquagesima', 'rank': 'sd2'},
 '01/07/03': {'feast': 'De die II infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/08/03': {'feast': 'De die III infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/09/03': {'feast': 'De die IV infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/10/03': {'feast': 'De die V infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/12/03': {'feast': 'De die VII infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/11/03': {'feast': 'S Familiæ Jesu Mariæ et Joseph; Dominica I post Epiphaniam', 'rank': 'dm'},
 '02/04/03': {'feast': 'Dies Cinerum', 'rank': 'sp'},
 '02/04/03': {'feast': 'Feria V post Diem Cinerum', 'rank': 'sp'},
 '02/04/03': {'feast': 'Feria VI post Diem Cinerum', 'rank': 'sp'},
 '02/04/03': {'feast': 'Sabbato post Diem Cinerum', 'rank': 'sp'},
 '02/08/03': {'feast': 'Dominica I in Quadragesima', 'rank': 'sd1'},
 '02/09/03': {'feast': 'Feria II infra Hebd I in Quadragesima', 'rank': 'sp'},
 '02/10/03': {'feast': 'Feria III infra Hebd I in Quadragesima', 'rank': 'sp'},
 '02/11/03': {'feast': 'Feria IV Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '02/12/03': {'feast': 'Feria V infra Hebd I in Quadragesima', 'rank': 'sp'},
 '02/13/03': {'feast': 'Feria VI Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '02/14/03': {'feast': 'Sabbato Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '02/15/03': {'feast': 'Dominica II in Quadragesima', 'rank': 'sd1'},
 '02/16/03': {'feast': 'Feria II infra Hebd II in Quadragesima', 'rank': 'sp'},
 '02/17/03': {'feast': 'Feria III infra Hebd II in Quadragesima', 'rank': 'sp'},
 '02/18/03': {'feast': 'Feria IV infra Hebd II in Quadragesima', 'rank': 'sp'},
 '02/19/03': {'feast': 'Feria V infra Hebd II in Quadragesima', 'rank': 'sp'},
 '02/20/03': {'feast': 'Feria VI infra Hebd II in Quadragesima', 'rank': 'sp'},
 '02/21/03': {'feast': 'Sabbato infra Hebd II in Quadragesima', 'rank': 'sp'},
 '02/22/03': {'feast': 'Dominica III in Quadragesima', 'rank': 'sd1'},
 '02/23/03': {'feast': 'Feria II infra Hebd III in Quadragesima', 'rank': 'sp'},
 '02/24/03': {'feast': 'Feria III infra Hebd III in Quadragesima', 'rank': 'sp'},
 '02/25/03': {'feast': 'Feria IV infra Hebd III in Quadragesima', 'rank': 'sp'},
 '02/26/03': {'feast': 'Feria V infra Hebd III in Quadragesima', 'rank': 'sp'},
 '02/27/03': {'feast': 'Feria VI infra Hebd III in Quadragesima', 'rank': 'sp'},
 '02/28/03': {'feast': 'Sabbato infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/01/03': {'feast': 'Dominica IV in Quadragesima', 'rank': 'sd1'},
 '03/02/03': {'feast': 'Feria II infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/03/03': {'feast': 'Feria III infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/04/03': {'feast': 'Feria IV infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/05/03': {'feast': 'Feria V infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/06/03': {'feast': 'Feria VI infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/07/03': {'feast': 'Sabbato infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/08/03': {'feast': 'Dominica de Passione', 'rank': 'sd1'},
 '03/09/03': {'feast': 'Feria II infra Hebd de Passione', 'rank': 'sp'},
 '03/10/03': {'feast': 'Feria III infra Hebd de Passione', 'rank': 'sp'},
 '03/11/03': {'feast': 'Feria IV infra Hebd de Passione', 'rank': 'sp'},
 '03/12/03': {'feast': 'Feria V infra Hebd de Passione', 'rank': 'sp'},
 '03/13/03': {'feast': 'Septem Dolorum BMV', 'rank': 'dm'},
 '03/14/03': {'feast': 'Sabbato infra Hebd de Passione', 'rank': 'sp'},
 '03/15/03': {'feast': 'Dominica in Palmis', 'rank': 'sd1'},
 '03/16/03': {'feast': 'Feria II Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '03/17/03': {'feast': 'Feria III Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '03/18/03': {'feast': 'Feria IV Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '03/19/03': {'feast': 'Feria V in Cœna Domini', 'rank': 'd1'},
 '03/20/03': {'feast': 'Feria VI in Parasceve', 'rank': 'd1'},
 '03/21/03': {'feast': 'Sabbatum Sanctum', 'rank': 'd1'},
 '03/22/03': {'feast': 'Dominica Resurrectionis', 'rank': 'd1'},
 '03/23/03': {'feast': 'Feria II Paschatis', 'rank': 'd1'},
 '03/24/03': {'feast': 'Feria III Paschatis', 'rank': 'd1'},
 '03/25/03': {'feast': 'De die IV infra Oct Paschæ', 'rank': 'sd'},
 '03/26/03': {'feast': 'De die V infra Oct Paschæ', 'rank': 'sd'},
 '03/27/03': {'feast': 'De die VI infra Oct Paschæ', 'rank': 'sd'},
 '03/28/03': {'feast': 'Sabbatum in Albis', 'rank': 'sd'},
 '03/29/03': {'feast': 'Dominica in Albis', 'rank': 'sd'},
 '04/08/03': {'feast': 'Solemnitas S Joseph, Sponsi BMV C et Ecclesiæ Universalis Patroni', 'rank': 'd1'},
 '04/15/03': {'feast': 'Octava Solemnitas S Joseph', 'rank': 'dm'},
 '04/05/03': {'feast': 'Dominica II post Pascha', 'rank': 'sd'},
 '04/12/03': {'feast': 'Dominica III post Pascha', 'rank': 'sd'},
 '04/19/03': {'feast': 'Dominica IV post Pascha', 'rank': 'sd'},
 '04/27/03': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '04/28/03': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '04/29/03': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '04/29/03': {'feast': 'Vigilæ Ascensionis', 'rank': 'sp'},
 '04/30/03': {'feast': 'Ascensio DNJC', 'rank': 'd1'},
 '04/26/03': {'feast': 'Dominica V post Pascha', 'rank': 'sd'},
 '05/02/03': {'feast': 'De II die infra Oct Ascensionis', 'rank': 'sd'},
 '05/04/03': {'feast': 'De IV die infra Oct Ascensionis', 'rank': 'sd'},
 '05/05/03': {'feast': 'De V die infra Oct Ascensionis', 'rank': 'sd'},
 '05/06/03': {'feast': 'De VI die infra Oct Ascensionis', 'rank': 'sd'},
 '05/03/03': {'feast': 'Dominica infra Octavam Ascensionis', 'rank': 'sd'},
 '05/09/03': {'feast': 'Vigilia Pentecostes', 'rank': 'sd'},
 '05/10/03': {'feast': 'Dominica Pentecostes', 'rank': 'd1'},
 '05/02/03': {'feast': 'De II die infra Oct Pentecostes', 'rank': 'd1'},
 '05/03/03': {'feast': 'De III die infra Oct Pentecostes', 'rank': 'd1'},
 '05/04/03': {'feast': 'De IV die infra Oct Pentecostes', 'rank': 'd1'},
 '05/05/03': {'feast': 'De V die infra Oct Pentecostes', 'rank': 'd1'},
 '05/06/03': {'feast': 'De VI die infra Oct Pentecostes', 'rank': 'd1'},
 '05/07/03': {'feast': 'Sabbato die infra Oct Pentecostes', 'rank': 'd1'},
 '05/13/03': {'feast': 'Feria IV Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '05/15/03': {'feast': 'Feria VI Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '05/16/03': {'feast': 'Sabbato Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '05/17/03': {'feast': 'Dominica Sanctissimæ Trinitatis', 'rank': 'd1'},
 '05/22/03': {'feast': 'De II die infra Oct Corporis Christi', 'rank': 'sd'},
 '05/23/03': {'feast': 'De III die infra Oct Corporis Christi', 'rank': 'sd'},
 '05/25/03': {'feast': 'De V die infra Oct Corporis Christi', 'rank': 'sd'},
 '05/26/03': {'feast': 'De VI die infra Oct Corporis Christi', 'rank': 'sd'},
 '05/27/03': {'feast': 'De VII die infra Oct Corporis Christi', 'rank': 'sd'},
 '05/21/03': {'feast': 'Sanctissimi Corporis Christi', 'rank': 'd1'},
 '05/28/03': {'feast': 'Octava SSmi Corporis Christi', 'rank': 'dm'},
 '05/24/03': {'feast': 'Dominica II post Pentecosten infra Octavam Corporis Christi', 'rank': 'sd'},
 '05/30/03': {'feast': 'De II die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/01/03': {'feast': 'De IV die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/02/03': {'feast': 'De V die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/03/03': {'feast': 'De VI die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/04/03': {'feast': 'De VII die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '05/29/03': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'd1'},
 '06/05/03': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'dm'},
 '05/31/03': {'feast': 'Dominica III post Pentecosten infra Octavam SSmi Cordis DNJC', 'rank': 'sd'},
 '06/07/03': {'feast': 'Dominica V post Pentecosten', 'rank': 'sd'},
 '06/14/03': {'feast': 'Dominica VI post Pentecosten', 'rank': 'sd'},
 '06/21/03': {'feast': 'Dominica VII post Pentecosten', 'rank': 'sd'},
 '06/28/03': {'feast': 'Dominica VIII post Pentecosten', 'rank': 'sd'},
 '07/05/03': {'feast': 'Dominica IX post Pentecosten', 'rank': 'sd'},
 '07/12/03': {'feast': 'Dominica X post Pentecosten', 'rank': 'sd'},
 '07/19/03': {'feast': 'Dominica XI post Pentecosten', 'rank': 'sd'},
 '07/26/03': {'feast': 'Dominica XII post Pentecosten', 'rank': 'sd'},
 '08/02/03': {'feast': 'Dominica XIII post Pentecosten', 'rank': 'sd'},
 '08/09/03': {'feast': 'Dominica XIV post Pentecosten', 'rank': 'sd'},
 '08/16/03': {'feast': 'Dominica XV post Pentecosten', 'rank': 'sd'},
 '08/23/03': {'feast': 'Dominica XVI post Pentecosten', 'rank': 'sd'},
 '08/30/03': {'feast': 'Dominica XVII post Pentecosten', 'rank': 'sd'},
 '09/06/03': {'feast': 'Dominica XVIII post Pentecosten', 'rank': 'sd'},
 '09/13/03': {'feast': 'Dominica XIX post Pentecosten', 'rank': 'sd'},
 '09/16/03': {'feast': 'Feria IV Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/18/03': {'feast': 'Feria VI Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/19/03': {'feast': 'Sabbato Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/20/03': {'feast': 'Dominica XX post Pentecosten', 'rank': 'sd'},
 '09/27/03': {'feast': 'Dominica XXI post Pentecosten', 'rank': 'sd'},
 '10/04/03': {'feast': 'Dominica XXII post Pentecosten', 'rank': 'sd'},
 '10/11/03': {'feast': 'Dominica XXIII post Pentecosten', 'rank': 'sd'},
 '10/18/03': {'feast': 'Dominica XXIV post Pentecosten', 'rank': 'sd'},
 '10/25/03': {'feast': 'Dominica XXV post Pentecosten', 'rank': 'sd'},
 '11/01/03': {'feast': 'Dominica XXVI post Pentecosten', 'rank': 'sd'},
 '11/08/03': {'feast': 'Dominica XXVII post Pentecosten', 'rank': 'sd'},
 '12/20/03': {'feast': 'Dominica IV Adventus', 'rank': 'sd2'},
 '12/13/03': {'feast': 'Dominica III Adventus', 'rank': 'sd2'},
 '12/16/03': {'feast': 'Feria IV Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/18/03': {'feast': 'Feria VI Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/19/03': {'feast': 'Sabbato Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/06/03': {'feast': 'Dominica II Adventus', 'rank': 'sd2'},
 '11/29/03': {'feast': 'Dominica I Adventus', 'rank': 'sd2'},
 '12/25/03': {'feast': 'Nativitas DNJC', 'rank': 'd1'},
 '12/30/03': {'feast': 'Dominica Infra Octavam Nativitatis reposit', 'rank': 'sd'},
 '12/26/03': {'feast': 'S Stephani Protomartyris', 'rank': 'd2'},
 '12/27/03': {'feast': 'S Joannis Ap & Ev', 'rank': 'd2'},
 '12/28/03': {'feast': 'Ss Innocentium Mm', 'rank': 'd2'},
 '12/29/03': {'feast': 'S Thomas EM', 'rank': 'd'},
 '12/31/03': {'feast': 'S Sylvestri I PC', 'rank': 'd'},
}
