temporal = {
 '01/01/44': {'feast': 'Circumcisio Domini et Oct Nativitatis', 'rank': 'd2'},
 '01/02/44': {'feast': 'Octava S Stephani Protomartyris', 'rank': 'sp'},
 '01/03/44': {'feast': 'Octava S Joannis Ap & Ev', 'rank': 'sp'},
 '01/04/44': {'feast': 'Octava Ss Innocentium Mm', 'rank': 'sp'},
 '01/02/44': {'feast': 'SS Nominis Jesu', 'rank': 'd2'},
 '01/28/44': {'feast': 'Dominica in Septuagesima', 'rank': 'sd2'},
 '02/04/44': {'feast': 'Dominica in Sexagesima', 'rank': 'sd2'},
 '02/11/44': {'feast': 'Dominica in Quinquagesima', 'rank': 'sd2'},
 '01/08/44': {'feast': 'De die III infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/09/44': {'feast': 'De die IV infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/10/44': {'feast': 'De die V infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/11/44': {'feast': 'De die VI infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/12/44': {'feast': 'De die VII infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/07/44': {'feast': 'S Familiæ Jesu Mariæ et Joseph; Dominica I post Epiphaniam', 'rank': 'dm'},
 '01/14/44': {'feast': 'Dominica II post Epiphaniam', 'rank': 'sp'},
 '01/21/44': {'feast': 'Dominica III post Epiphaniam', 'rank': 'sp'},
 '02/14/44': {'feast': 'Dies Cinerum', 'rank': 'sp'},
 '02/14/44': {'feast': 'Feria V post Diem Cinerum', 'rank': 'sp'},
 '02/14/44': {'feast': 'Feria VI post Diem Cinerum', 'rank': 'sp'},
 '02/14/44': {'feast': 'Sabbato post Diem Cinerum', 'rank': 'sp'},
 '02/18/44': {'feast': 'Dominica I in Quadragesima', 'rank': 'sd1'},
 '02/19/44': {'feast': 'Feria II infra Hebd I in Quadragesima', 'rank': 'sp'},
 '02/20/44': {'feast': 'Feria III infra Hebd I in Quadragesima', 'rank': 'sp'},
 '02/21/44': {'feast': 'Feria IV Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '02/22/44': {'feast': 'Feria V infra Hebd I in Quadragesima', 'rank': 'sp'},
 '02/23/44': {'feast': 'Feria VI Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '02/24/44': {'feast': 'Sabbato Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '02/25/44': {'feast': 'Dominica II in Quadragesima', 'rank': 'sd1'},
 '02/26/44': {'feast': 'Feria II infra Hebd II in Quadragesima', 'rank': 'sp'},
 '02/27/44': {'feast': 'Feria III infra Hebd II in Quadragesima', 'rank': 'sp'},
 '02/28/44': {'feast': 'Feria IV infra Hebd II in Quadragesima', 'rank': 'sp'},
 '02/29/44': {'feast': 'Feria V infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/01/44': {'feast': 'Feria VI infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/02/44': {'feast': 'Sabbato infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/03/44': {'feast': 'Dominica III in Quadragesima', 'rank': 'sd1'},
 '03/04/44': {'feast': 'Feria II infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/05/44': {'feast': 'Feria III infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/06/44': {'feast': 'Feria IV infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/07/44': {'feast': 'Feria V infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/08/44': {'feast': 'Feria VI infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/09/44': {'feast': 'Sabbato infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/10/44': {'feast': 'Dominica IV in Quadragesima', 'rank': 'sd1'},
 '03/11/44': {'feast': 'Feria II infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/12/44': {'feast': 'Feria III infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/13/44': {'feast': 'Feria IV infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/14/44': {'feast': 'Feria V infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/15/44': {'feast': 'Feria VI infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/16/44': {'feast': 'Sabbato infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/17/44': {'feast': 'Dominica de Passione', 'rank': 'sd1'},
 '03/18/44': {'feast': 'Feria II infra Hebd de Passione', 'rank': 'sp'},
 '03/19/44': {'feast': 'Feria III infra Hebd de Passione', 'rank': 'sp'},
 '03/20/44': {'feast': 'Feria IV infra Hebd de Passione', 'rank': 'sp'},
 '03/21/44': {'feast': 'Feria V infra Hebd de Passione', 'rank': 'sp'},
 '03/22/44': {'feast': 'Septem Dolorum BMV', 'rank': 'dm'},
 '03/23/44': {'feast': 'Sabbato infra Hebd de Passione', 'rank': 'sp'},
 '03/24/44': {'feast': 'Dominica in Palmis', 'rank': 'sd1'},
 '03/25/44': {'feast': 'Feria II Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '03/26/44': {'feast': 'Feria III Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '03/27/44': {'feast': 'Feria IV Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '03/28/44': {'feast': 'Feria V in Cœna Domini', 'rank': 'd1'},
 '03/29/44': {'feast': 'Feria VI in Parasceve', 'rank': 'd1'},
 '03/30/44': {'feast': 'Sabbatum Sanctum', 'rank': 'd1'},
 '03/31/44': {'feast': 'Dominica Resurrectionis', 'rank': 'd1'},
 '04/01/44': {'feast': 'Feria II Paschatis', 'rank': 'd1'},
 '04/02/44': {'feast': 'Feria III Paschatis', 'rank': 'd1'},
 '04/03/44': {'feast': 'De die IV infra Oct Paschæ', 'rank': 'sd'},
 '04/04/44': {'feast': 'De die V infra Oct Paschæ', 'rank': 'sd'},
 '04/05/44': {'feast': 'De die VI infra Oct Paschæ', 'rank': 'sd'},
 '04/06/44': {'feast': 'Sabbatum in Albis', 'rank': 'sd'},
 '04/07/44': {'feast': 'Dominica in Albis', 'rank': 'sd'},
 '04/17/44': {'feast': 'Solemnitas S Joseph, Sponsi BMV C et Ecclesiæ Universalis Patroni', 'rank': 'd1'},
 '04/24/44': {'feast': 'Octava Solemnitas S Joseph', 'rank': 'dm'},
 '04/14/44': {'feast': 'Dominica II post Pascha', 'rank': 'sd'},
 '04/21/44': {'feast': 'Dominica III post Pascha', 'rank': 'sd'},
 '04/28/44': {'feast': 'Dominica IV post Pascha', 'rank': 'sd'},
 '05/06/44': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/07/44': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/08/44': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/08/44': {'feast': 'Vigilæ Ascensionis', 'rank': 'sp'},
 '05/09/44': {'feast': 'Ascensio DNJC', 'rank': 'd1'},
 '05/05/44': {'feast': 'Dominica V post Pascha', 'rank': 'sd'},
 '05/11/44': {'feast': 'De II die infra Oct Ascensionis', 'rank': 'sd'},
 '05/13/44': {'feast': 'De IV die infra Oct Ascensionis', 'rank': 'sd'},
 '05/14/44': {'feast': 'De V die infra Oct Ascensionis', 'rank': 'sd'},
 '05/15/44': {'feast': 'De VI die infra Oct Ascensionis', 'rank': 'sd'},
 '05/12/44': {'feast': 'Dominica infra Octavam Ascensionis', 'rank': 'sd'},
 '05/18/44': {'feast': 'Vigilia Pentecostes', 'rank': 'sd'},
 '05/19/44': {'feast': 'Dominica Pentecostes', 'rank': 'd1'},
 '05/11/44': {'feast': 'De II die infra Oct Pentecostes', 'rank': 'd1'},
 '05/12/44': {'feast': 'De III die infra Oct Pentecostes', 'rank': 'd1'},
 '05/13/44': {'feast': 'De IV die infra Oct Pentecostes', 'rank': 'd1'},
 '05/14/44': {'feast': 'De V die infra Oct Pentecostes', 'rank': 'd1'},
 '05/15/44': {'feast': 'De VI die infra Oct Pentecostes', 'rank': 'd1'},
 '05/16/44': {'feast': 'Sabbato die infra Oct Pentecostes', 'rank': 'd1'},
 '05/22/44': {'feast': 'Feria IV Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '05/24/44': {'feast': 'Feria VI Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '05/25/44': {'feast': 'Sabbato Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '05/26/44': {'feast': 'Dominica Sanctissimæ Trinitatis', 'rank': 'd1'},
 '05/31/44': {'feast': 'De II die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/01/44': {'feast': 'De III die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/03/44': {'feast': 'De V die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/04/44': {'feast': 'De VI die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/05/44': {'feast': 'De VII die infra Oct Corporis Christi', 'rank': 'sd'},
 '05/30/44': {'feast': 'Sanctissimi Corporis Christi', 'rank': 'd1'},
 '06/06/44': {'feast': 'Octava SSmi Corporis Christi', 'rank': 'dm'},
 '06/02/44': {'feast': 'Dominica II post Pentecosten infra Octavam Corporis Christi', 'rank': 'sd'},
 '06/08/44': {'feast': 'De II die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/10/44': {'feast': 'De IV die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/11/44': {'feast': 'De V die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/12/44': {'feast': 'De VI die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/13/44': {'feast': 'De VII die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/07/44': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'd1'},
 '06/14/44': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'dm'},
 '06/09/44': {'feast': 'Dominica III post Pentecosten infra Octavam SSmi Cordis DNJC', 'rank': 'sd'},
 '06/16/44': {'feast': 'Dominica V post Pentecosten', 'rank': 'sd'},
 '06/23/44': {'feast': 'Dominica VI post Pentecosten', 'rank': 'sd'},
 '06/30/44': {'feast': 'Dominica VII post Pentecosten', 'rank': 'sd'},
 '07/07/44': {'feast': 'Dominica VIII post Pentecosten', 'rank': 'sd'},
 '07/14/44': {'feast': 'Dominica IX post Pentecosten', 'rank': 'sd'},
 '07/21/44': {'feast': 'Dominica X post Pentecosten', 'rank': 'sd'},
 '07/28/44': {'feast': 'Dominica XI post Pentecosten', 'rank': 'sd'},
 '08/04/44': {'feast': 'Dominica XII post Pentecosten', 'rank': 'sd'},
 '08/11/44': {'feast': 'Dominica XIII post Pentecosten', 'rank': 'sd'},
 '08/18/44': {'feast': 'Dominica XIV post Pentecosten', 'rank': 'sd'},
 '08/25/44': {'feast': 'Dominica XV post Pentecosten', 'rank': 'sd'},
 '09/01/44': {'feast': 'Dominica XVI post Pentecosten', 'rank': 'sd'},
 '09/08/44': {'feast': 'Dominica XVII post Pentecosten', 'rank': 'sd'},
 '09/15/44': {'feast': 'Dominica XVIII post Pentecosten', 'rank': 'sd'},
 '09/18/44': {'feast': 'Feria IV Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/20/44': {'feast': 'Feria VI Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/21/44': {'feast': 'Sabbato Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/22/44': {'feast': 'Dominica XIX post Pentecosten', 'rank': 'sd'},
 '09/29/44': {'feast': 'Dominica XX post Pentecosten', 'rank': 'sd'},
 '10/06/44': {'feast': 'Dominica XXI post Pentecosten', 'rank': 'sd'},
 '10/13/44': {'feast': 'Dominica XXII post Pentecosten', 'rank': 'sd'},
 '10/20/44': {'feast': 'Dominica XXIII post Pentecosten', 'rank': 'sd'},
 '10/27/44': {'feast': 'Dominica XXIV post Pentecosten', 'rank': 'sd'},
 '11/03/44': {'feast': 'Dominica XXV post Pentecosten', 'rank': 'sd'},
 '11/10/44': {'feast': 'Dominica XXVI post Pentecosten', 'rank': 'sd'},
 '11/17/44': {'feast': 'Dominica XXVII post Pentecosten', 'rank': 'sd'},
 '12/22/44': {'feast': 'Dominica IV Adventus', 'rank': 'sd2'},
 '12/15/44': {'feast': 'Dominica III Adventus', 'rank': 'sd2'},
 '12/18/44': {'feast': 'Feria IV Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/20/44': {'feast': 'Feria VI Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/21/44': {'feast': 'Sabbato Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/08/44': {'feast': 'Dominica II Adventus', 'rank': 'sd2'},
 '12/01/44': {'feast': 'Dominica I Adventus', 'rank': 'sd2'},
 '12/25/44': {'feast': 'Nativitas DNJC', 'rank': 'd1'},
 '12/29/44': {'feast': 'Dominica Infra Octavam Nativitatis', 'rank': 'sd'},
 '12/30/44': {'feast': 'De VI Die infra Octavam Nativitatis', 'rank': 'sd'},
 '12/26/44': {'feast': 'S Stephani Protomartyris', 'rank': 'd2'},
 '12/27/44': {'feast': 'S Joannis Ap & Ev', 'rank': 'd2'},
 '12/28/44': {'feast': 'Ss Innocentium Mm', 'rank': 'd2'},
 '12/29/44': {'feast': 'S Thomas EM', 'rank': 'd'},
 '12/31/44': {'feast': 'S Sylvestri I PC', 'rank': 'd'},
}
