temporal = {
 '01/01/18': {'feast': 'Circumcisio Domini et Oct Nativitatis', 'rank': 'd2'},
 '01/02/18': {'feast': 'Octava S Stephani Protomartyris', 'rank': 'sp'},
 '01/03/18': {'feast': 'Octava S Joannis Ap & Ev', 'rank': 'sp'},
 '01/04/18': {'feast': 'Octava Ss Innocentium Mm', 'rank': 'sp'},
 '01/02/18': {'feast': 'SS Nominis Jesu', 'rank': 'd2'},
 '02/04/18': {'feast': 'Dominica in Septuagesima', 'rank': 'sd2'},
 '02/11/18': {'feast': 'Dominica in Sexagesima', 'rank': 'sd2'},
 '02/18/18': {'feast': 'Dominica in Quinquagesima', 'rank': 'sd2'},
 '01/08/18': {'feast': 'De die III infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/09/18': {'feast': 'De die IV infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/10/18': {'feast': 'De die V infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/11/18': {'feast': 'De die VI infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/12/18': {'feast': 'De die VII infra Oct Epiphaniæ', 'rank': 'sd'},
 '01/07/18': {'feast': 'S Familiæ Jesu Mariæ et Joseph; Dominica I post Epiphaniam', 'rank': 'dm'},
 '01/14/18': {'feast': 'Dominica II post Epiphaniam', 'rank': 'sp'},
 '01/21/18': {'feast': 'Dominica III post Epiphaniam', 'rank': 'sp'},
 '01/28/18': {'feast': 'Dominica IV post Epiphaniam', 'rank': 'sp'},
 '02/21/18': {'feast': 'Dies Cinerum', 'rank': 'sp'},
 '02/21/18': {'feast': 'Feria V post Diem Cinerum', 'rank': 'sp'},
 '02/21/18': {'feast': 'Feria VI post Diem Cinerum', 'rank': 'sp'},
 '02/21/18': {'feast': 'Sabbato post Diem Cinerum', 'rank': 'sp'},
 '02/25/18': {'feast': 'Dominica I in Quadragesima', 'rank': 'sd1'},
 '02/26/18': {'feast': 'Feria II infra Hebd I in Quadragesima', 'rank': 'sp'},
 '02/27/18': {'feast': 'Feria III infra Hebd I in Quadragesima', 'rank': 'sp'},
 '02/28/18': {'feast': 'Feria IV Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/01/18': {'feast': 'Feria V infra Hebd I in Quadragesima', 'rank': 'sp'},
 '03/02/18': {'feast': 'Feria VI Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/03/18': {'feast': 'Sabbato Quattuor Temporum Quadragesimæ', 'rank': 'sp'},
 '03/04/18': {'feast': 'Dominica II in Quadragesima', 'rank': 'sd1'},
 '03/05/18': {'feast': 'Feria II infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/06/18': {'feast': 'Feria III infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/07/18': {'feast': 'Feria IV infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/08/18': {'feast': 'Feria V infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/09/18': {'feast': 'Feria VI infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/10/18': {'feast': 'Sabbato infra Hebd II in Quadragesima', 'rank': 'sp'},
 '03/11/18': {'feast': 'Dominica III in Quadragesima', 'rank': 'sd1'},
 '03/12/18': {'feast': 'Feria II infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/13/18': {'feast': 'Feria III infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/14/18': {'feast': 'Feria IV infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/15/18': {'feast': 'Feria V infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/16/18': {'feast': 'Feria VI infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/17/18': {'feast': 'Sabbato infra Hebd III in Quadragesima', 'rank': 'sp'},
 '03/18/18': {'feast': 'Dominica IV in Quadragesima', 'rank': 'sd1'},
 '03/19/18': {'feast': 'Feria II infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/20/18': {'feast': 'Feria III infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/21/18': {'feast': 'Feria IV infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/22/18': {'feast': 'Feria V infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/23/18': {'feast': 'Feria VI infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/24/18': {'feast': 'Sabbato infra Hebd IV in Quadragesima', 'rank': 'sp'},
 '03/25/18': {'feast': 'Dominica de Passione', 'rank': 'sd1'},
 '03/26/18': {'feast': 'Feria II infra Hebd de Passione', 'rank': 'sp'},
 '03/27/18': {'feast': 'Feria III infra Hebd de Passione', 'rank': 'sp'},
 '03/28/18': {'feast': 'Feria IV infra Hebd de Passione', 'rank': 'sp'},
 '03/29/18': {'feast': 'Feria V infra Hebd de Passione', 'rank': 'sp'},
 '03/30/18': {'feast': 'Septem Dolorum BMV', 'rank': 'dm'},
 '03/31/18': {'feast': 'Sabbato infra Hebd de Passione', 'rank': 'sp'},
 '04/01/18': {'feast': 'Dominica in Palmis', 'rank': 'sd1'},
 '04/02/18': {'feast': 'Feria II Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/03/18': {'feast': 'Feria III Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/04/18': {'feast': 'Feria IV Majoris Hebd; Feria Priv', 'rank': 'sp'},
 '04/05/18': {'feast': 'Feria V in Cœna Domini', 'rank': 'd1'},
 '04/06/18': {'feast': 'Feria VI in Parasceve', 'rank': 'd1'},
 '04/07/18': {'feast': 'Sabbatum Sanctum', 'rank': 'd1'},
 '04/08/18': {'feast': 'Dominica Resurrectionis', 'rank': 'd1'},
 '04/09/18': {'feast': 'Feria II Paschatis', 'rank': 'd1'},
 '04/10/18': {'feast': 'Feria III Paschatis', 'rank': 'd1'},
 '04/11/18': {'feast': 'De die IV infra Oct Paschæ', 'rank': 'sd'},
 '04/12/18': {'feast': 'De die V infra Oct Paschæ', 'rank': 'sd'},
 '04/13/18': {'feast': 'De die VI infra Oct Paschæ', 'rank': 'sd'},
 '04/14/18': {'feast': 'Sabbatum in Albis', 'rank': 'sd'},
 '04/15/18': {'feast': 'Dominica in Albis', 'rank': 'sd'},
 '04/25/18': {'feast': 'Solemnitas S Joseph, Sponsi BMV C et Ecclesiæ Universalis Patroni', 'rank': 'd1'},
 '05/02/18': {'feast': 'Octava Solemnitas S Joseph', 'rank': 'dm'},
 '04/22/18': {'feast': 'Dominica II post Pascha', 'rank': 'sd'},
 '04/29/18': {'feast': 'Dominica III post Pascha', 'rank': 'sd'},
 '05/06/18': {'feast': 'Dominica IV post Pascha', 'rank': 'sd'},
 '05/14/18': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/15/18': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/16/18': {'feast': 'Litaniæ Minores', 'rank': 'sp'},
 '05/16/18': {'feast': 'Vigilæ Ascensionis', 'rank': 'sp'},
 '05/17/18': {'feast': 'Ascensio DNJC', 'rank': 'd1'},
 '05/13/18': {'feast': 'Dominica V post Pascha', 'rank': 'sd'},
 '05/19/18': {'feast': 'De II die infra Oct Ascensionis', 'rank': 'sd'},
 '05/21/18': {'feast': 'De IV die infra Oct Ascensionis', 'rank': 'sd'},
 '05/22/18': {'feast': 'De V die infra Oct Ascensionis', 'rank': 'sd'},
 '05/23/18': {'feast': 'De VI die infra Oct Ascensionis', 'rank': 'sd'},
 '05/20/18': {'feast': 'Dominica infra Octavam Ascensionis', 'rank': 'sd'},
 '05/26/18': {'feast': 'Vigilia Pentecostes', 'rank': 'sd'},
 '05/27/18': {'feast': 'Dominica Pentecostes', 'rank': 'd1'},
 '05/19/18': {'feast': 'De II die infra Oct Pentecostes', 'rank': 'd1'},
 '05/20/18': {'feast': 'De III die infra Oct Pentecostes', 'rank': 'd1'},
 '05/21/18': {'feast': 'De IV die infra Oct Pentecostes', 'rank': 'd1'},
 '05/22/18': {'feast': 'De V die infra Oct Pentecostes', 'rank': 'd1'},
 '05/23/18': {'feast': 'De VI die infra Oct Pentecostes', 'rank': 'd1'},
 '05/24/18': {'feast': 'Sabbato die infra Oct Pentecostes', 'rank': 'd1'},
 '05/30/18': {'feast': 'Feria IV Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/01/18': {'feast': 'Feria VI Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/02/18': {'feast': 'Sabbato Quattuor infra Temporum Pentecostes', 'rank': 'd1'},
 '06/03/18': {'feast': 'Dominica Sanctissimæ Trinitatis', 'rank': 'd1'},
 '06/08/18': {'feast': 'De II die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/09/18': {'feast': 'De III die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/11/18': {'feast': 'De V die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/12/18': {'feast': 'De VI die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/13/18': {'feast': 'De VII die infra Oct Corporis Christi', 'rank': 'sd'},
 '06/07/18': {'feast': 'Sanctissimi Corporis Christi', 'rank': 'd1'},
 '06/14/18': {'feast': 'Octava SSmi Corporis Christi', 'rank': 'dm'},
 '06/10/18': {'feast': 'Dominica II post Pentecosten infra Octavam Corporis Christi', 'rank': 'sd'},
 '06/16/18': {'feast': 'De II die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/18/18': {'feast': 'De IV die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/19/18': {'feast': 'De V die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/20/18': {'feast': 'De VI die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/21/18': {'feast': 'De VII die infra Oct Ss Cordis Jesu', 'rank': 'sd'},
 '06/15/18': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'd1'},
 '06/22/18': {'feast': 'Sacratissimi Cordis Jesu', 'rank': 'dm'},
 '06/17/18': {'feast': 'Dominica III post Pentecosten infra Octavam SSmi Cordis DNJC', 'rank': 'sd'},
 '06/24/18': {'feast': 'Dominica V post Pentecosten', 'rank': 'sd'},
 '07/01/18': {'feast': 'Dominica VI post Pentecosten', 'rank': 'sd'},
 '07/08/18': {'feast': 'Dominica VII post Pentecosten', 'rank': 'sd'},
 '07/15/18': {'feast': 'Dominica VIII post Pentecosten', 'rank': 'sd'},
 '07/22/18': {'feast': 'Dominica IX post Pentecosten', 'rank': 'sd'},
 '07/29/18': {'feast': 'Dominica X post Pentecosten', 'rank': 'sd'},
 '08/05/18': {'feast': 'Dominica XI post Pentecosten', 'rank': 'sd'},
 '08/12/18': {'feast': 'Dominica XII post Pentecosten', 'rank': 'sd'},
 '08/19/18': {'feast': 'Dominica XIII post Pentecosten', 'rank': 'sd'},
 '08/26/18': {'feast': 'Dominica XIV post Pentecosten', 'rank': 'sd'},
 '09/02/18': {'feast': 'Dominica XV post Pentecosten', 'rank': 'sd'},
 '09/09/18': {'feast': 'Dominica XVI post Pentecosten', 'rank': 'sd'},
 '09/16/18': {'feast': 'Dominica XVII post Pentecosten', 'rank': 'sd'},
 '09/19/18': {'feast': 'Feria IV Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/21/18': {'feast': 'Feria VI Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/22/18': {'feast': 'Sabbato Quattuor Temporum Septembris', 'rank': 'sd'},
 '09/23/18': {'feast': 'Dominica XVIII post Pentecosten', 'rank': 'sd'},
 '09/30/18': {'feast': 'Dominica XIX post Pentecosten', 'rank': 'sd'},
 '10/07/18': {'feast': 'Dominica XX post Pentecosten', 'rank': 'sd'},
 '10/14/18': {'feast': 'Dominica XXI post Pentecosten', 'rank': 'sd'},
 '10/21/18': {'feast': 'Dominica XXII post Pentecosten', 'rank': 'sd'},
 '10/28/18': {'feast': 'Dominica XXIII post Pentecosten', 'rank': 'sd'},
 '11/04/18': {'feast': 'Dominica XXIV post Pentecosten', 'rank': 'sd'},
 '11/11/18': {'feast': 'Dominica XXV post Pentecosten', 'rank': 'sd'},
 '11/18/18': {'feast': 'Dominica XXVI post Pentecosten', 'rank': 'sd'},
 '11/25/18': {'feast': 'Dominica XXVII post Pentecosten', 'rank': 'sd'},
 '12/23/18': {'feast': 'Dominica IV Adventus', 'rank': 'sd2'},
 '12/16/18': {'feast': 'Dominica III Adventus', 'rank': 'sd2'},
 '12/19/18': {'feast': 'Feria IV Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/21/18': {'feast': 'Feria VI Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/22/18': {'feast': 'Sabbato Quattuor Temporum in Adventu', 'rank': 'sp'},
 '12/09/18': {'feast': 'Dominica II Adventus', 'rank': 'sd2'},
 '12/02/18': {'feast': 'Dominica I Adventus', 'rank': 'sd2'},
 '12/25/18': {'feast': 'Nativitas DNJC', 'rank': 'd1'},
 '12/30/18': {'feast': 'Dominica Infra Octavam Nativitatis', 'rank': 'sd'},
 '12/30/18': {'feast': 'De VI Die infra Octavam Nativitatis', 'rank': 'sd'},
 '12/26/18': {'feast': 'S Stephani Protomartyris', 'rank': 'd2'},
 '12/27/18': {'feast': 'S Joannis Ap & Ev', 'rank': 'd2'},
 '12/28/18': {'feast': 'Ss Innocentium Mm', 'rank': 'd2'},
 '12/29/18': {'feast': 'S Thomas EM', 'rank': 'd'},
 '12/31/18': {'feast': 'S Sylvestri I PC', 'rank': 'd'},
}
